### ISSUE TITLE
failed to get network resource

### ISSUE THREAD

**Issue by Elegant996** [intel/multus-cni#101]
Hello,
Multus was recently built using the `network-plumbing-working-group-crd-change` branch and the [examples](https://github.com/intel/multus-cni/tree/dev/network-plumbing-working-group-crd-change/examples) were followed to create the `samplepod`. Unfortunately, the pod is not created and the below errors can be seen on the node using `journalctl` or `systemctl status kubelet`:

```
cni.go:243] CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "2f3e60dd3ff2ed4928d2164a0b6ec704582da33fdeaaf916640c15abde20a45b"
cni.go:280] Error deleting network: Multus: Err in getting k8s network from pod: GetK8sNetwork: failed getting the delegate: getKubernetesDelegate: failed to get network resource, refer Multus README.md for the usage guide: unknown
remote_runtime.go:115] StopPodSandbox "2f3e60dd3ff2ed4928d2164a0b6ec704582da33fdeaaf916640c15abde20a45b" from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod "samplepod_default" network: Multus: Err in getting k8s network from pod: GetK8sNetwork: failed getting the delegate: getKubernetesDelegate: failed to get network resource, refer Multus README.md for the usage guide: unknown
kuberuntime_manager.go:799] Failed to stop sandbox {"docker" "2f3e60dd3ff2ed4928d2164a0b6ec704582da33fdeaaf916640c15abde20a45b"}
kuberuntime_manager.go:594] killPodWithSyncResult failed: failed to "KillPodSandbox" for "01670bb6-8e2b-11e8-a5b3-000c29616bad" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"samplepod_default\" network: Multus: Err in getting k8s network from pod: GetK8sNetwork: failed getting the delegate: getKubernetesDelegate: failed to get network resource, refer Multus README.md for the usage guide: unknown"
pod_workers.go:186] Error syncing pod 01670bb6-8e2b-11e8-a5b3-000c29616bad ("samplepod_default(01670bb6-8e2b-11e8-a5b3-000c29616bad)"), skipping: failed to "KillPodSandbox" for "01670bb6-8e2b-11e8-a5b3-000c29616bad" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"samplepod_default\" network: Multus: Err in getting k8s network from pod: GetK8sNetwork: failed getting the delegate: getKubernetesDelegate: failed to get network resource, refer Multus README.md for the usage guide: unknown"
```

Multus appears to fail to obtain the network resource and everything just stops. Below is also a list of the current pods in all namespaces:

```
[root@Kube-Master ~]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                                   READY     STATUS              RESTARTS   AGE
default       samplepod                                              0/1       ContainerCreating   0          1d
kube-system   coredns-78fcdf6894-2dgkn                               1/1       Running             0          1d
kube-system   coredns-78fcdf6894-zwt9c                               1/1       Running             0          1d
kube-system   etcd-kube-master.example.com                           1/1       Running             0          1d
kube-system   kube-apiserver-kube-master.example.com                 1/1       Running             0          1d
kube-system   kube-controller-manager-kube-master.example.com        1/1       Running             0          1d
kube-system   kube-multus-ds-88ts8                                   1/1       Running             0          1d
kube-system   kube-multus-ds-pgplg                                   1/1       Running             0          1d
kube-system   kube-proxy-6smwx                                       1/1       Running             0          1d
kube-system   kube-proxy-t8jqv                                       1/1       Running             0          1d
kube-system   kube-scheduler-kube-master.example.com                 1/1       Running             0          1d
```

This is with a fresh install of Kubernetes 1.11.1 as well as the latest commit of the CNI Plugins on Fedora 28. The only change to the example is that `master` was swapped from `eth0` to `net0` to match the interface name on the VM.

Unsure what could be blocking Multus from obtaining the network resource especially on a fresh build but thought it best to report.

**Comment by s1061123** [comment]
@Elegant996 , thank you for your pointing! Let me take a look into it.

Could you please previous version (e.g. v2.0) for now if you want to use it?
https://github.com/intel/multus-cni/releases/tag/v2.0

**Comment by s1061123** [comment]
@Elegant996 For more detail, could you please let me know which network is used for default overlay network?

**Comment by rkamudhan** [comment]
It looks like RBAC rules issue.. Are you using kubeadm or kubespray in your setup.

**Comment by Elegant996** [comment]
@s1061123 default overlay is flannel per [`multus-with-flannel.yml`](https://github.com/intel/multus-cni/blob/dev/network-plumbing-working-group-crd-change/examples/multus-with-flannel.yml) in the example.

@rkamudhan kubeadm was used to create the setup, but the `clusterrole` and `clusterrolebinding` were created for each node including the master.

[`clusterrole.yml`](https://github.com/intel/multus-cni/blob/dev/network-plumbing-working-group-crd-change/examples/clusterrole.yml)

```
kubectl create clusterrolebinding multus-node-Kube-Master.example.com\
    --clusterrole=multus-crd-overpowered \
    --user=system:node:Kube-Master.example.com
kubectl create clusterrolebinding multus-node-Kube-Node01.example.com\
    --clusterrole=multus-crd-overpowered \
    --user=system:node:Kube-Node01.example.com
```

**Comment by dougbtv** [comment]
Awesome that solved the RBAC issue. 

Some of the examples were in flux, so if you hadn't updated your branch in a couple days, it might've had a mis-match between the CRD and the example.

First up, try using [this latest example pod spec](https://github.com/intel/multus-cni/blob/2f96fa302a92c199fef27049e210131321e9de51/examples/sample-pod.yml)

If that doesn't work, can you please for me, show the output of:

```bash 
# in multus directory
git rev-parse HEAD
cat examples/sample-pod.yml
# from master or wherever you can run kubectl
kubectl get crd
kubectl describe crd network-attachment-definition
kubectl get network-attachment-definition
kubectl describe network-attachment-definition macvlan-conf
```

Thanks!

**Comment by Elegant996** [comment]
Was definitely the case for the `examples/sample-pod.yml`, I switched my head to `2f96fa302a92c199fef27049e210131321e9de51` as well and rebuilt; the interface is now created when using `macvlan`. Thanks!
