### ISSUE TITLE
Specify default network by name

### ISSUE THREAD

**Issue by squeed** [intel/multus-cni#131]
It would be nice to be able to specify the default network by name in the multus configuration file. This has a couple advantanges:

1. It allows for CNI configurations that are more dynamic
2. It works well with existing self-hosted plugins, e.g. Calico, that write their CNI configuration file via a daemonset
3. It also solves the readiness problem fixed in #98 in a slightly neater way.

It could take advantage of the already existing `getCNIConfigFromFile` function, so this should be pretty easy.

Thoughts? I can have a PR for this relatively quickly.

**Comment by dougbtv** [comment]
Hey Casey, just trying to verify my understanding of this so...

Like today, we have the default network CNI configuration packed into say `/etc/cni/net.d/00-multus.conf` that looks like:

```
    {
      "name": "multus-cni-network",
      "type": "multus",
      "delegates": [
        {
          "type": "flannel",
          "name": "flannel.1",
          "delegate": {
            "isDefaultGateway": true
          }
        }
      ],
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
    }
```

Instead, we'd have a way to otherwise specify the default network with something like...

```
    {
      "name": "multus-cni-network",
      "type": "multus",
      "default": "calico",
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
    }
```

And then it'd pull up say, Calico either via CRD object or file on disk?

**Comment by squeed** [comment]
@dougbtv yeah, that was my idea - thanks for elaborating it!

**Comment by rkamudhan** [comment]
@squeed Thanks for the thoughts on it. @dougbtv PR is help us to check a plugin readiness, it need not to be default network. 

I see your idea is making sense to use the on-disk file as the default network. so delegate, gives a opportunity to attach multiple networks, with out any Network CRD objects itself. So I am thinking we can change the name `delegates` to `defaultnetworks` and make it to accept both network name or array of networks conf ? Is that ok for you guys ?

**Comment by dougbtv** [comment]
I really like this idea, and I'm all for it. I also have uses for making the default plugin more flexible, so, I'm all for it for sure. Thanks @squeed

**Comment by squeed** [comment]
cc @dcbw, who wanted to take a look.

**Comment by s1061123** [comment]
Let's close it because #169 address the issue and now we can specify network-attachment name to specify defaultNetwork as well as clusterNetwork.
