### ISSUE TITLE
Is there a way to integrate with kubeDNS?

### ISSUE THREAD

**Issue by wzrdtales** [intel/multus-cni#133]
Is there a way to integrate with kubeDNS? Still trying to dig through the sources did not find any documents on how names actually get propagated to kubeDNS, so if someone here knows already would be pleased if you could tell me :)

Otherwise I will let you know as soon as I've found the point where it propagates...

**Comment by rkamudhan** [comment]
You want to run kube-dns pod with Multus ?

**Comment by wzrdtales** [comment]
Not running it with multus, but propagating the ips from a secondary interface to multus for discovery.

**Comment by rkamudhan** [comment]
Awesome!! We are currently working with stalkholder to define the implementation on this.

**Comment by rkamudhan** [comment]
Red Hat folks and myself were working on the Multi-netwok service impact almost a year back - https://docs.google.com/document/d/1Q2hJou2Jjoyng9tawt8IhoueHlvD8nrxAv7lQ9_6EEQ/edit#heading=h.izm7jgs60a9b . Getting you some document from the dust.. Please have a look at it.. it explain the way it could work. We later killed this proposal due to complexity on the Kubernetes Core components. But it will give you the idea on the cluster IP and routing information that we required to do on the Multi-network.

**Comment by wzrdtales** [comment]
Is there any follow up plan on this yet? Or will this simply not happen? The serviceCIDR approach for the clusterIP is reasonable though.

**Comment by wzrdtales** [comment]
Ok cool, also discovered that there are actually two solutions right now aiming to do quite the same https://github.com/Huawei-PaaS/CNI-Genie, I hope that is not ending up in two different conversations about the same thing.

I think for the DNS probably going for etcd and coredns with the etcd plugin could be an easy solution, but a standard that is actually generally more aware of multiple networks would be probably better.

**Comment by mJace** [comment]
@rkamudhan  Hi, Is there any update about this? I'm highly interested in this feature/issue.

**Comment by rkamudhan** [comment]
@mJace I am no longer part of Multus. @s1061123  and @dougbtv from Red Hat will help your query.

**Comment by dougbtv** [comment]
KubeDNS has been deprecated by CoreDNS -- although we agree that DNS records for secondary interfaces is necessary. If you're still looking for a solution, may we suggest that you add an agenda item to the NPWG agenda @ https://www.google.com/url?q=https://docs.google.com/document/d/1oE93V3SgOGWJ4O1zeD1UmpeToa0ZiiO6LqRAmZBPFWM/edit&sa=D&ust=1585147325830000&usg=AOvVaw0OPUEz-BGEGL572YIlXpyW

Thanks!
