### ISSUE TITLE
Dynamically creating overlays with multus

### ISSUE THREAD

**Issue by little-dude** [intel/multus-cni#147]
Hi,

I'm trying to use multus to dynamically define topologies. What I call "topology" is a k8s manifest that defines `pods` and `net-attach-def` such that the pods have multiple links with each other.

I'm thinking of using flannel for this, since apparently I [can have multiple flannel networks](https://coreos.com/flannel/docs/latest/running.html#multiple-networks). This sounds similar to https://github.com/intel/multus-cni/issues/7 but not quite: I want the creation and deletion of flannel networks to be dynamic. I don't know in advance how many networks I'll need.

I'm unsure if multus will help me here, because if I understand correctly, I'll need to run one flanneld instance for each network, and multus won't help me with that. It will only call the flannel plugin to create the interfaces in the containers, and attach them to the flannel bridge.

Do you have any pointers for what I'm trying to achieve? Or is multus not the right tool for me?

**Comment by dougbtv** [comment]
Hey Corentin, I need to think about this -- and I'm replying mobile, so
it's brief (sorry) but... I'm curious about your use case -- would you
attach these dynamically during run-time? That's something we are likely
going to consider for v4, I believe.

Join up the slack at some point, too. Worth discussing and documenting here
to capture the use case. Sounds interesting

**Comment by little-dude** [comment]
Hi Doung!

> I'm curious about your use case -- would you attach these dynamically during run-time?

We're building a networking product. To test it, we want to be able to create topologies where multiple  docker containers are connected to each other in various ways, and destroy these topologies after the tests finished.


> That's something we are likely going to consider for v4, I believe.

That would be awesome !

**Comment by dougbtv** [comment]
@little-dude -- do you think you could expand on the use case here? We're not sure if it's necessarily proper for Multus to dynamically create more Flannels networks (and... I might be misunderstanding your issue again as I re-read a little later). Network attachment dynamically is definitely on our radar.

At any rate -- want to make sure we're addressing your concerns before we close out the issue, and... Don't want to close it if we haven't addressed your concerns and/or learned from it!!

Thanks for sure

**Comment by onixie** [comment]
@dougbtv 
I'd like to ask how the dynamically network attaching is going since the last comment was 1 years ago.
In our company, we are heavily relying on multus-cni and we also have some real use case for the dynamic attachment.

**Comment by dougbtv** [comment]
Currently we do not have plans to manage dynamic attachments for Multus CNI.

One suggestion may be to create a custom controller to watch net-attach-defs and then take action when they're added/removed/changed/etc. 

We're still curious about use cases, and we'd love to have them shared with the NPWG to help further explore this topic, more details @ https://www.google.com/url?q=https://docs.google.com/document/d/1oE93V3SgOGWJ4O1zeD1UmpeToa0ZiiO6LqRAmZBPFWM/edit&sa=D&ust=1585147325830000&usg=AOvVaw0OPUEz-BGEGL572YIlXpyW
