### ISSUE TITLE
delPlugins not cleaning up and causing resource leak

### ISSUE THREAD

**Issue by pkdas** [intel/multus-cni#152]
A POD may have multiple networks
net1, net2, net3, net4...
If delPlugin for any of these nets fail, it skips calling delegateDel
For instance if delegateDel fails on net1, the net2..net4 are not deleted.
If net2..net4 are SRIOV VFs - these are never released and as a result SRIOV CNI runs out of VFs as PODs deleted and recreated. 

And it can bring the whole Node down, because Multus keeps reporting error and Kubelet keep retrying to create a POD and filling up the entire /tmp filesystem with Multus error/warn files. It's not clear why Multus log messages show up in /tmp folder. There is one file created per multus log message. Rebooting the node does not work. The workaround is to stop in BIOS, get into grub and delete all multus error log files from /tmp and reboot.

func delPlugins(exec invoke.Exec, argIfname string, delegates []*types.DelegateNetConf, lastIdx int, rt *libcni.RuntimeConf, binDir string) error {
	logging.Debugf("delPlugins: %v, %s, %v, %d, %v, %s", exec, argIfname, delegates, lastIdx, rt, binDir)
	if os.Setenv("CNI_COMMAND", "DEL") != nil {
		return logging.Errorf("Multus: error in setting CNI_COMMAND to DEL")
	}

	for idx := lastIdx; idx >= 0; idx-- {
		ifName := getIfname(delegates[idx], argIfname, idx)
		rt.IfName = ifName
		if err := delegateDel(exec, ifName, delegates[idx], rt, binDir); err != nil {
			//return err - resource leak
                        // workaround
                       logging.Errorf("Multus: Err in delegateDel: %s %v continuing next delegateDel", ifName, err)
		}
	}

	return nil
}

**Comment by rkamudhan** [comment]
I understood the issue, I will provide the fix for it

**Comment by s1061123** [comment]
Closed due to fixed at #201 . Please re-open it if you found something related.
