### ISSUE TITLE
SVG or AI version of the Multus logo

### ISSUE THREAD

**Issue by dankohn** [intel/multus-cni#156]
I'd like to add Multus to CNCF's Interactive Landscape: https://landscape.cncf.io/grouping=landscape&landscape=cloud-native-network

I need an SVG, AI, or EPS version of your logo. You can upload it here (you need to zip it first) or email to dan at linuxfoundation.org. Thank you.

**Comment by rkamudhan** [comment]
@dankohn Thanks a lot for reach out to us @dougbtv also mention it to be. I will send you the SVG file.

**Comment by rkamudhan** [comment]
[Multus logo.zip](https://github.com/intel/multus-cni/files/2440140/Multus.logo.zip)

@dankohn @dougbtv here is the Multus logo as zip, in SVG format

**Comment by dankohn** [comment]
Thanks, but that's not a real SVG, it's a PNG encapsulated in an SVG. You can tell, because it's blurry.

Could you please ask the designer for the original AI or EPS file. If you can't find it, we can recreate the logo for you

**Comment by dankohn** [comment]
And here you go: https://landscape.cncf.io/grouping=landscape&landscape=cloud-native-network&selected=multus

Thanks everyone for your assistance.
