### ISSUE TITLE
Cache CRD data at the CmdAdd() for graceful pod network deletion

### ISSUE THREAD

**Issue by s1061123** [intel/multus-cni#164]
When CRD data is changed before CmdDel(), multus may call wrong CNI plugin (or arguments) at CmdDel(), hence it may be necessary.

**Comment by s1061123** [comment]
Currently CRD is cahced, but json file should be cached

**Comment by ahalim-intel** [comment]
> Currently CRD is cahced, but json file should be cached

All 'delegate' objects should be cached. This would eliminate the need of out-of-cluster communication  on CmdDel() as well and deletion would be faster.

**Comment by dcbw** [comment]
Yeah, Multus should cache the specific JSON sent to stdin for each sub-plugin/delegate.

**Comment by dougbtv** [comment]
In the meanwhile, this should be documented as "you should add new CR's, not change the CR's"

**Comment by gageorsburn** [comment]
This definitely should be cached. If a namespace is deleted the NAD CRD could get deleted before the pod which will cause Multus to error on unplugging the interface.

**Comment by gageorsburn** [comment]
Are there any plans for implementation on this? If nobody has picked it up yet I could give it a shot.
