### ISSUE TITLE
Add option '--is-default-ready' to check its readiness.

### ISSUE THREAD

**Issue by s1061123** [intel/multus-cni#166]
See https://github.com/intel/multus-cni/pull/98#issuecomment-428598120 for the detail.

-------
@dougbtv 's comments:
Idea: We run this as a startup option -- that is, this happens to look for a file (or CRD object) before Multus runs, so you say run multus as ./multus --is-default-ready /target/file.name or ./multus --is-default-ready my-crd-name and it reports back saying that it's ready or not. So that we don't have the entrypoint script runs first before this happens, this might be better for configuration management, especially relative to an operator-style management of cni plugin configuration.

**Comment by dougbtv** [comment]
This is covered by the `--readiness-indicator-file` option :)
