### ISSUE TITLE
Multus bin&conf missing in OpenShift after compute node is rebooted

### ISSUE THREAD

**Issue by flyinghawkren** [intel/multus-cni#173]
Hi, @dougbtv. I have successfully deployed multus in OpenShift origin 3.10. And I have checked the bin&conf files (/opt/cni/bin/multus and /etc/cni/net.d/70-multus.conf) in compute nods and all is ok.
**But after I reboot any compute node, I found that the multus bin&conf files was missing.**

FYI: I deploy multus with the following command into a existing cluster:
`$ ansible-playbook -i inventory/above.inventory playbooks/openshift-multinetwork/config.yml`

**Comment by dougbtv** [comment]
Hey @flyinghawkren -- I take it you are using my openshift-ansible fork to install it -- which branch are you using on my fork @ https://github.com/dougbtv/openshift-ansible ?

In theory -- the best branch to use should be the `multus-developer-preview` branch @ https://github.com/dougbtv/openshift-ansible/tree/multus-developer-preview/playbooks/openshift-multinetwork -- this has a daemonset-style install, which in theory should reinstall the binaries in the right spots after a reboot.

**Comment by dougbtv** [comment]
Additionally -- one thing is that your original cluster install will need to have this patch -- https://github.com/openshift/openshift-ansible/pull/7825

Without that patch, there's a chance that the portions that manage OpenShift-SDN can clobber the binaries as they're managed by the Multus daemonset.

**Comment by flyinghawkren** [comment]
Sorry for the late reply.Thank you very much!

I have test the new openshift-sdn daemonset, and files in /opt/cni/bin are OK now.
Thanks~ This issue can be closed.
