### ISSUE TITLE
Chances to change the default route. Is this a use case ?

### ISSUE THREAD

**Issue by rkamudhan** [intel/multus-cni#175]

**Comment by s1061123** [comment]
I've heard that some VPN case could be the one. (but now there is no CNI plugin for VPN yet, so it could be a future case)

I suppose IP routing can be one possible challenges in multi interface.

 In current CNI specification, user and CNI plugin can add IP route, but user cannot
delete/filter ip routes added by CNI plugins. In case of multus multiple interface,
non master plugin cannot change the route added by master plugin.

The most visible case could be default route. So we could provide fix to mask default
route as quick fix. Then we could discuss more general case for users to filter any
IPv4/v6 routes with network-attach-definition or some other way, I guess.

**Comment by dougbtv** [comment]
This is covered in the latest version of the NPWG spec with default route selection.
