### ISSUE TITLE
IPRequest can not work

### ISSUE THREAD

**Issue by zmz** [intel/multus-cni#180]

**Comment by zmz** [comment]
use macvlan cni, IPRequest can not work, but I know CNI  support static ip request ,  for example CNI_ARGS="IP=203.0.113.121"

**Comment by s1061123** [comment]
Thank you for your feedback. 
Could you please let me know following information to make the issue clear?

- multus version (is that latest or you use older version than v3.1?)
- CNI config file (in /etc/cni/net.d/)
- NetworkAttachment info
- Pod yaml info (with annotation)

**Comment by s1061123** [comment]
Thank you for your info!

For now, Multus does not pass "IPRequest" to IPAM plugin of NetworkAttachment (i.e. 'k8s.../networks') and we already have a plan to implement it in near future.

**Comment by micw** [comment]
I'm also interested in this. Currently I workaround this by having multiple configs with "static" ipam type.

**Comment by dougbtv** [comment]
This is covered by recent changes regarding CNI ARGS
