### ISSUE TITLE
Unique address for host-local ipam plugin & Multus when NPWG supported

### ISSUE THREAD

**Issue by flyinghawkren** [intel/multus-cni#185]
Hi, @s1061123. I noticed this issue refered as following link had been closed:
https://github.com/intel/multus-cni/issues/52

I think that's OK when multus not support NPWG. We can manually configure the conf with non-overlapped IP subnet range for every node in cluster. So we can finally get unique IP address for pods across the whole cluster.
But when multus support NPWG, the network-attachment-definition for IPVLAN become a global configuration in cluster. When use host-local as the ipam plugin, every node get same IP subnet range now. So it may allocate duplicated IP addr.
Is there any sugguestion for this case? And will multus support network-attachment-definition work with node's local conf together?
Thanks!

**Comment by flyinghawkren** [comment]
FYI, the code in `cniConfigFromNetworkResource` indicate that multus can only support one configuration method. And I have not found a open source global IPAM plugin that can work with ipvlan since ipvlan can't work with dhcp.

**Comment by s1061123** [comment]
Hi,

This issue seems not to be related to multus-cni and seems to be related to IPAM(incl DHCP) and IPVLAN plugin issue because this issue will be happen without multus (and network-attachment-definition) as following:

- setup kubernetes cluster
- ipvlan as interface CNI
- host-local as IPAM CNI

Hence I suppose that the issue should go to [CNI community](https://github.com/containernetworking/plugins).
Could you please file it to above?

**Comment by flyinghawkren** [comment]
Hi, 
When multus work in CRD config mode with NetworkAttachmentDefinition，the IPAM config become global configuration. Are there any global ipam CNI plugin to work with multus + ipvlan?
Thank you very much!

**Comment by s1061123** [comment]
How about to use CRD with files:
(pointing document is in PR and hope it will be merged soon)

https://github.com/s1061123/multus-cni/blob/dev/update-readme/doc/how-to-use.md#networkattachmentdefinition-with-cni-config-file

**Comment by hshtel** [comment]
@s1061123 Hey dear, 
I've tried to set CRD with files but failed when creating the pod with this error:
```
Events:
  Type     Reason                  Age               From                 Message
  ----     ------                  ----              ----                 -------
  Normal   Scheduled               21s               default-scheduler    Successfully assigned default/kamailio-ci to k8-worker2
  Warning  FailedCreatePodSandBox  13s               kubelet, k8-worker2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "58161c41e2bbdb2f16b08319ec085aa696893229308af4193465b20c806c875c" network for pod "kamailio-ci": NetworkPlugin cni failed to set up pod "kamailio-ci_default" network: Multus: Err in loading K8s Delegates k8s args: Multus: Err in getting k8s network from pod: GetPodNetwork: failed getting the delegate: cniConfigFromNetworkResource: err in getCNIConfigFromFile: No networks found in /etc/cni/multus/net.d
  Warning  FailedCreatePodSandBox  3s                kubelet, k8-worker2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "994eea03b0690c9bde039dd0c2499e4e960a16a23c6fe1e1e2df92aed63acd5a" network for pod "kamailio-ci": NetworkPlugin cni failed to set up pod "kamailio-ci_default" network: Multus: Err in loading K8s Delegates k8s args: Multus: Err in getting k8s network from pod: GetPodNetwork: failed getting the delegate: cniConfigFromNetworkResource: err in getCNIConfigFromFile: No networks found in /etc/cni/multus/net.d
  Normal   SandboxChanged          2s (x2 over 12s)  kubelet, k8-worker2  Pod sandbox changed, it will be killed and re-created.
```

I've tried to set macvlan-conf file on each worker node with different ranges so the pod can get IP from the range assigned to its node:

I've created below CRD:
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
```
I have two worker and in each one I 've added macvlan-conf in "/etc/cni/multus/net.d" path:
worker-1
```
{
        "cniVersion": "0.3.0",
        "type": "macvlan",
        "name": "macvlan-conf",
        "master": "ens160",
        "mode": "bridge",
        "ipam": {
                "type": "host-local",
                "subnet": "172.1.1.0/24",
                "rangeStart": "172.1.1.200",
                "rangeEnd": "172.1.1.210",
                "routes": [{
                        "dst": "0.0.0.0/0"
                }],
                "gateway": "172.1.1.27"
        }
}
```
worker-2
```
{
        "cniVersion": "0.3.0",
        "type": "macvlan",
        "name": "macvlan-conf",
        "master": "ens160",
        "mode": "bridge",
        "ipam": {
                "type": "host-local",
                "subnet": "172.1.1.0/24",
                "rangeStart": "172.1.1.211",
                "rangeEnd": "172.1.1.220",
                "routes": [{
                        "dst": "0.0.0.0/0"
                }],
                "gateway": "172.1.1.27"
        }
}
```
I didn't create any file on the master node.

please is there anything wrong in these step or I missed something.
