### ISSUE TITLE
Improved image tagging in Travis CI

### ISSUE THREAD

**Issue by dougbtv** [intel/multus-cni#187]
Considerations:

* Build a `:latest-master` with each pull request in master to provide a "tip of master" tagged Docker image
* Update the quick-start YAML to use a special tag (that's not `:latest`) to show that you're using the latest version tag, something like `:latest-stable` or `:latest-release`

Up for discussion:

* Should the `release-3` branch reflect a different tag for that branch?

**Comment by dougbtv** [comment]
regarding the `release-3`, I think it would be confusing to maintain to have the yaml daemonsets vary between each branch. I think it should be assumed that the yaml daemonsets are specifically for the quick-start methodology. And that variants thereof should be in documentation (e.g. some `./docs/` information showing that "here's how you use the `release-x` branches and show information on how to compile and build images)

**Comment by s1061123** [comment]
I also checked flannel and flannel yaml file explicitly added container tag name in yaml file, e.g. v0.10.0-amd64 for master. (well, I imagined that they use 'latest'...)
https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml#L106

**Comment by dougbtv** [comment]
Thanks for finding an example to work from. Would like to get input here on which method people like here, and then we can move forward on how to tag / manage the yaml.
