### ISSUE TITLE
NetworkAttachmentDefinition client

### ISSUE THREAD

**Issue by phoracek** [intel/multus-cni#189]
Hello Multus,

we use NetworkAttachmentDefinitions in multiple projects now, all of them are using the same mechanism to obtain definitions as multus does - raw client requests. 

I created a Go client for NetworkAttachmentDefinition resources using Kubernetes' code-generator https://github.com/phoracek/network-attachment-definition-client.

Would you consider consuming it and more importantly, would it be possible to host it under Intel's GitHub organization? To make it available for everyone. First I wanted to asks you to host it under multus-cni, but there would be multiple branches generated for each Kubernetes release.

I see that it is not that urgent for multus-cni itself, since it only reads those definitions. However, for other consumers, simple updating or list and watch could be important.

Thanks.

**Comment by rkamudhan** [comment]
@phoracek Awesome!! It won't be issue to hosting it in Multus-cni, I believe it will be ok for @dougbtv @s1061123 and @dcbw to host it here.

**Comment by phoracek** [comment]
@rkamudhan sounds good, but the client is generated with certain client-go version as a dependency. Would not that be a problem? Let's say multus-cni hosts the client generated against 1.12, user wants to use it along exising 1.11 code, tries to build source codes, *random vendoring issue appears*.

**Comment by dougbtv** [comment]
Very cool! Maybe we can host it as part of the new NPWG github org? 

https://github.com/K8sNetworkPlumbingWG

**Comment by phoracek** [comment]
@dougbtv that sounds like a good neutral ground to do that! How should I proceed?

**Comment by dougbtv** [comment]
@dcbw -- could you invite @phoracek as a member to the K8sNetworkPlumbingWG org and we can have him create a new repo there?

**Comment by dcbw** [comment]
I added https://github.com/K8sNetworkPlumbingWG/network-attachment-definition-client and will take a PR to update it

**Comment by phoracek** [comment]
Thanks a lot.
