### ISSUE TITLE
Deleting interface should be continued instead of returning after one failure

### ISSUE THREAD

**Issue by ahalim-intel** [intel/multus-cni#20]
Instead of returning the error encountered on deleting one  interface inside the loop can we concatenate the errors and continue with deletion of rest of the interfaces and return the error outside of the loop? 
That way, if there was any error on deletion on any interface we are still catching it and able to return it at the end of the function.

**Comment by rkamudhan** [comment]
+1 Agreed 👍

**Comment by s1061123** [comment]
@ahalim-intel @rkamudhan This issue seems to be fixed current. So let me close the issue.
Please re-open if something is missing.
