### ISSUE TITLE
Portmap is not working with default installation

### ISSUE THREAD

**Issue by micw** [intel/multus-cni#208]
**What happend**:
I have installed multus with the both daemonsets from images/*.yaml (master). I created a simple deployment (Nginx hello world) and added "hostPort:8888" to the container.
The port does not get exposed to the host. No firewall rule for this port is created at all.

**What you expected to happen**:
A NAT firewall rule that exposes the container's port to the host.

**How to reproduce it (as minimally and precisely as possible)**:
- Install multus-cni together with the flannel-daemonset from images/*.yaml
- Create a deployment/pod with a hostPort

**Anything else we need to know?**:
According to the changelog of Version 3.1, portmap support should be in place.
It's important to have this work because otherwise there's no way to use an ingress like nginx or traefik.

**Environment**:

- Multus version 3.1
  nfvpe/multus latest d9e7bffad290
  (tried also snapshot)
- Kubernetes version (use `kubectl version`):
  v1.12.3
- Primary CNI for Kubernetes cluster:
  flannel
- OS (e.g. from /etc/os-release):
- File of '/etc/cni/net.d/'
  /etc/cni/net.d/multus.d/multus.kubeconfig
  /etc/cni/net.d/70-multus.conf
  (fresh installed by multus, no manual changes)

- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
  Error: unknown command "net-attach-def" for "kubectl"

**Comment by micw** [comment]
I finally found a solution with the deamonset installation from images/*.yaml.
I build a new docker image that contains a build from latest master and the following configuration:
```
{
  "name": "multus-cni-network",
  "type": "multus",
  "logLevel": "debug",
  "capabilities": {
    "portMappings": true
  },
  "delegates": [
    {
      "cniVersion": "0.3.1",
      "name": "default-cni-network",
      "plugins": [
        {
          "type": "flannel",
          "name": "flannel.1",
            "delegate": {
              "isDefaultGateway": true,
              "hairpinMode": true
            }
          },
          {
            "type": "portmap",
            "capabilities": {
              "portMappings": true
            }
          }
      ]
    }
  ],
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
}
```

The multus-cni binary requires #132 to have this work.

The flannel-daemonset.yaml also contains a cni config with delegate - this is very missleading since that config is not used at all.

**Comment by dougbtv** [comment]
@micw -- thanks for the detailed explanation and also for the PR! ...I think it's quite reasonable to add the portMap here while setting up the default network. I think it's a fair capability to have in here by default. I've been reviewing the PR and it looks good, I'll approve it and I'll bring it up for review during the next maintainers meeting, too.

Also -- regarding your note here:

> The flannel-daemonset.yaml also contains a cni config with delegate - this is very missleading since that config is not used at all.

I think there needs to be better documentation here, or notes in the YAML -- sorry this caused you any pain here with it being misleading. Mostly, I wanted that there as a convenient place to override the configuration that's packed into the Docker image. I think I'm missing some explanation there, thanks for pointing it out!!

**Comment by s1061123** [comment]
#217 fixes the issue, so close it.
