### ISSUE TITLE
Provide a way to add config in daemonset-install yaml

### ISSUE THREAD

**Issue by s1061123** [intel/multus-cni#218]
**What would you like to be added**:
This comes from @micw. 
Currently [images/flannel-daemonset.yml](https://github.com/intel/multus-cni/blob/master/images/flannel-daemonset.yml) uses [images/70-multus.conf](https://github.com/intel/multus-cni/blob/master/images/70-multus.conf) implicitly and no way to provide config in configmap.

**Why is this needed**:
Configmap configuration also provides a way to configure multus CNI configuration, hence it is better way.

**Comment by dougbtv** [comment]
I have existing examples here, too: https://github.com/dougbtv/openshift-ansible/blob/multus-developer-preview/playbooks/openshift-multinetwork/files/multus-daemonset.yml#L135-L136

I like the idea of making this more flexible!! Thanks Tomo & Michael.

**Comment by micw** [comment]
This is great. Personally I prefer the ENV way over the args way because it makes it more easy to add one ore more (e.g. via helm chart)

**Comment by s1061123** [comment]
#279 fixed it
