### ISSUE TITLE
NetworkPlugin cni failed to set up pod "samplepod_default" network

### ISSUE THREAD

**Issue by tcnieh** [intel/multus-cni#229]
Hello All,
I followed the quickstart guide [https://goo.gl/2EFoLN](url) and have been tried a very long time on creating a pod that attaches an additional network interface. The following shows a list of the current pods in all namespaces:

> ```
> root@mn-virtual-machine:~# kubectl get pod --all-namespaces
> NAMESPACE     NAME                                         READY   STATUS              RESTARTS   AGE
> default       samplepod                                    0/1     ContainerCreating   0          103m
> kube-system   coredns-86c58d9df4-jqhl4                     1/1     Running             0          165m
> kube-system   coredns-86c58d9df4-vwsxc                     1/1     Running             0          165m
> kube-system   etcd-mn-virtual-machine                      1/1     Running             0          167m
> kube-system   kube-apiserver-mn-virtual-machine            1/1     Running             0          167m
> kube-system   kube-controller-manager-mn-virtual-machine   1/1     Running             0          167m
> kube-system   kube-flannel-ds-amd64-984mh                  1/1     Running             0          166m
> kube-system   kube-flannel-ds-amd64-mv244                  1/1     Running             0          165m
> kube-system   kube-flannel-ds-amd64-wf456                  1/1     Running             0          165m
> kube-system   kube-multus-ds-amd64-7djcm                   1/1     Running             0          165m
> kube-system   kube-multus-ds-amd64-8ntn2                   1/1     Running             0          166m
> kube-system   kube-multus-ds-amd64-d4qzd                   1/1     Running             0          165m
> kube-system   kube-proxy-jd9fx                             1/1     Running             0          168m
> kube-system   kube-proxy-kxjbh                             1/1     Running             0          165m
> kube-system   kube-proxy-l7n4d                             1/1     Running             0          165m
> kube-system   kube-scheduler-mn-virtual-machine            1/1     Running             0          167m

It seems fine that I got a cluster with one master and three work nodes.  When I try to create a samplepod as described in quickstart guide, I got failed message as below:
 
```Warning  FailedCreatePodSandBox  10s (x4 over 15s)   kubelet, wn1-virtual-machine  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "b81b68757b77f4bff32daeffb40376e8747b7082fff2b44ec7af16f9ded76dcb" network for pod "samplepod": NetworkPlugin cni failed to set up pod "samplepod_default" network: Multus: Err in tearing down failed plugins: Multus: error in invoke Delegate add - "macvlan": failed to lookup master "eth0": Link not found```

I studied the issues list and noticed [https://github.com/intel/multus-cni/issues/101#issuecomment-408095789](url) describe a debug way.

> ```
> root@mn-virtual-machine:~# kubectl get crd
> NAME                                             CREATED AT
> network-attachment-definitions.k8s.cni.cncf.io   2018-12-27T03:01:06Z

> ```
> root@mn-virtual-machine:~# kubectl describe crd network-attachment-definition
> Name:         network-attachment-definitions.k8s.cni.cncf.io
> Namespace:
> Labels:       <none>
> Annotations:  kubectl.kubernetes.io/last-applied-configuration:
>                 {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"name":"network-attachment-def...
> API Version:  apiextensions.k8s.io/v1beta1
> Kind:         CustomResourceDefinition
> Metadata:
>   Creation Timestamp:  2018-12-27T03:01:06Z
>   Generation:          1
>   Resource Version:    661
>   Self Link:           /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/network-attachment-definitions.k8s.cni.cncf.io
>   UID:                 a72d9007-0983-11e9-8faf-005056861a56
> Spec:
>   Conversion:
>     Strategy:  None
>   Group:       k8s.cni.cncf.io
>   Names:
>     Kind:       NetworkAttachmentDefinition
>     List Kind:  NetworkAttachmentDefinitionList
>     Plural:     network-attachment-definitions
>     Short Names:
>       net-attach-def
>     Singular:  network-attachment-definition
>   Scope:       Namespaced
>   Validation:
>     Open APIV 3 Schema:
>       Properties:
>         Spec:
>           Properties:
>             Config:
>               Type:  string
>   Version:           v1
>   Versions:
>     Name:     v1
>     Served:   true
>     Storage:  true
> Status:
>   Accepted Names:
>     Kind:       NetworkAttachmentDefinition
>     List Kind:  NetworkAttachmentDefinitionList
>     Plural:     network-attachment-definitions
>     Short Names:
>       net-attach-def
>     Singular:  network-attachment-definition
>   Conditions:
>     Last Transition Time:  2018-12-27T03:01:06Z
>     Message:               no conflicts found
>     Reason:                NoConflicts
>     Status:                True
>     Type:                  NamesAccepted
>     Last Transition Time:  <nil>
>     Message:               the initial names have been accepted
>     Reason:                InitialNamesAccepted
>     Status:                True
>     Type:                  Established
>   Stored Versions:
>     v1
> Events:  <none>

> ```
>root@mn-virtual-machine:~# kubectl get network-attachment-definition
> NAME           AGE
> macvlan-conf   2h

> ```
> root@mn-virtual-machine:~# kubectl describe network-attachment-definition macvlan-conf
> Name:         macvlan-conf
> Namespace:    default
> Labels:       <none>
> Annotations:  kubectl.kubernetes.io/last-applied-configuration:
>                 {"apiVersion":"k8s.cni.cncf.io/v1","kind":"NetworkAttachmentDefinition","metadata":{"annotations":{},"name":"macvlan-conf","namespace":"de...
> API Version:  k8s.cni.cncf.io/v1
> Kind:         NetworkAttachmentDefinition
> Metadata:
>   Creation Timestamp:  2018-12-27T03:38:26Z
>   Generation:          1
>   Resource Version:    4058
>   Self Link:           /apis/k8s.cni.cncf.io/v1/namespaces/default/network-attachment-definitions/macvlan-conf
>   UID:                 dea7726a-0988-11e9-8faf-005056861a56
> Spec:
>   Config:  { "cniVersion": "0.3.0", "type": "macvlan", "master": "eth0", "mode": "bridge", "ipam": { "type": "host-local", "subnet": "192.168.1.0/24", "rangeStart": "192.168.1.200", "rangeEnd": "192.168.1.216", "routes": [ { "dst": "0.0.0.0/0" } ], "gateway": "192.168.1.1" } }
> Events:    <none>

And when I create a pod without `annotations:    k8s.v1.cni.cncf.io/networks: macvlan-conf`, it works fine. Could anyone give me some hint or way to debug please, I'm bit lost here.

**Comment by SchSeba** [comment]
@tcnieh This problem is in your `macvlan-conf` you vm doesn't have `eth0` the master configuration needs to point to an interface on your vm like `ens160`.

You can try to do something like this
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec: 
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens160",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.22.100.0/24",
        "rangeStart": "10.22.100.36.200",
        "rangeEnd": "10.22.100.36.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "<gateway>"
      }
    }'
```

please check the IPAM configuration to avoid collisions and also update the gateway with the right gateway on your network.

Last think is that you have 3 servers so IPAM `host-local` can be a problem for you any service will assign the same ips for pods.

**Comment by tcnieh** [comment]
@SchSeba Thanks for your suggestion, I now can create a pod with extra network interface.
Here I have a furthermore question, that is, I could not reach this pod directly from external IP. Here is ```ip a``` and ```route -n``` in the pod:

```
[root@multuspod /]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if69807: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP
    link/ether 0a:58:0a:f4:01:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.1.3/24 scope global eth0
       valid_lft forever preferred_lft forever
4: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 5a:eb:32:90:1f:f5 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.1.200/24 scope global net1
       valid_lft forever preferred_lft forever
[root@multuspod /]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.244.1.1      0.0.0.0         UG    0      0        0 eth0
10.244.0.0      10.244.1.1      255.255.0.0     UG    0      0        0 eth0
10.244.1.0      0.0.0.0         255.255.255.0   U     0      0        0 eth0
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 net1
```
It seems that 192.168.1.x and 10.244.1.x packets are sent via net1 and eth0, respectively. In pod, I try to ping another external IP 192.168.1.210 and get no response.
Hence I guess that something in master node is causing problems. Here is ```route -n``` from master node:
```
root@mn-virtual-machine:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.22.100.254   0.0.0.0         UG    100    0        0 ens160
10.22.100.0     0.0.0.0         255.255.255.0   U     100    0        0 ens160
10.244.0.0      0.0.0.0         255.255.255.0   U     0      0        0 cni0
10.244.1.0      10.244.1.0      255.255.255.0   UG    0      0        0 flannel.1
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
```
Is the problem occurred on fourth routing rule? 
I study the closed issue https://github.com/intel/multus-cni/issues/145 , still no clues.
Or I should modify the coreDNS as described in  https://github.com/intel/multus-cni/issues/23#issuecomment-336718504  ? Perhaps add an "stubDomains"??

**Comment by SchSeba** [comment]
@tcnieh
you connect yourself using the macvlan to the interface `ens160` that is in the subnet of `10.22.100.0/24` but your pod got `192.168.1.200` I am not sure if this can work.

**Comment by tcnieh** [comment]
Thanks, I noticed that too. Hence I created another custom resource:
```
root@mn-virtual-machine:~/multus-cni/images# cat networkattachment_1.yml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-1
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens160",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.22.100.0/24",
        "rangeStart": "10.22.100.237",
        "rangeEnd": "10.22.100.240",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.22.100.254"
      }
    }'

root@mn-virtual-machine:~/multus-cni/images# kubectl exec -it multuspod-3 -- route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.244.1.1      0.0.0.0         UG    0      0        0 eth0
10.22.100.0     0.0.0.0         255.255.255.0   U     0      0        0 net1
10.244.0.0      10.244.1.1      255.255.0.0     UG    0      0        0 eth0
10.244.1.0      0.0.0.0         255.255.255.0   U     0      0        0 eth0

root@mn-virtual-machine:~/multus-cni/images# kubectl exec -it multuspod-3 -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if69809: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP
    link/ether 0a:58:0a:f4:01:05 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.1.5/24 scope global eth0
       valid_lft forever preferred_lft forever
4: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether ca:6d:fd:0c:97:db brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.22.100.237/24 scope global net1
       valid_lft forever preferred_lft forever
```
As you can see, that I had a net1 connected within bridge mode via ens160, still unreachable:
```
root@mn-virtual-machine:~/multus-cni/images# kubectl exec -it multuspod-3 -- ping 10.22.100.36
PING 10.22.100.36 (10.22.100.36) 56(84) bytes of data.
From 10.22.100.237 icmp_seq=1 Destination Host Unreachable
From 10.22.100.237 icmp_seq=2 Destination Host Unreachable
From 10.22.100.237 icmp_seq=3 Destination Host Unreachable
From 10.22.100.237 icmp_seq=4 Destination Host Unreachable
^C
--- 10.22.100.36 ping statistics ---
5 packets transmitted, 0 received, +4 errors, 100% packet loss, time 4044ms
pipe 4
command terminated with exit code 1
```
This is really bothering me Orz

**Comment by SchSeba** [comment]
Can you please run the ping test and in a second terminal run `tcpdump -vvvnnpi ens160 icmp`
If you don't see any packets please run `tcpdump -vvvnnpi ens160 arp` 
post both outputs please

**Comment by tcnieh** [comment]
Yes yes, I run ping test and tcpdump before, here is the icmp result:

![1](https://user-images.githubusercontent.com/32285674/50959569-3bdb7e80-14fe-11e9-9529-4a0700613cc6.PNG)

Here is the arp result:
![2](https://user-images.githubusercontent.com/32285674/50959712-878e2800-14fe-11e9-8982-e7b8f63b7574.PNG)

These IPs 100.67/78/69 are other utilization, nothing to do with the tests.


Here is another test between multus_pod1 (192.168.1.200) and multus_pod2 (192.168.1.201), which both `net1@if2` are bridged via ens160:
![3](https://user-images.githubusercontent.com/32285674/50960404-4860d680-1500-11e9-93cd-6320df689478.PNG)
I am so curious where the packet go through? XD

**Comment by SchSeba** [comment]
All the tests are using a different subnet again can you please try the tcpdump with the right subnet (10.22.100.0/24)

> I am so curious where the packet go through? XD

The  packets go through a bridge in the interface (you select type bridge for the macvlan)  you can't see that bridge but is there.

**Comment by s1061123** [comment]
Hi,

If your pod is sitting on same node of 10.22.100.36, this ping should NOT work as expected due to macvlan limitation.

```
# NOTE: the containers can NOT ping the underlying host interfaces as
# they are intentionally filtered by Linux for additional isolation.
```
From https://docs.docker.com/v17.09/engine/userguide/networking/get-started-macvlan/#macvlan-bridge-mode-example-usage

**Comment by tcnieh** [comment]
Thanks,  I did another test with right subnet (10.22.100.0/24), still got the same result:
![4](https://user-images.githubusercontent.com/32285674/51010342-e0a59c80-158e-11e9-81bf-12ae0024bce7.PNG)
![5](https://user-images.githubusercontent.com/32285674/51010346-e4392380-158e-11e9-880b-e6f8ee437a8b.PNG)

Hence, it seems like what Mr.Hayashi said, the pod can not ping as expected due to its limitation. 
Therefore, other than utilizing port forwarding, I am wondering if there is methods or CNIs that I could ssh to the pod directly from external IPs (same subnet).

**Comment by xdk-rachel** [comment]
> Thanks, I did another test with right subnet (10.22.100.0/24), still got the same result:
> ![6](https://user-images.githubusercontent.com/32285674/51012850-519e8180-159a-11e9-87c3-3d25b07a09d0.PNG)
> ![7](https://user-images.githubusercontent.com/32285674/51012851-55320880-159a-11e9-84a7-d9f9e1ebf405.PNG)
> 
> Hence, it seems like what Mr.Hayashi said, the pod can not ping as expected due to its limitation.
> Therefore, other than utilizing port forwarding, I am wondering if there is methods or CNIs that I could ssh to the pod directly from external IPs (same subnet).

Can you ping the other ip address which is in the range  of 10.22.100.xxx?

**Comment by tcnieh** [comment]
![image](https://user-images.githubusercontent.com/32285674/51223021-18d82100-197b-11e9-8af0-7e4aa01ef1d1.png)
Yes, I got response If I ping other pod with same subnet, in this case, pod-4 (10.22.00.238) ping pod-3 (10.22.00.237). 
My testbed could be describe as followed picture:
![k8s](https://user-images.githubusercontent.com/32285674/51223733-0ad7cf80-197e-11e9-950c-a02c21594285.jpg)
And what I would like to is pinging a IP with same subnet 10.22.100.242 from pod-4 with 10.22.100.238. I guess this is the limitation @s1061123 mentioned.
