### ISSUE TITLE
How to check the version of the binary

### ISSUE THREAD

**Issue by mhristache** [intel/multus-cni#235]
Hi

I am trying to understand what version of Multus I get when I use https://raw.githubusercontent.com/intel/multus-cni/master/images/multus-daemonset.yml to install it. The MD5 sum for the x86_64 binary I get is `1d218378557f393a5872d809e5a82edb` which does not match the MD5 for the v3.0 or v3.1 amd64 binaries.

Can you help out? Is there a way to check the version of the binary? I tried `strings` but could not find anything useful.

Thanks

//Max

**Comment by dougbtv** [comment]
Also -- for what it's worth, the `nfvpe/multus:latest` is the latest tagged release. There's also docker image tags for each tagged release. There's also the `nfvpe/multus:snapshot` which is latest build @ master HEAD.

**Comment by mhristache** [comment]
Thanks @dougbtv

**Comment by rgaduput** [comment]
If needed to be checked on already running k8s cluster below will help, (make sure to modify the pod name)
```
[root@k8s-master01 ~]# kubectl -n kube-system exec -it kube-multus-ds-fzwk7 -c kube-multus -- /usr/src/multus-cni/bin/multus --version
multus-cni version:v3.9, commit:ca8c9c579100648b88774cb9f79223eb213373a2, date:2022-06-23T14:08:12+00:00
```
