### ISSUE TITLE
Reboot server, cmddel not success, pod ip will not release. 

### ISSUE THREAD

**Issue by hangzhouwanjun** [intel/multus-cni#239]
**What happend**:
If reboot server,  i find the /var/lib/cni/networks/mynet/10.10.1.13 is not deleted, 10.10.1.13 is the pod ip.

**What you expected to happen**:
The pod ip will be retrieve.

**How to reproduce it (as minimally and precisely as possible)**:
Reboot server.

**Anything else we need to know?**:
I think this is a bug, because in multus.go, the cmdDel has bad code,such as:
`if args.Netns == "" {
		return nil
	}
	netns, err := ns.GetNS(args.Netns)
	if err != nil {
		//  if NetNs is passed down by the Cloud Orchestration Engine, or if it called multiple times
		// so don't return an error if the device is already removed.
		// https://github.com/kubernetes/kubernetes/issues/43014#issuecomment-287164444
		_, ok := err.(ns.NSPathNotExistErr)
		if ok {
			return nil
		}
		return fmt.Errorf("failed to open netns %q: %v", netns, err)
	}`
If i reboot server, the ns is not exist, that will return NSPathNotExistErr, delPlugins is not exec. The pod ip will not release. 

**Environment**:

- Multus version : v3.1 
- Kubernetes version (use `kubectl version`): v1.11.5
- Primary CNI for Kubernetes cluster: calico
- OS (e.g. from /etc/os-release): centos 7.3

**Comment by rkamudhan** [comment]
@hangzhouwanjun Thanks for finding the issue. I will create a PR for this fix. Thank for helping us to find the bug.

**Comment by s1061123** [comment]
#326 fixed issue so close it.
