### ISSUE TITLE
Can't add second interface to the pod with multus

### ISSUE THREAD

**Issue by hshtel** [intel/multus-cni#240]
I am trying to add multiple interfaces to a POD using multus but with no luck, I have followed the instruction in the Quickstart Guide:

-  use daemonset to install multus with flannel.
-  use macvlan-conf in the example directory to set the NetworkAttachmentDefinition as below:

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens192",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.205.28.0/24",
        "rangeStart": "10.205.28.14.200",
        "rangeEnd": "10.205.28.14.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.205.28.1"
      }
    }'
```
-  deploy sample-pod to use macvlan as seconf interface with flannel:
```
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
```

- the output of "kubectl exec -it samplepod -- ip a":
```
root@master:~/multus-cni/examples# kubectl exec -it samplepod -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if38: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP
    link/ether 0a:58:0a:f4:01:19 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.1.25/24 scope global eth0
       valid_lft forever preferred_lft forever
```

- ip a output:
```
root@master:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0c:29:11:ec:32 brd ff:ff:ff:ff:ff:ff
    inet 172.1.1.14/24 brd 172.1.1.255 scope global ens160
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fe11:ec32/64 scope link
       valid_lft forever preferred_lft forever
3: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0c:29:11:ec:3c brd ff:ff:ff:ff:ff:ff
    inet 10.205.28.14/24 brd 10.205.28.255 scope global ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fe11:ec3c/64 scope link
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:af:4c:35:8e brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
24: vethc798d74f@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether fa:b1:d4:f3:cf:1d brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::f8b1:d4ff:fef3:cf1d/64 scope link
       valid_lft forever preferred_lft forever
1242: veth4907c78e@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default
    link/ether fe:32:46:e9:60:80 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::fc32:46ff:fee9:6080/64 scope link
       valid_lft forever preferred_lft forever
495: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether 36:5c:54:7c:8f:e8 brd ff:ff:ff:ff:ff:ff
    inet 10.244.0.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::345c:54ff:fe7c:8fe8/64 scope link
       valid_lft forever preferred_lft forever
496: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether 0a:58:0a:f4:00:01 brd ff:ff:ff:ff:ff:ff
    inet 10.244.0.1/24 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::60e1:3bff:fe1e:3cf1/64 scope link
       valid_lft forever preferred_lft forever
```
- I think the configuration files in  /etc/cni/net.d are another way to use multus, please correct me if I am wrong ? and below is the multus configurtion file:
```
root@master:/etc/cni/net.d# ls
10-flannel.conflist  10-multus-with-flannel.conf  70-multus.conf  multus.d
root@master:/etc/cni/net.d# vi 70-multus.conf
{
  "name": "multus-cni-network",
  "type": "multus",
  "delegates": [
    {
      "type": "flannel",
      "name": "flannel.1",
      "delegate": {
        "isDefaultGateway": true,
        "hairpinMode": true
      }
    }
  ],
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
```
please advise if there are other configuration to add or modify to set multiple interfaces.

**Comment by dougbtv** [comment]
Ahhh -- you know what -- I think you might have installed Flannel first. So you have an alphabetically first config called `10-flannel.conflist` and Kubernetes reads that first, and it never executes Multus.

What you can do is `cd /etc/cni/net.d; mkdir old-configs; mv 10-* old-configs`

That'll make so that `70-multus.conf` is the first in alphabetical order in that dir, and then it should execute Multus.

The daemonset style installation doesn't know if you have, and it creates its own configuration, so since that Flannel one is alphabetically first, Multus hasn't gotten executed.

Looks like it's possibly a docs issue on our side -- we should note this in the quickstart guide.

**Comment by hshtel** [comment]
Thanks @dougbtv for your response, I have tried your suggestion but it didn't work. also I tried another plugin (weave net) but with no luck.

below is my configuration now:
root@master:~/multus-cni/examples# vi weave-conf-test
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: weave-conf
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "weave-net",
    "delegate": {
      "isDefaultGateway": true
    }
  }'
```
root@master:~/multus-cni/examples# vi sample-pod.yml
```
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: weave-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
```

```
root@master:/etc/cni/net.d# ls
00-multus.conf  10-weave.conflist  70-multus.conf  multus.d  old-configs
```
```
root@master:/etc/cni/net.d# vi 00-multus.conf
{
  "name": "multus-cni-network",
  "type": "multus",
  "delegates": [
    {
      "type": "flannel",
      "name": "flannel.1",
      "delegate": {
        "isDefaultGateway": true,
        "hairpinMode": true
      }
    }
  ],
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
```

the sample-pod is working normally but with no second interface
```
root@master:~/multus-cni/examples# kubectl exec -it samplepod -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if30: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP
    link/ether 0a:58:0a:f4:01:2d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.1.45/24 scope global eth0
       valid_lft forever preferred_lft forever
```

**Comment by PatrickKutch** [comment]
I am having the same exact issue.  Using 1.13 via kubeadm install.  Tried a fresh install where right after init I   did cat ./images/{multus-daemonset.yml,flannel-daemonset.yml} | kubectl apply -f -.  All works fine, but when I create pods via the rest of the example, additional interfaces not created.

**Comment by rkamudhan** [comment]
@PatrickKutch Can you give me the example pod you used ?

**Comment by rkamudhan** [comment]
@PatrickKutch @hshtel can you do `ls -l /etc/cni/net.d/`

**Comment by PatrickKutch** [comment]
I figured it out - the example uses 'eth0' in macvlan-conf.  Should be whatever you have on your specific system - mine is ens3.  Might want to update the doc to clearly indicate this for newbie's such as myself :-)

**Comment by dougbtv** [comment]
@PatrickKutch -- thanks for reporting the fix and also the documentation suggestion! Agreed. I've got a fix together in #248, give it a thumbs up if you agree (or have another suggestion, please feel free to comment -- always looking for eyeballs on the docs from fresh eyes) and we'll merge it in. 

Thanks again!

**Comment by hshtel** [comment]
@dougbtv I had to uninstall and reset configuration related to other plugins ( flannel & weavenet) then I was able to redeploy multus and flannel (multus first) and it is working now. I will close this issue
Thanks again.

**Comment by Scavallarin** [comment]
Hi, I followed all the steps, but the result is that now "get pods" is telling me:  that the connection to <host>:6443 was refused - did you specify the right host or port? 
It looks like k8s is still looking for 10-wave.conflist, and it has even recreated the file that i moved into a new directory called "old-configs", just to live only the 70-multus.conf inside net.d. How can i reset the configuration related to other plugins? I think that without a reset like @hshtel said there is no way to make it works, Thanks!
