### ISSUE TITLE
Adding config for namespace for clusterNetwork/defaultNetworks

### ISSUE THREAD

**Issue by s1061123** [intel/multus-cni#252]
**What would you like to be added**:
Adding new config parameter that specifies namespace for clusterNetwork/defaultNetworks (currently fixed to 'kube-system'
**Why is this needed**:
Allow user to change the namespace

**Comment by dougbtv** [comment]
@s1061123 -- I think this one is closed? We have the PR which references it merged @ https://github.com/intel/multus-cni/pull/254

**Comment by s1061123** [comment]
@dougbtv Yes, so let me close it.
