### ISSUE TITLE
nfvpe/multus:latest used in multus-daemonset.yml fails with SR-IOV lugin

### ISSUE THREAD

**Issue by PatrickKutch** [intel/multus-cni#257]
Following the instructions cat ./images/{multus-daemonset.yml,flannel-daemonset.yml} | kubectl apply -f - does what is expected and puts the multus plugin on all the systems. 

However that binary plugin is slightly out of date and doesn't seem to work with the SR-IOV plugin.

If I build the multus plugin from source and manually copy it over to each system, SR-IOV will work.

I believe the nfvpe/multus needs to be updated.

**Comment by ahalim-intel** [comment]
@rkamudhan @s1061123 
The nfvpe/multus:latest was built last time 6 months ago! Thus it does not support device information fetching. Can we please at least have the _**:latest**_ tagged image build regularly?

As per the main README.md we are suggesting users to deploy using a pre-built image which is not up to date.

**Comment by rkamudhan** [comment]
@PatrickKutch & @ahalim-intel The image point to the v3.0 version. Please use `[nfvpe/multus:snapshot](https://hub.docker.com/r/nfvpe/multus/tags) in ` https://github.com/intel/multus-cni/blob/master/images/multus-daemonset.yml

**Comment by dougbtv** [comment]
Thanks Kural -- I think this does bring up a point that sometimes people expect the `:latest` tag to be, well, tip of master. Maybe this should change, however, I'd also say in tandem, that for community friendliness that the quick-start daemonset-style installation refer to a tagged release, potentially.

**Comment by rkamudhan** [comment]
@dougbtv I think it time for the next latest release. We should discuss it in our core meeting :).

**Comment by PatrickKutch** [comment]
> Thanks Kural -- I think this does bring up a point that sometimes people expect the `:latest` tag to be, well, tip of master. Maybe this should change, however, I'd also say in tandem, that for community friendliness that the quick-start daemonset-style installation refer to a tagged release, potentially.

I think both, but at a minimum I'd make the yaml files point to a tagged release.

**Comment by dougbtv** [comment]
The yaml files do now point at a recent tagged release, usually in the format `:v3.x` :+1:
