### ISSUE TITLE
Proposal for improvements to releases and image tagging

### ISSUE THREAD

**Issue by dougbtv** [intel/multus-cni#260]
Here's my proposal for the changes to releases / image tagging.

## Release schedule

We should tag a release soon (as v3.2), and come up with a schedule for having a regularly tagged release (I propose every 3 months), we haven't had a tagged release in 6 months.

In concert with this, we'll also update the `images/multus-daemonset.yaml` to point at the newly tagged release, e.g.

```
image: nfvpe/multus:v3.2
```

## Improved image tagging

I propose that we tag a `:latest` image with each merge into master, this will make for a more intuitive use of the `:latest` tag. Previously, we only tagged `:latest` with each tagged release, and we would tag `:snapshot` with each merge into master (e.g. the `:snapshot` tagged image was equivalent to tip of master)

On the tagging of each release, we'll tag an image with the version, e.g. `vX.Y` (as we currently do) but, we'll also tag this image as `:stable`.

**Comment by SchSeba** [comment]
@dougbtv it will be nice to have also a Z stream for some important cherry picks like bugs and security issues.
