### ISSUE TITLE
which namespace should clusterNetwork be defined in

### ISSUE THREAD

**Issue by hanxueluo** [intel/multus-cni#261]
currently, multus-cni support specify pod default network in two ways:
1. add "clusterNetwork" in multus.conf, and no annotation on pod
2. annotation "v1.multus-cni.io/default-network" on pod, which overwrite the "clusterNetwork" in multus.conf

Before commit 6bf296f54d11d7a3e84020366116add9441e1570, these 2 configurations both lookup net-attach-def in namespace "default". After that commit, the first way lookups in namespace "kube-system", just as the commit message says "Change the namespace to 'kube-system'". However, the second still in namespace "default", because of the code in function "tryLoadK8sPodDefaultNetwork":
```
networks, err := parsePodNetworkAnnotation(netAnnot, "default")
```
I'm not sure whether it's a bug or on purpose? 
@s1061123, Could you explain some for me? Thanks

**Comment by s1061123** [comment]
@hanxueluo , this should be issue and both should be in 'multusNamespace' in config, default is 'kube-system'.

Let me fix the code.
