### ISSUE TITLE
Multus interoperation with Minikube

### ISSUE THREAD

**Issue by dougbtv** [intel/multus-cni#272]
**What would you like to be added**: Documentation reflecting usage on Minikube

**Why is this needed**: Would be nice for trial environment / first try with Multus.

**Current failings**: 

@mccv1r0 reports that:

> So my setup is fedora 28 native on laptop.   install minikube binary and start using KVM and crio.

He's using 

```
cat ./images/{multus-crio-daemonset.yml,flannel-daemonset.yml} | kubectl apply -f -
```

...to kick off the install.

He's running into an issue with Flannel (firstly), which results in pods that look like (this pastebin): http://pastebin.test.redhat.com/722516

**Comment by mccv1r0** [comment]
Additional info:

Host is fedora 28
minikube version: v0.33.1

start minikube using kvm2 and cri-o
```
minikube start \
    --network-plugin=cni \
    --enable-default-cni \
    --vm-driver=kvm2 \
    --container-runtime=cri-o \
    --cri-socket=/var/run/crio/crio.sock \
    --extra-config=kubelet.container-runtime=remote \
    --extra-config=kubelet.container-runtime-endpoint=unix:///var/run/crio/crio.sock \
    --extra-config=kubelet.image-service-endpoint=unix:///var/run/crio/crio.sock
```

multus wasn't auto-magically copied to node, so sample pod didn't start.  When I copied multus to /opt/cni/bin/multus, hit issue with flannel

**Comment by dougbtv** [comment]
This probably belongs best in the reference deployments @ https://github.com/k8snetworkplumbingwg/reference-deployment
