### ISSUE TITLE
multus-cni namespace issue

### ISSUE THREAD

**Issue by wei0313** [intel/multus-cni#277]
Hi 
I deployed multus-cni first. I was able to successfully deploy my pod without giving any namespace. Then, I created a new namespace. I tried to deploy the same image with the new yaml which reflects to the new namespace. However, I kept getting errors saying that it can't find multus-cni in this new namespace. What should I do to resolve this issue? I googled but can't seem to find the answer to this issue. If I need to redeploy multus-cni, what configuration do I need to add to fix this issue?

Thanks

**Comment by dougbtv** [comment]
Hi @wei0313 -- any chance you can provide us with the steps that you followed so that we can replicate the issue? We might be able to give you some deeper insight given that. Thanks!

**Comment by wei0313** [comment]
network CRD 
`apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovs-eth1-agnes
  namespace: agnestest
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/eth1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ovs",
      "bridge": "eth1"
    }'
`
deployment.yaml
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: agnes-test1
  namespace: agnestest
  labels:
    app: agnes-test1
spec:
  selector:
    matchLabels:
      app: agnes-test1
  template:
    metadata:
      labels:
        app: agnes-test1
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
                                        { "name": "ovs-eth1-agnes",
                                          "interfaceRequest": "eth1" }
                                      ]'
    spec:
      nodeSelector:
        type: agnestest
      containers:
      - name: agnes-test1
        image: test:18.2.10
        imagePullPolicy: Never
`

Error
`Mar  5 12:10:36 localhost kubelet: E0305 12:10:36.235256   15185 cni.go:345] Error deleting agnestest_agnes-test1-59bb9cd898-8j78f/c1c4e9b033c02e1d574f95a116fbcd6ddf8b36f1e7691f0cfa92f3adf98d3b7a from network multus/multus-cni-network: Multus: Err in getting k8s network from pod: GetK8sNetwork: failed getting the delegate: getKubernetesDelegate: failed to get network resource, refer Multus README.md for the usage guide: the server could not find the requested resource

Mar  5 12:10:36 localhost kubelet: E0305 12:10:36.571260   15185 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = [failed to set up sandbox container "c1c4e9b033c02e1d574f95a116fbcd6ddf8b36f1e7691f0cfa92f3adf98d3b7a" network for pod "agnes-vcmts-59bb9cd898-8j78f": NetworkPlugin cni failed to set up pod "agnes-test1-59bb9cd898-8j78f_agnestest" network: Multus: Err in loading K8s Delegates k8s args: Multus: Err in getting k8s network from pod: GetK8sNetwork: failed getting the delegate: getKubernetesDelegate: failed to get network resource, refer Multus README.md for the usage guide: the server could not find the requested resource, failed to clean up sandbox container "c1c4e9b033c02e1d574f95a116fbcd6ddf8b36f1e7691f0cfa92f3adf98d3b7a" network for pod "agnes-vcmts-59bb9cd898-8j78f": NetworkPlugin cni failed to teardown pod "agnes-test1-59bb9cd898-8j78f_agnestest" network: Multus: Err in getting k8s network from pod: GetK8sNetwork: failed getting the delegate: getKubernetesDelegate: failed to get network resource, refer Multus README.md for the usage guide: the server could not find the requested resource]
...
`

**Comment by maximshd** [comment]
Hi @wei0313 ,

I caught the same problem with the latest Multus version. To resolve it you need to configure clusterrolebinding for every node in k8s cluster. 
Please follow configuration guide - https://github.com/intel/multus-cni/tree/master/examples#rbac-configuration

**Comment by wardenlym** [comment]
i meet the same issue on ubuntu18.04, kubernetes (v1.14.1),nfvpe/multus:v3.2
it does not work  even  i update clusterrole system:node and create clusterrolebinding with all node hostname

should i do something else for creating workload in non default namespace?

```
E0505 09:33:17.714075    8549 pod_workers.go:190] Error syncing pod b768dde2-6f18-11e9-930c-0800277dca1b ("b-867989b75-5thk8_ns1(b768dde2-6f18-11e9-930c-0800277dca1b)"), skipping: failed to "CreatePodSandbox" for "b-867989b75-5thk8_ns1(b768dde2-6f18-11e9-930c-0800277dca1b)" with CreatePodSandboxError: "CreatePodSandbox for pod \"b-867989b75-5thk8_ns1(b768dde2-6f18-11e9-930c-0800277dca1b)\" failed: rpc error: code = Unknown desc = failed to set up sandbox container \"5a7bdad271029febfdb810b0de97d986049029028ff31c48f7cb06d6b94d4bd7\" network for pod \"b-867989b75-5thk8\": NetworkPlugin cni failed to set up pod \"b-867989b75-5thk8_ns1\" network: Multus: Err in loading K8s Delegates k8s args: Multus: Err in getting k8s network from pod: GetPodNetwork: failed getting the delegate: getKubernetesDelegate: failed to get network resource, refer Multus README.md for the usage guide: the server could not find the requested resource"
```

**Comment by holmesb** [comment]
Me too ("server could not find the requested resource") after creating clusterrole & bindings to all nodes.  @wardenlym, did you find a solution?

**Comment by s1061123** [comment]
Multus CNI lookup the net-attach-def in the namespace that pod is in due to [spec](https://github.com/k8snetworkplumbingwg/multi-net-spec) , hence, you need to add net-attach-def into new namespace, otherwise multus cannot find the net-attach-def.

Please check your namespace of Pod as well as net-attach-def and both are in same namespace.
