### ISSUE TITLE
Assign same ip address for POD

### ISSUE THREAD

**Issue by andysun1123** [intel/multus-cni#278]
I have deployed k8s cluster via kubeadm, 1 master +  2 node.
then deploy multus, default network is calico and CRD is macvlan.
https://github.com/intel/multus-cni/blob/master/doc/quickstart.md

Then I create 3 pods which depoly to 2 nodes.
the pod on different nodes will assign the same ip address via macvlan.
how could I control them, I want they have unique ip address and could reach each other.

kubectl get pod -o wide
NAME             READY   STATUS    RESTARTS   AGE   IP                NODE    NOMINATED NODE   READINESS GATES
mycentos-6kk8w   1/1     Running   0          7s    192.168.137.162   node1   <none>           <none>
mycentos-f976b   1/1     Running   0          7s    192.168.233.210   node2   <none>           <none>
mycentos-kntcc   1/1     Running   0          7s    192.168.137.163   node1   <none>           <none>

mycentos-6kk8w and mycentos-f976b have the same ip for net1.

Thanks in advence.

**Comment by SchSeba** [comment]
Hi @andysun1123 
the IPAM for macvlan is `"type": "host-local"` this mean every node only knows about is allocated ips if you want to have unique ip over the cluster please take a look on the dhcp IPAM https://github.com/containernetworking/plugins/tree/master/plugins/ipam/dhcp

**Comment by frui0101** [comment]
I met same issue, do you have any other approach for it? Is it possible that assign ip address by etcd instead of local assignment.
Seems nobody have the scenarios that the pod in different nodes wish to be assigned to same ip address.

**Comment by s1061123** [comment]
how about to use static ipam for that? 
Multus can assign ip address from pod annotation with static IPAM CNI pluigin as follows:

```
---
apiVersion: "kubernetes.cni.cncf.io/v1"
kind: Network
metadata:
  name: macvlan-conf-1
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": "eth1",
            "mode": "bridge",
            "ipam": {
                "type": "static"
            }
        }'
```

Pod side:
```
  annotations:
     k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "macvlan-conf-1",
          "ips": ["10.2.2.42", "2001:db8::5"]
        }
      ]
```

**Comment by frui0101** [comment]
@s1061123 thanks your suggestion, sorry, I can't try it successfully and have enough time for trying. Also seems it is not feasible if we have several pods in the deployment, we can't use fixed ip address in the pod.
I have one idea  about it, based on the mechanism of the host-local plugins, It got ip address from "/var/lib/cni/networks/macvlan-cni/last_reserved_ip.0" locally, with least effort approach is we mount same remote folder to this folder, just an idea, have no time to try..

**Comment by boat320** [comment]
Hi @s1061123
I can't set pod ip like your example.
but I can set pod IP like this:
apiVersion: apps/v1
kind: NetworkAttachmentDefinition
metadata:
  name: sdj-discovery-center
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "em1",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "addresses": [{"address": "10.3.32.17/24","gateway": "10.3.32.1"}],
        "routes": [
          { "dst": "0.0.0.0/0" }
        ]
      }
    }'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdj-discovery-center
spec:
  selector:
    matchLabels:
      app: sdj-discovery-center
  replicas: 3
  template:
    metadata:
      labels:
        app: sdj-discovery-center
      annotations:
        k8s.v1.cni.cncf.io/networks: sdj-discovery-center
    spec:
      containers:
....

So how can I set the pod IP like you

**Comment by s1061123** [comment]
Hi @boat320 

Here is what I do today (with latest multus binary). The static plugin uses CIDR notation for now, so current config is slightly different from my previous one.

How to do that:

1. Verify `static` CNI plugin is in your CNI plugin path (usually `/opt/cni/bin`)
1. Add `static` in "ipam" of your net-attach-def
1. Add `"ips": "<address in CIDR notation>"` in pod annotations

Here is the example config.

```
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-eth1
spec: 
  config: '{
                "cniVersion": "0.3.0",
		"name": "test",
                "type": "vlan",
                "master": "eth1",
		"vlanId": 1,
                "ipam": {
                        "type": "static"
                }
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-case-01
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "vlan-eth1",
              "ips": "172.16.1.10/24"
            }
    ]'
spec:
  containers:
  - name: pod-case-01
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
```


Here is the result of `ip address show`

```
[root@pod-case-01 /]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether e6:44:b0:df:ea:ed brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.1.3/24 brd 10.244.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::e444:b0ff:fedf:eaed/64 scope link 
       valid_lft forever preferred_lft forever
4: net1@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 52:54:00:aa:c8:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.16.1.10/24 brd 172.16.1.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:feaa:c803/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by boat320** [comment]
it's not work ,this is my setting:
 #############################
  apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-1
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "em1",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-22-5-deployment
spec:
  selector:
    matchLabels:
      app: nginx-22-5
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-22-5
      annotations:
#        k8s.v1.cni.cncf.io/networks: default/macvlan-conf-1
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan-conf-1",
              "ips": "10.3.32.199/24"
            }
    ]'
     spec:
      nodeName: node1
      containers:
      - name: nginx-23-5
        image: nginx:1.7.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
################################
 [root@t021100 k8s_test]# kubectl exec -it nginx-22-5-deployment-6c77855c5b-ddlv2 ip add
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if80: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
    link/ether 0a:58:0a:f4:01:4b brd ff:ff:ff:ff:ff:ff
    inet 10.244.1.75/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::fcba:3aff:fea1:9992/64 scope link 
       valid_lft forever preferred_lft forever
 ##############################################
  
 I use macvlan cni 

 

 ------------------ 原始邮件 ------------------
  发件人: "Tomofumi Hayashi"<notifications@github.com>;
 发送时间: 2019年5月13日(星期一) 下午2:42
 收件人: "intel/multus-cni"<multus-cni@noreply.github.com>;
 抄送: "撩进碗里就是菜"<330934554@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [intel/multus-cni] Assign same ip address for POD (#278)

 

 
Hi @boat320
 
Here is what I do today (with latest multus binary). The static plugin uses CIDR notation for now, so current config is slightly different from my previous one.
 
How to do that:
  
Verify static CNI plugin is in your CNI plugin path (usually /opt/cni/bin)
 
Add static in "ipam" of your net-attach-def
 
Add "ips": "<address in CIDR notation>" in pod annotations
 
Here is the example config.
--- apiVersion: "k8s.cni.cncf.io/v1" kind: NetworkAttachmentDefinition metadata:   name: vlan-eth1 spec:    config: '{                 "cniVersion": "0.3.0", 		"name": "test",                 "type": "vlan",                 "master": "eth1", 		"vlanId": 1,                 "ipam": {                         "type": "static"                 }         }' --- apiVersion: v1 kind: Pod metadata:   name: pod-case-01   annotations:     k8s.v1.cni.cncf.io/networks: '[             { "name": "vlan-eth1",               "ips": "172.16.1.10/24"             }     ]' spec:   containers:   - name: pod-case-01     image: docker.io/centos/tools:latest     command:     - /sbin/init  
Here is the result of ip address show
[root@pod-case-01 /]# ip a 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00     inet 127.0.0.1/8 scope host lo        valid_lft forever preferred_lft forever     inet6 ::1/128 scope host         valid_lft forever preferred_lft forever 3: eth0@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default      link/ether e6:44:b0:df:ea:ed brd ff:ff:ff:ff:ff:ff link-netnsid 0     inet 10.244.1.3/24 brd 10.244.1.255 scope global eth0        valid_lft forever preferred_lft forever     inet6 fe80::e444:b0ff:fedf:eaed/64 scope link         valid_lft forever preferred_lft forever 4: net1@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default      link/ether 52:54:00:aa:c8:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0     inet 172.16.1.10/24 brd 172.16.1.255 scope global net1        valid_lft forever preferred_lft forever     inet6 fe80::5054:ff:feaa:c803/64 scope link         valid_lft forever preferred_lft forever

**Comment by s1061123** [comment]
@boat320 
macvlan is also worked with following config. You may need to check following:

- multus binary is up-to-date
- static plugin is up-to-date (I use [CNI plugin v0.8.0](https://github.com/containernetworking/plugins/releases/tag/v0.8.0))

```
[centos@kube-master demo_static_1905]$ /opt/cni/bin/multus --version
multus-cni version:master, commit:d8638643233d7848c7aec6aa5cfbe3c572530267, date:2019-05-10T14:10:14+0000
```

```
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-eth1
spec:
  config: '{
                "cniVersion": "0.3.0",
                "name": "test",
                "type": "macvlan",
                "master": "eth1",
                "ipam": {
                        "type": "static"
                }
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-case-01
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "vlan-eth1",
              "ips": "10.1.1.101/24"
            }
    ]'
spec:
  containers:
  - name: pod-case-01
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
```

```
[root@pod-case-01 /]# ip -d a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 promiscuity 0 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3: eth0@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether 9e:e3:bb:48:28:d9 brd ff:ff:ff:ff:ff:ff link-netnsid 0 promiscuity 0
    veth numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
    inet 10.244.1.4/24 brd 10.244.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::9ce3:bbff:fe48:28d9/64 scope link
       valid_lft forever preferred_lft forever
4: net1@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default
    link/ether 46:34:5f:8a:f3:3d brd ff:ff:ff:ff:ff:ff link-netnsid 0 promiscuity 0
    macvlan mode bridge numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
    inet 10.1.1.101/24 brd 10.1.1.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::4434:5fff:fe8a:f33d/64 scope link
       valid_lft forever preferred_lft forever
```

If you still have the issue, could you please provide following information next time?

- Kubernetes version (and how to install Kubernetes)
- `multus` binary version (you can get `multus --version`)
- CNI plugin for network attachment (i.e. release version or git hash for the source)
- yaml file for the network attachment and pod
- multus debug log (please set `    "logLevel": "debug"` in your multus CNI config

**Comment by boat320** [comment]
thankyou so mutch ! I got it.
 But I have another question:
   How to set the gateway at this mode
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Tomofumi Hayashi"<notifications@github.com>;
 发送时间: 2019年5月13日(星期一) 晚上9:03
 收件人: "intel/multus-cni"<multus-cni@noreply.github.com>;
 抄送: "撩进碗里就是菜"<330934554@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [intel/multus-cni] Assign same ip address for POD (#278)

 

 
@boat320
macvlan is also worked with following config. You may need to check following:
  
multus binary is up-to-date
 
static plugin is up-to-date (I use CNI plugin v0.8.0)
[centos@kube-master demo_static_1905]$ /opt/cni/bin/multus --version multus-cni version:master, commit:d8638643233d7848c7aec6aa5cfbe3c572530267, date:2019-05-10T14:10:14+0000 --- apiVersion: "k8s.cni.cncf.io/v1" kind: NetworkAttachmentDefinition metadata:   name: vlan-eth1 spec:   config: '{                 "cniVersion": "0.3.0",                 "name": "test",                 "type": "macvlan",                 "master": "eth1",                 "ipam": {                         "type": "static"                 }         }' --- apiVersion: v1 kind: Pod metadata:   name: pod-case-01   annotations:     k8s.v1.cni.cncf.io/networks: '[             { "name": "vlan-eth1",               "ips": "10.1.1.101/24"             }     ]' spec:   containers:   - name: pod-case-01     image: docker.io/centos/tools:latest     command:     - /sbin/init [root@pod-case-01 /]# ip -d a 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 promiscuity 0 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535     inet 127.0.0.1/8 scope host lo        valid_lft forever preferred_lft forever     inet6 ::1/128 scope host        valid_lft forever preferred_lft forever 3: eth0@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default     link/ether 9e:e3:bb:48:28:d9 brd ff:ff:ff:ff:ff:ff link-netnsid 0 promiscuity 0     veth numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535     inet 10.244.1.4/24 brd 10.244.1.255 scope global eth0        valid_lft forever preferred_lft forever     inet6 fe80::9ce3:bbff:fe48:28d9/64 scope link        valid_lft forever preferred_lft forever 4: net1@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default     link/ether 46:34:5f:8a:f3:3d brd ff:ff:ff:ff:ff:ff link-netnsid 0 promiscuity 0     macvlan mode bridge numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535     inet 10.1.1.101/24 brd 10.1.1.255 scope global net1        valid_lft forever preferred_lft forever     inet6 fe80::4434:5fff:fe8a:f33d/64 scope link        valid_lft forever preferred_lft forever  
If you still have the issue, could you please provide following information next time?
  
Kubernetes version (and how to install Kubernetes)
 
multus binary version (you can get multus --version)
 
CNI plugin for network attachment (i.e. release version or git hash for the source)
 
yaml file for the network attachment and pod
 
multus debug log (please set "logLevel": "debug" in your multus CNI config

**Comment by s1061123** [comment]
you just add gateway config in 'ipam' section in network attachment.

**Comment by hymgg** [comment]
@s1061123 please excuse a dumb question. Say we have pod1 on node1 with static ip 10.1.1.101, pod2 on node2 with static ip 10.1.1.102, pod3 on node3 with static ip 10.1.1.103, how do we get the pods to connect / communicate? Thanks.  -Jessica

**Comment by s1061123** [comment]
@hymgg you need to write net-attach-def to connect the pod each other. K8s will schedule the pod to each worker nodes by K8s scheduler, so we cannot identify which node will have the pod. 

For a example, let's imagine two NICs (eth0,eth1) are installed into each worker node and each eth0 are connected and each eth1 are connected. At that time, using macvlan (i.e. master:eth1) for net-attach-def,, all pods are connected.

**Comment by hymgg** [comment]
@s1061123 what if we're using sriov? Here's current config following your example,

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net-4
  namespace: mtx-test10
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov_net_A
spec:
  config: '{
  "type": "sriov",
  "name": "sriov-network-4",
  "ipam": {
    "type": "static"
  }
}'



apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  namespace: mtx-test10
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "sriov-net-4",
              "ips": "10.1.1.101/24"
            }
    ]'
spec:
  containers:
  - name: appcntr1 
    image: centos/tools 
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/sriov_net_A: '1' 
      limits:
        intel.com/sriov_net_A: '1'
  nodeName: mtx-hw3-bld01



apiVersion: v1
kind: Pod
metadata:
  name: testpod2
  namespace: mtx-test10
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "sriov-net-4",
              "ips": "10.1.1.102/24"
            }
    ]'
spec:
  containers:
  - name: appcntr1 
    image: centos/tools 
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/sriov_net_A: '1' 
      limits:
        intel.com/sriov_net_A: '1'
  nodeName: mtx-hw3-bld02


Thanks.  -Jessica

**Comment by s1061123** [comment]
@hymgg it seems to be sr-iov cni question, not multus. Could you ask sr-iov community about it?

**Comment by hymgg** [comment]
@s1061123 thank you, asking in sriov-cni...

**Comment by ebahou** [comment]
Hello, and thank you for the information you have provided thus far.

I can successfully run a pod with a static IP address when I add an address field to the NetworkAttachementDefinition config as follows:
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachementDefinition
metadata:
  name: macvlan-1g
spec:
config: '{
    "cniVersion": "0.3.0",
    "name": "macvlan-1g"
    "type": "macvlan",
    "master": "eth0",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "10.4.5.6/16",
          "gateway": "0.0.0.0"
        }
      ]
    }
  }'
```
Pod Side:
```
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
  labels:
    name: my-pod
    namespace: default
    app: my-app
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-1g
spec:
  serviceAccountName: default
  containers:
  - name: my-container
    image: repository:5000/my-image
    command: ["/bin/bash"]
```

*However*, when I try to inject an IP address using the ```k8s.v1.cni.cncf.io/networks:``` Pod annotation just like you did in your latest example, Macvlan reports an error: ```Multus: error in invoke Delegate add - "macvlan": IPAM plugin returned missing IP config```

So, I did debug the CNI plugins (Multus, Macvlan, Static) and I can see that in this scenario, the Pod annotation is *not* being passed to those binaries via the stdin JSON data. I did also attempt passing an IP through CNI_ARGS from a Pod yaml environment field, but that also was not passed to the CNI environment from Kubelet.

Any help or insight would be tremendously valued.

I am using K8s 1.13.1, CNI v0.8, and Multus 3.1 with Flannel as the primary interface and Macvlan/Static as the secondary interface. For reference, here are the respective NetworkAttachementDefinition and Pod yamls:
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachementDefinition
metadata:
  name: macvlan-1g
spec:
config: '{
    "cniVersion": "0.3.0",
    "type": "macvlan",
    "master": "eth0",
    "ipam": {
      "type": "static",
      "gateway": "0.0.0.0"
    }
  }'
```
```
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
  labels:
    name: my-pod
    namespace: default
    app: my-app
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
                               { "name": "macvlan-1g",
                               "ips": "10.4.5.6/16" }
                               ]'
spec:
  serviceAccountName: default
  containers:
  - name: my-container
    image: repository:5000/my-image
    command: ["/bin/bash"]
```

**Comment by s1061123** [comment]
@ebahou 

- Typo: "kind: NetworkAttachementDefinition" -> "kind: NetworkAttachmentDefinition"
- tested following yaml

```
[centos@kube-master ~]$ cat test.yml 
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-1g
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "eth1",
    "ipam": {
      "type": "static"
    }
  }'
---
apiVersion: v1
kind: Pod
metadata:
  name: multus-01-simple
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "macvlan-1g", "ips": "10.1.1.6/24" }]'
spec:
  containers:
  - name: multus-01-simple
    image: docker.io/centos/tools:latest
    command:
      - /sbin/init
[centos@kube-master ~]$ kubectl create -f test.yml 
networkattachmentdefinition.k8s.cni.cncf.io/macvlan-1g created
pod/multus-01-simple created
[centos@kube-master ~]$ kubectl get pod -o wide
NAME               READY   STATUS    RESTARTS   AGE   IP           NODE          NOMINATED NODE   READINESS GATES
multus-01-simple   1/1     Running   0          19s   10.244.2.6   kube-node-2   <none>           <none>
[centos@kube-master ~]$ kubectl exec -it multus-01-simple ip a 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether da:6b:fe:79:6e:26 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.2.6/24 brd 10.244.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::d86b:feff:fe79:6e26/64 scope link 
       valid_lft forever preferred_lft forever
4: net1@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/ether d6:ee:5d:c6:85:05 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.1.1.6/24 brd 10.1.1.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::d4ee:5dff:fec6:8505/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by dolphyvn** [comment]
for this issue, I used ping to check the result of requestedIP. if it already in use then move on to next one from the range. It works really well on my productions env atm. I know there are dhcp and whereabouts from dougbtv but I thought this would be an easy fix for my requirement.

**Comment by ebahou** [comment]
After doing a code analysis, the most recent official release of Multus CNI is 3.2 at this time. We had downloaded Multus 3.1 right before the 3.2 release.

**Comment by mJace** [comment]
Defining static IP in pod's annotation is not working in multus v3.4.
@s1061123  Can you check this? Does multus deprecated this? or it is a bug?

k8s v1.14.3 + multus v3.2 -> ok to define ip in pod annotation.
but 
k8s v1.14.3 + multus v3.4 -> can not define pod ip in annotation.

**Comment by danieler81** [comment]
same here....I can't define static ip:

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-ops
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "eno1.11",
    "ipam": {
      "type": "static"
    }
  }'
```

```
apiVersion: v1
kind: Pod
metadata:
  name: pod-bn1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "macvlan-ops", "ips": "10.5.11.14/24" }]'
spec:
  containers:
  - name: pod-bn1
    image: docker.io/centos/tools:latest
    command:
      - /sbin/init
```

[leo@manager MANAGER test]$ kubectl exec -it pod-bn1 -- ifconfig -a
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.244.2.8  netmask 255.255.255.0  broadcast 0.0.0.0
        ether b2:22:c0:c9:62:bb  txqueuelen 0  (Ethernet)
        RX packets 7  bytes 622 (622.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1  bytes 42 (42.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[leo@manager MANAGER net.d]$ /opt/cni/bin/multus --version
multus-cni version:v3.4, commit:230f3148779c787b86ddeac05343f33b4fdf960b, date:2019-12-03T21:17:13+0000

[leo@manager MANAGER test]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by s1061123** [comment]
> Defining static IP in pod's annotation is not working in multus v3.4.
> @s1061123 Can you check this? Does multus deprecated this? or it is a bug?
> k8s v1.14.3 + multus v3.2 -> ok to define ip in pod annotation.
> but
> k8s v1.14.3 + multus v3.4 -> can not define pod ip in annotation.

From multus v3.4, ips and mac uses CNI `runtimeConfig` `capabilities` framework as following spec:
https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md

Hence CNI configuration is changed as following.

```
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: centos-runtimeconfig-def
spec:
  config: '{
            "cniVersion": "0.3.1",
            "plugins": [
                {
                    "type": "macvlan",
                    "capabilities": { "ips": true },
                    "master": "eth1",
                    "mode": "bridge",
                    "ipam": {
                        "type": "static"
                    }
                } ]
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-runtimeconfig
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "centos-runtimeconfig-def",
              "ips": [ "10.1.1.104/24" ] }
    ]'
spec:
  containers:
  - name: centos-runtimeconfig
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
    securityContext:
      privileged: true
```

**Comment by XueCangQiuYe** [comment]
Really useful

**Comment by thockin** [comment]
Is it problematic to allow a pod to set its own IP with no formal "approval" mechaanism?

**Comment by s1061123** [comment]
@thockin thank you for your comment. `static` plugin is not formal way, mainly as noted in [static plugin](https://www.cni.dev/plugins/current/ipam/static/). This should be mainly debug purpose or some valid reason why they, user, want to assign IPs somehow because it is not scalable with Kubernetes Deployment or some similar mechanisms.

NPWG (Network Plumbing WG) also provides [whereabouts plugin](https://github.com/k8snetworkplumbingwg/whereabouts) which allows user to assign IP addresses to the Pod. We suppose that many user uses whereabout CNI plugin for IPAM in case of multus interface, hence we don't recommend to static plugin for IPAM, multus just provide a way to use it easily with CNI mechanism (`capabilities` and `runtimeConfig`).

**Comment by cHunter789** [comment]
@s1061123 If I want to use SBR plugin in the manner presented by You (really thanks for that), how can I do that? It should be set in NetworkAttachmentDefinition or in Pod under annotations?

**Comment by s1061123** [comment]
@cHunter789 I don't know how to do that because I don't use SBR plugin.

**Comment by mr-yaky** [comment]
@s1061123 does this plugin support adding a regular static ip? I mean without using ranges. For example, to connect a public IP to a pod.

**Comment by s1061123** [comment]
in such case, static plugin in cni github repo could be fit, I guess.

**Comment by sachinaravind92** [comment]
Hi @s1061123 , does this ipam type 'static' support SCTP protocol?
