### ISSUE TITLE
Unable to assign MAC when using DHCP

### ISSUE THREAD

**Issue by Elegant996** [intel/multus-cni#285]
**What happened**:
Using `mac` in the annotations did not work when specifying `dhcp` as the `ipam`.

**What you expected to happen**:
`multus` to apply the `mac` in order to allow the `dhcp` plugin to be able to acquire a desired reservation from the DHCP server.

**How to reproduce it (as minimally and precisely as possible)**:
Create a config for `multus` which uses the `dhcp` plugin for the `ipam` ensuring that the daemon is running.

**Anything else we need to know?**:
Not 100% sure if this is a `multus` issue or a `cni` plugin issue but thought I'd start here.

**Environment**:
Latest snapshot as of March 20th.

**Logs**:

> Warning  FailedCreatePodSandBox  1s    kubelet, kube-node02.example.com  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "8341a9db002ce151dd67d3240cf42473e37b31ac8deafc43b370794a0777833e" network for pod "alpinepod": NetworkPlugin cni failed to set up pod "alpinepod_default" network: Multus: Err adding pod to network "dhcp-conf": Multus: error in invoke Conflist add - "dhcp-conf": error in getting result from AddNetworkList: failed to set "net1" address to "e7:d1:44:8d:65:b0": cannot assign requested address, failed to clean up sandbox container "8341a9db002ce151dd67d3240cf42473e37b31ac8deafc43b370794a0777833e" network for pod "alpinepod": NetworkPlugin cni failed to teardown pod "alpinepod_default" network: Multus: error in invoke Delegate del - "": no plugin name provided]

**Config**:
```
---
kind: NetworkAttachmentDefinition
apiVersion: "k8s.cni.cncf.io/v1"
metadata:
  name: dhcp-conf
spec: 
  config: '{
    "cniVersion": "0.3.1",
    "name": "dhcp-conf",
    "plugins": [
      {
        "type": "macvlan",
        "master": "net0",
        "ipam": {
          "type": "dhcp"
        }
      },
      {
        "type": "tuning"
      }
    ]
  }'
```

**Pod**:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: alpinepod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
        "name": "dhcp-conf",
        "mac": "e7:d1:44:8d:65:b0"
      }
    ]'
spec:
  containers:
  - name: alpinepod
    image: alpine:latest
    command: ["/bin/sh", "-c", "sleep 2000000000000"]
```

**Comment by s1061123** [comment]
There are several reason as follows:

1. As following, your mac address, "e7:d1:44:8d:65:b0", is rejected by kernel due to local bit misssing
https://superuser.com/questions/725467/set-mac-address-fails-rtnetlink-answers-cannot-assign-requested-address/725472

```
# ip link add macv1 link eno1 type macvlan mode bridge
# ip link set up macv1
# ip link set macv1 address e7:d1:44:8d:65:b0
RTNETLINK answers: Cannot assign requested address
# ip link set macv1 address e8:d1:44:8d:65:b0
# (succeed)
```

2. If you change MAC address, dhcp address should be invalid because dhcp protocol uses client MAC address for the IP address association. So you need to change MAC address before IPAM allocation by dhcp, but currently CNI macvlan/dhcp does not allow it.

**Comment by s1061123** [comment]
hi. It is quite a long time from the last update. So let me close the issue.
Please re-open it if you have update on that.
