### ISSUE TITLE
SR-IOV doesn't work with Multus using conflist

### ISSUE THREAD

**Issue by zshi-redhat** [intel/multus-cni#289]
**What happend**:

SR-IOV CNI doesn't recognize the ``deviceID`` passed from Multus in the case of ``conflist`` (chained plugin config format) is used.

**What you expected to happen**:

Multus passes the correct conflist format to SR-IOV CNI.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the instructions in SR-IOV Network Device Plugin [README](https://github.com/intel/sriov-network-device-plugin) to create pods with SR-IOV device attached to it.
replace sriov-crd.yaml net-attach-def Custom Resource with:
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov
spec:
  config: '{
        "name": "sriov-network",
        "plugins": [
                {
                        "type": "sriov",
	                "ipam": {
		                "type": "host-local",
		                "subnet": "10.56.217.0/24",
		                "routes": [{
			                "dst": "0.0.0.0/0"
		                }],
		                "gateway": "10.56.217.1"
                        }
	        }
        ]
}'
```
Create pods requesting SR-IOV resource again.

**Anything else we need to know?**:

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')

Multus master branch

- Kubernetes version (use `kubectl version`):

any kube version, for example, 1.12, 1.13

- Primary CNI for Kubernetes cluster:

Multus

- OS (e.g. from /etc/os-release):

CentOS 7.6

- File of '/etc/cni/net.d/'
```
{
	"name": "multus-cni-network",
	"type": "multus",
	"logLevel": "debug",
	"logFile": "/var/log/multus.log",
	"delegates": [{
		"type": "flannel",
		"delegate": {
			"isDefaultGateway": true
		}
	}],
	"kubeconfig": "/etc/kubernetes/admin.conf"
}
```

- File of '/etc/cni/multus/net.d'

N/A

- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

```
2019-03-25T03:39:55-04:00 [debug] conflistDel: &{6e33d59199aedd486f3e6a541687660e4dc73a722960eb63d8bbd9496b918307 /proc/74657/ns/net net1 [[IgnoreUnknown 1] [K8S_POD_NAMESPACE default] [K8S_POD_NAME testpod1] [K8S_POD_INFRA_CONTAINER_ID 6e33d59199aedd486f3e6a541687660e4dc73a722960eb63d8bbd9496b918307]] map[] }, {"deviceID":"0000:87:02.5","name":"sriov-network","plugins":[{"ipam":{"gateway":"10.56.217.1","routes":[{"dst":"0.0.0.0/0"}],"subnet":"10.56.217.0/24","type":"host-local"},"type":"sriov"}]}, /opt/cni/bin
2019-03-25T03:39:55-04:00 [error] error in getting result from DelNetworkList: failed to convert major version part "": strconv.Atoi: parsing "": invalid syntax
2019-03-25T03:39:55-04:00 [error] Multus: error in invoke Conflist Del - "sriov-network": error in getting result from DelNetworkList: failed to convert major version part "": strconv.Atoi: parsing "": invalid syntax
```

**Comment by zshi-redhat** [comment]
@s1061123 thanks for capturing this issue!

**Comment by ahalim-intel** [comment]
@zshi-redhat The error log shows it failed on delete during CNI version parsing. The CRD above has no version information, I'm not sure what is the default behavior is if delegate has no version information.

As a side note: I don't get the use-case with the above config for sriov-cni. The "deviceID" is expected to be unique on each Pod. Usually we leave this out in CRD for Multus to fill in when it parses delegate conf. Can you please elaborate. OR is this is just use as an example how to reproduce it?

**Comment by zshi-redhat** [comment]
> @zshi-redhat The error log shows it failed on delete during CNI version parsing. The CRD above has no version information, I'm not sure what is the default behavior is if delegate has no version information.

Sorry for the misleading of error messages, please take a look at this line:
```
 {"deviceID":"0000:87:02.5","name":"sriov-network","plugins":[{"ipam":{"gateway":"10.56.217.1","routes":[{"dst":"0.0.0.0/0"}],"subnet":"10.56.217.0/24","type":"host-local"},"type":"sriov"}]}
```
it has ``deviceID`` parameter included in the same level as ``name``, which shall be contained inside ``plugins`` as a sub-option.

> 
> As a side note: I don't get the use-case with the above config for sriov-cni. The "deviceID" is expected to be unique on each Pod. Usually we leave this out in CRD for Multus to fill in when it parses delegate conf. Can you please elaborate? OR is this just usee as an example on how to reproduce it?

Yes, the example CRD above is for demonstrating how to reproduce the issue and how it shall be fixed.

**Comment by Dev0Null** [comment]
Good day,

I'm also encountering this issue. Is this issue fixed via the above-noted commits? If so, I was planning to pull either `v3.3-tp` or `HEAD` from source and re-testing.

Thanks.

**Comment by zshi-redhat** [comment]
> Good day,
> 
> I'm also encountering this issue. Is this issue fixed via the above-noted commits? If so, I was planning to pull either `v3.3-tp` or `HEAD` from source and re-testing.

Yes, it was fixed via this [PR](https://github.com/intel/multus-cni/pull/290), either `v3.3-tp` or `HEAD` should contain the fix. Closing this issue.

> 
> Thanks.
