### ISSUE TITLE
Support chained CNI Plugins

### ISSUE THREAD

**Issue by piglei** [intel/multus-cni#29]
CNI v0.3.0 defined a way to call a list of plugins by defining multiple plugins in "plugins" field([details](https://github.com/containernetworking/cni/blob/spec-v0.3.0/SPEC.md#network-configuration-lists)).

But this feature is not supported in multus. If you try to use a CNI plugin(like "[portmap](https://github.com/containernetworking/plugins/tree/master/plugins/meta/portmap)") which is supposed to be used as a chained plugin only, you will get an error message: `must be called as chained plugin`.

Can multus support chained plugins?

I think we can add a special type of Network Resource, like "chained", and defined the real plugin type and args in the "args" field. So multus will understand this network is a "chained plugins" and call it sequentially with prevResult enabled.

**Comment by rkamudhan** [comment]
@piglei Could you please give me the details of conf files you using in kubernetes cluster, we sort of achieving the cni chaining mechanism in Multus, I may help you to achieve it. Multus was developed before the cni chaining mechanism, I also believe in it has to evolve.

**Comment by piglei** [comment]
@rkamudhan The [current default configuration file of flannel](https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml) is using chained CNI plugins feature, you can check it out.

```json
    {
      "name": "cbr0",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
```

In this config, the last portmap CNI plugin was called as a chained plugin.

**Comment by rkamudhan** [comment]
@piglei Working on #37 ..

**Comment by krsna1729** [comment]
same with newer versions of calico

```
{
    "name": "k8s-pod-network",
    "cniVersion": "0.3.0",
    "plugins": [
        {
            "type": "calico",
            "etcd_endpoints": "http://10.96.232.136:6666",
            "log_level": "info",
            "mtu": 1500,
            "ipam": {
                "type": "calico-ipam"
            },
            "policy": {
                "type": "k8s"
            },
            "kubernetes": {
                "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
            }
        },
        {
            "type": "portmap",
            "snat": true,
            "capabilities": {
                "portMappings": true
            }
        }
    ]
}
```

**Comment by rkamudhan** [comment]
@krsna1729 I am working on the conflist files support on Multus v2.1. Will add the conflist file support in the code: https://github.com/intel/multus-cni/blob/dev/network-plumbing-working-group-crd-change/k8sclient/k8sclient.go#L154

**Comment by rkamudhan** [comment]
@piglei @krsna1729 conflist will be supported in the Multus v2.2, a PR will be raised before EOW

**Comment by rkamudhan** [comment]
@piglei check the #103 PR

**Comment by matrohon** [comment]
@rkamudhan 
I gave your patch a try, but with a conflist in the "delegates" part of the multus.conf:

```
{
  "name": "multus-cni-network",
  "type": "multus",
  "delegates": [
    {
        "cniVersion": "0.3.1",
        "name": "rkt.kubernetes.io",
        "plugins": [
            {
                "type": "bridge",
                "bridge": "mybridge",
                "mtu": 1460,
                "addIf": "true",
                "isGateway": true,
                "ipMasq": true,
                "ipam": {
                    "type": "host-local",
                    "subnet": "10.1.0.0/16",
                    "gateway": "10.1.0.1",
                    "routes": [
                        {
                            "dst": "0.0.0.0/0"
                        }
                    ]
                }
            },
            {
                "type": "portmap",
                "capabilities": {"portMappings": true},
                "externalSetMarkChain": "KUBE-MARK-MASQ"
            }
        ]
    }
  ],
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
}
```
I recompiled the multus binary, after having checkouted to the dev/net....crd-change thanks to @dougbtv container.

Starting a pod results in a crash of the multus binary.
Maybe I'm missing something?

**Comment by matrohon** [comment]
I think the port mapping feature doesn't work because the runtime config doesn't retrieve the port mapping config for the pod:
https://github.com/intel/multus-cni/blob/master/types/conf.go#L75

It does in the dockershim code:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/network/cni/cni.go#L354

**Comment by rkamudhan** [comment]
@s1061123 @dcbw Could you please help me on this.. I think we discussed it during our last meeting. We planned to include the port mapping feature in further release ?

**Comment by matrohon** [comment]
@rkamudhan I'll also try to give a hand, but I first need to better understand libcni and multus internals.
