### ISSUE TITLE
Multus binary missing in /opt/cni/bin with version 3.1 yaml file 

### ISSUE THREAD

**Issue by Raajev** [intel/multus-cni#293]
I was unable to get the multus binary file in the /opt/cni/bin directory when applied the v3.1 yaml file from
https://raw.githubusercontent.com/intel/multus-cni/v3.1/images/multus-daemonset.yml

Config files and images in the docker were updated though. Also, image tag was "latest" and not v3.1.

With v3.2 yaml file, i get the binary file in the /opt/cni/bin and correct image tag in docker.

I also tried applying the yaml files directly with

`kubectl apply -f https://raw.githubusercontent.com/intel/multus-cni/v3.1/images/multus-daemonset.yml
kubectl apply -f https://raw.githubusercontent.com/intel/multus-cni/v3.1/images/flannel-daemonset.yml`

**Environment**:
Ubuntu 18.04.1

**Comment by dougbtv** [comment]
Thanks for the report Raajev -- you'll need to update the daemonset to set the tag specifically after we changed the tagging scheme recently:

```
nfvpe/multus:v3.1
```

**Comment by dougbtv** [comment]
Also -- updated the release notes for v3.1, thanks again for reporting this one!

https://github.com/intel/multus-cni/releases/tag/v3.1
