### ISSUE TITLE
Change in network attachement between v3.2 and v3.1

### ISSUE THREAD

**Issue by Raajev** [intel/multus-cni#294]
With v3.2, we are no longer able to use "interfaceRequest" key for network Attachments.

`  networkAttachments:
  - name: node-int1
    interfaceRequest: eth1
`
We now need to use "interface" instead
`  networkAttachments:
  - name: node-int1
    interface: eth1
`
This is breaking the backward compatibility.

I was expecting that for backward compatibility both "interface" & "interfaceRequest" should work (hopefully till release 4.0)

This can be reproduced in the applications where custom name is used for the multus interface.

Environment:
Ubuntu 18.04.1
Kubernetes v1.13

**Comment by MihailKo** [comment]
This is a very frustrating Issue. Please, give some attention to this issue.

**Comment by giovanism** [comment]
@dougbtv Can we just update the docs to use the correct Network Attachment Selection Annotation
format? And also provide compatibility for `interfaceRequest` parameter?

**Comment by giovanism** [comment]
Oh, and why they (ips, mac, interface) are called "request"? I think network attachment on its own is already considered a request.
