### ISSUE TITLE
Multus doesn't support ipv6 k8s api service endpoint

### ISSUE THREAD

**Issue by kahou82** [intel/multus-cni#299]
I am trying to setup a k8s cluster with two interfaces: primary interface ipv6 running as Calico CNI and the secondary interface running as macvlan.

I can successfully setup an IPv6 pod and all the services are working well (api server is running as IPv6 and my pod can communicate to it).

But when I try to spin up a pod with macvlan as the secondary interface, I see the following message in the multus delegate log:

`Apr 01 23:11:31 kahou-multus-6-worker-1 kubelet[4442]: 2019-04-01T23:11:31Z [debug] tryLoadK8sDelegates: Err in loading K8s cluster default network from pod annotation: Get https://fd03::1:443/api/v1/namespaces/default/pods/testpod: invalid URL port ":1:443", use cached delegates
`

Notice fd03::1 is the api k8s service endpoint but the curl is using a wrong syntax; It should be https://[fd03::1]:443/api/v1/namespaces/default/pods/testpod instead.

**What happend**:
Unable to attach the second interface

**What you expected to happen**:
Second interface (ipv4) should be attached

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
- Primary CNI for Kubernetes cluster:
- OS (e.g. from /etc/os-release):
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by dougbtv** [comment]
Any chance you could try to build a Multus image using this modified entrypoint in this PR and see if it works for you?

https://github.com/intel/multus-cni/pull/238/files

**Comment by kahou82** [comment]
@dougbtv do you have pointer on how to build and deploy the binary? https://github.com/intel/multus-cni/blob/master/doc/development.md doesn't have a lot of info.

**Comment by dougbtv** [comment]
@kahou82 I think we have fixes in master that will help this, the line in question is here @ https://github.com/intel/multus-cni/blob/master/images/entrypoint.sh#L209

If you need to reopen this issue, please do! Thanks!
