### ISSUE TITLE
Does multus support calico as CRD 

### ISSUE THREAD

**Issue by shufanhao** [intel/multus-cni#321]
I have this case want to know whether multus support ? 

Pod should be assign two ip address belong to different subnet, one is 172.18.0.0/16, another is  192.168.0.0/16。The default network is flannel that assign 172.18.0.0/16, like [quickstart guid](https://github.com/intel/multus-cni/blob/master/doc/quickstart.md)。Another network plugin want to use calico to assign 192.168.0.0/16 network also want to run calico-node to make sure can learn 192.168.0.0/16 routes from different node.

**Comment by shufanhao** [comment]
I try this solution, but failed. 
Calico NetworkAttachmentDefinition defined is as below:
```
[root@c-sfnd3s2k-xrnvszdn ~]# kubectl get network-attachment-definitions -o yaml
apiVersion: v1
items:
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    creationTimestamp: "2019-05-15T12:27:49Z"
    generation: 1
    name: calico-conf
    namespace: default
    resourceVersion: "1197922"
    selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/default/network-attachment-definitions/calico-conf
    uid: da0fda90-770c-11e9-a4de-fa163e967a19
  spec:
    config: '{ "cniVersion": "0.3.0", "type": "calico", "log_level": "debug", "datastore_type":
      "kubernetes", "nodename": "192.168.1.79", "mtu": 1440, "ipam": { "type": "host-local",
      "subnet": "10.244.1.0/24" }, "kubernetes": { "kubeconfig": "/root/.kube/config"
      } }'
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
pod define is as below:

```
[root@c-sfnd3s2k-xrnvszdn ~]# cat samplepod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: calico-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
```
But fail to create this pod. I wonder that why "invlaid name calico-conf", have created it.

```
desc = Error: No such container: 7226fcf7a873afa1694d8f5564b71f3d6ff66e168db0e3897e8714f39c0f0083
  Warning  FailedCreatePodSandBox  2m9s (x63 over 29m)  kubelet, 192.168.1.79  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "061e09cee96467d36ea6ab1cd413f0f8ca0b4787d3bae00bdfc281a51e358e81" network for pod "samplepod": NetworkPlugin cni failed to set up pod "samplepod_default" network: Multus: Err adding pod to network "calico-conf": Multus: error in invoke Delegate add - "calico": Invalid name calico-conf
```

**Comment by dougbtv** [comment]
We have a reference deployments repo as part of the network plumbing working group, and recently a calico example was submitted there, take a look and see if it has any examples that work for you: https://github.com/K8sNetworkPlumbingWG/reference-deployment/pull/1

If not, let's come up with one and we'll add to the reference deployments repo.

**Comment by dcbw** [comment]
@shufanhao also, I believe the "Invalid name calico-conf" comes from calico itself. Perhaps Calico doesn't like the network name? Multus will ensure that hte CRD object name is sent as the CNI JSON config name for consistency.

**Comment by shufanhao** [comment]
@dcbw Thanks for much. I fix it. It work now.

**Comment by dougbtv** [comment]
@shufanhao -- any chance you can add some documentation or reference to the reference deployment git repo as referenced above, we'd really appreciate it!

**Comment by s1061123** [comment]
Reference deployment git repo: https://github.com/K8sNetworkPlumbingWG/reference-deployment
