### ISSUE TITLE
CoreDNS stuck in pending state

### ISSUE THREAD

**Issue by msherif4** [intel/multus-cni#322]
There seems to be a recent issue with multus I can't get the master in Ready state , CoreDNS seems to be stuck in pending state forever 

I have been using the steps in the quick start to get it running
 git clone https://github.com/intel/multus-cni.git  
 kubectl apply -f $HOME/multus-cni/images/multus-daemonset.yml

kubectl get pods -n kube-system
NAME                             READY   STATUS    RESTARTS   AGE
coredns-fb8b8dccf-clvcp          0/1     Pending   0          15m
coredns-fb8b8dccf-kmcf4          0/1     Pending   0          15m
etcd-master                      1/1     Running   0          14m
kube-apiserver-master            1/1     Running   0          15m
kube-controller-manager-master   1/1     Running   0          15m
kube-multus-ds-amd64-8d5z9       1/1     Running   1          15m
kube-multus-ds-amd64-vs52v       1/1     Running   1          15m
kube-proxy-r9rzx                 1/1     Running   0          15m
kube-proxy-zfrwd                 1/1     Running   0          15m
kube-scheduler-master            1/1     Running   0          14m

also the multus conf file isn't created 
ls -la /etc/cni/net.d/
total 12
drwxr-xr-x 3 root root 4096 May 20 08:35 .
drwxr-xr-x 3 root root 4096 May 20 06:00 ..
drwxr-xr-x 2 root root 4096 May 20 08:36 multus.d
any idea what has been changed ?

Thanks!!

**Comment by msherif4** [comment]
am I the only one seeing this issue can anyone let me know if latest code can bring up k8s cluster fine ?

**Comment by s1061123** [comment]
Before apply `multus-daemonset.yaml`, you need to setup any CNI plugin for cluster network, like flannel, weave or others because multus-cni is just a meta plugin and does not provide any actual network for kubernetes.

So could you please install CNI plugin first (for your cluster network) and then apply multus-daemonset.yaml to your cluster?

**Comment by s1061123** [comment]
Hi @msherif4 is there any update on the issue?

**Comment by msherif4** [comment]
Hi s1961123 
Thanks for your reply I need to get multus with SRIOV CNI to be able to deploy vNF with DPDK to have a good reference for such deployment ?
