### ISSUE TITLE
Multus IP resource leakage after node reboot

### ISSUE THREAD

**Issue by maximshd** [intel/multus-cni#323]
**What happend**:
Multus doesn't invoke cmdDel execution to delegates after node reboot. 
After node reboot, Multus receives requests from kubelet to delete orphaned IP resources and starts to execute cmdDel func with next input parameters:
```
[debug] cmdDel: &{6ec1bafe874f6fc03391709743cb8b1247c759ab716d7a3f0f8b764a98eff256  eth0 IgnoreUnknown=1;K8S_POD_NAMESPACE=kube-system;K8S_POD_NAME=kube-sriov-device-plugin-hggm6;K8S_POD_INFRA_CONTAINER_ID=6ec1bafe874f6fc03391709743cb8b1247c759ab716d7a3f0f8b764a98eff256 /opt/cni/bin [123 34 99 110 105 86 101 114 115 105 111 110 34 58 34 34 44 34 100 101 108 101 103 97 116 101 115 34 58 91 123 34 99 110 105 86 101 114 115 105 111 110 34 58 34 48 46 51 46 49 34 44 34 110 97 109 101 34 58 34 99 110 105 48 34 44 34 112 108 117 103 105 110 115 34 58 91 123 34 100 101 108 101 103 97 116 101 34 58 123 34 102 111 114 99 101 65 100 100 114 101 115 115 34 58 116 114 117 101 44 34 104 97 105 114 112 105 110 77 111 100 101 34 58 116 114 117 101 44 34 105 115 68 101 102 97 117 108 116 71 97 116 101 119 97 121 34 58 116 114 117 101 125 44 34 116 121 112 101 34 58 34 102 108 97 110 110 101 108 34 125 44 123 34 99 97 112 97 98 105 108 105 116 105 101 115 34 58 123 34 112 111 114 116 77 97 112 112 105 110 103 115 34 58 116 114 117 101 125 44 34 116 121 112 101 34 58 34 112 111 114 116 109 97 112 34 125 93 125 93 44 34 107 117 98 101 99 111 110 102 105 103 34 58 34 47 101 116 99 47 99 110 105 47 110 101 116 46 100 47 109 117 108 116 117 115 46 100 47 109 117 108 116 117 115 46 107 117 98 101 99 111 110 102 105 103 34 44 34 108 111 103 70 105 108 101 34 58 34 47 118 97 114 47 108 111 103 47 109 117 108 116 117 115 46 108 111 103 34 44 34 108 111 103 76 101 118 101 108 34 58 34 100 101 98 117 103 34 44 34 110 97 109 101 34 58 34 109 117 108 116 117 115 45 99 110 105 45 110 101 116 119 111 114 107 34 44 34 116 121 112 101 34 58 34 109 117 108 116 117 115 34 125]}, <nil>, <nil>
```
According to the code, Multus will just return nill if net namespace is empty string
https://github.com/intel/multus-cni/blob/v3.2/multus/multus.go#L426

As a result, we have IP resources leakage for primary and secondary delegates.
As I understood, such behavior was introduced intentionally after this pull request https://github.com/intel/multus-cni/pull/120

I am expecting that cni plugin would try to perform full resource deletion even when network namespace for pod doesn't exist anymore.

**How to reproduce it (as minimally and precisely as possible)**:
Reboot the node with pods 

- Multus version v.3.2 
- Kubernetes version (use `kubectl version`): v.1.12.7
- Primary CNI for Kubernetes cluster: flannel

**Comment by maximshd** [comment]
Hi, @s1061123 ,
Did you have a chance to take a look on this problem? 
I have already tested custom multus version which invoke delPlugins() func even when Netns is empty. 
```
    rt := types.CreateCNIRuntimeConf(args, k8sArgs, "", in.RuntimeConfig)

	if args.Netns == "" {
		logging.Debugf("Multus: Netns for container is empty, try to clean up network resources")
		return delPlugins(exec, args.IfName, in.Delegates, len(in.Delegates)-1, rt, in.BinDir)
	}
```
Everything looks good but maybe you will notice some side-effects of such change.
Thanks!

**Comment by s1061123** [comment]
@maximshd ,
Thank you for your additional information with candidate fix!
I am investigating it more and will update this ticket.

**Comment by s1061123** [comment]
@maximshd This issue is fixed in latest (snapshot).
https://github.com/intel/multus-cni/pull/269

The latest multus invokes DEL of delegated CNI plugin to cleanup the resources even though target network namespace is already removed (= not found at that time).

**Comment by maximshd** [comment]
Hi @s1061123 ,

Seems like I observed a little bit different issue. For my case, cmdDel() returns with nil just after the first namespace verification from passed skel.CmdArgs argument in this block of code:
https://github.com/intel/multus-cni/blob/master/multus/multus.go#L426-L428

And the same behavior persists even in the latest master version.

**Comment by s1061123** [comment]
hmm.. let me investigate it.
