### ISSUE TITLE
Multi-Host Network Across Worker Nodes

### ISSUE THREAD

**Issue by infinitydon** [intel/multus-cni#324]
Hello,

I am trying to create a set of network subnets that will be available to all the worker nodes. An example:

net1 with IP 10.10.10.1/24 in POD1 (running in worker 1) should be able to ping net1 with IP 10.10.10.2/24 in POD1 (running in worker 2).

net2 with IP 10.10.20.1/24 in POD1 (running in worker 1) should be able to ping net2 with IP 10.10.20.2/24 in POD1 (running in worker 2).

N.B -- I will not be using SR-IOV.

BTW -- I tried using the vlan CNI but I noticed it does not allow multiple PODs with the same vlanId on the same worker node.

A sample architecture (from the knitter project):

![image](https://user-images.githubusercontent.com/6318992/58413573-6c6d2080-8079-11e9-9010-4bbe0d38f35d.png)

**Comment by SchSeba** [comment]
Hi @infinitydon just to be sure you have 3 interfaces on the machine or just one and you want to create a vlan for ctrl and for the media ?

**Comment by infinitydon** [comment]
Hi @SchSeba -- 3 distinct interfaces (unique subnets) on the machine .

**Comment by SchSeba** [comment]
so can you try to use the macvlan plugin I think it will provide everything you need.

**Comment by SchSeba** [comment]
if you have 3 different interfaces why you need the vlan separation?

**Comment by infinitydon** [comment]
With mac-vlan, PODs on different worker nodes can't ping one another..

I only mentioned using the VLAN method as an alternative but like I said it seems not to work..

An example of what I want to achieve is that all PODs on the media network should be able to ping one another irrespective of their worker nodes.

**Comment by dougbtv** [comment]
Hey @infinitydon -- could you provide the configs that you're currently using?

And then we'll try to come up with some changes, or an example. Sounds like you're really close.

**Comment by infinitydon** [comment]
@dougbtv -- I was able to achieve this aim eventually with the DANM project.

But what I want to setup basically is to create a second interface across a deployment with a central IP allocation scheme (each POD irrespective of the worker node host will have a unique IP and must be reachable).

The diagram I uploaded gives a better picture..

**Comment by MohammedNoureldin** [comment]
Is it working at all? I see nobody mentioned any solution of this issue.

https://github.com/k8snetworkplumbingwg/multus-cni/issues/983
