### ISSUE TITLE
Latest k8s w/crio does not support current multus daemonset script.

### ISSUE THREAD

**Issue by s1061123** [intel/multus-cni#325]
**What happend**:
Kubernetes with crio (as far as I know, at least k8s ver 1.14 + cri-o-1.14.0-1.dev.rhaos4.2.git0b8a2df.el7.x86_64) does not allow to change CNI config file name. Once we put some config in CNI dir, kubelet seems to lock the filename. multus-daemonset.yml does not expect such stuff, hence we do not install multus cni by multus-daemonset.yaml
(1.12.6-1.rhaos4.0.git2f0cb0d.el7 does not have issue)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
- Primary CNI for Kubernetes cluster:
- OS (e.g. from /etc/os-release):
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by dcbw** [comment]
Is the problem that CRIO installs a default CNI config file somewhere? Or what is in the CRIO CNI config dir before multus starts?  Its default behavior to find the first file and hang onto it until the runtime restarts, mainly to ensure that we don't tear down pods that were created with a previous plugin, using config of the newly found plugin.  There are some CNI updates to handle that (cache the config/plugin type for use on DEL).

**Comment by s1061123** [comment]
Yeah, right. Currently multus-daemonset.yaml expects that if automatically the new CNI config is found then the new one is used once the new config file found, but current oci-cni lock on the CNI file. So only crio restart to reload the config file?

**Comment by rkamudhan** [comment]
@s1061123 @dcbw  Is this issue with CRIO ? Kubelet behavior is to pick the file from cni directory right ?

**Comment by s1061123** [comment]
The issue is comes from the change of cri-o CNI at oci-cni. not related to kubelet.

**Comment by s1061123** [comment]
In the latest cri-o case, we need to change entrypoint.sh to support

- create multus config that has same network name as previous based one
- delete previous config file (to notify to update network conf to crio)
