### ISSUE TITLE
support for other architectures  such  ppc64le golang packages

### ISSUE THREAD

**Issue by moshe010** [intel/multus-cni#334]
**What would you like to be added**:
support for other architectures  such  ppc64le golang packages
**Why is this needed**:
Currently the repo for golang [1] include only x86 rpms. Can we use repo that also have other architectures ? when need this for [2] 

[1] - https://mirror.go-repo.io/centos/7Server/
[2] -  https://github.com/intel/multus-cni/pull/306

**Comment by dougbtv** [comment]
Do we also need #305 issue to track as well?

**Comment by moshe010** [comment]
@Mmduh-483 why there are 2 PR for the multi arch support (https://github.com/intel/multus-cni/pull/306, https://github.com/intel/multus-cni/issues/305) ?

**Comment by Mmduh-483** [comment]
#305 is the issue and #306 is the PR

**Comment by s1061123** [comment]
closed because now ppc64le and arm64 are supported.
