### ISSUE TITLE
cniVersion field missing from 00-multus.conf generated by multus DaemonSet

### ISSUE THREAD

**Issue by Cynerva** [intel/multus-cni#335]
**What happend**:

When using the multus DaemonSet from [here](https://github.com/intel/multus-cni/blob/e723aabca8792ddd181167660e252a127a81b073/images/multus-daemonset.yml), the 00-multus.conf file that was generated had no cniVersion field. As a result, I encountered the following issue from containerd: https://github.com/containerd/containerd/issues/2540

**What you expected to happen**:

Generated 00-multus.conf includes a cniVersion field so Multus can work with containerd.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy Kubernetes with a CNI base network (e.g. calico).
2. Deploy the multus DaemonSet into Kubernetes.
3. Look at /etc/cni/net.d/00-multus.conf on the Kubernetes nodes.

**Anything else we need to know?**:

A workaround is to manually edit 00-multus.conf after it is created, adding `"cniVersion": "0.3.1"` as a top-level field. Doing this resolved my issue with containerd.

**Environment**:

- Multus version: nfvpe/multus:v3.2
- Kubernetes version: v1.14.2
- Primary CNI for Kubernetes cluster: Calico v3.6
- OS: Ubuntu 18.04.2 LTS
- File of '/etc/cni/net.d/'

/etc/cni/net.d/00-multus.conf:
```
{ "name": "multus-cni-network", "type": "multus", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "calico-k8s-network", "cniVersion": "0.3.1", "plugins": [ { "type": "calico", "etcd_endpoints": "https://10.88.0.14:2379,https://10.88.0.15:2379,https://10.88.0.9:2379", "etcd_key_file": "/opt/calicoctl/etcd-key", "etcd_cert_file": "/opt/calicoctl/etcd-cert", "etcd_ca_cert_file": "/opt/calicoctl/etcd-ca", "log_level": "info", "ipam": { "type": "calico-ipam" }, "policy": { "type": "k8s" }, "kubernetes": { "kubeconfig": "/root/cdk/kubeconfig" } }, { "type": "portmap", "capabilities": {"portMappings": true}, "snat": true } ] } ] }
```

/etc/cni/net.d/10-calico.conflist:
```
{
  "name": "calico-k8s-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "etcd_endpoints": "https://10.88.0.14:2379,https://10.88.0.15:2379,https://10.88.0.9:2379",
      "etcd_key_file": "/opt/calicoctl/etcd-key",
      "etcd_cert_file": "/opt/calicoctl/etcd-cert",
      "etcd_ca_cert_file": "/opt/calicoctl/etcd-ca",
      "log_level": "info",
      "ipam": {
          "type": "calico-ipam"
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "kubeconfig": "/root/cdk/kubeconfig"
      }
    },
    {
      "type": "portmap",
      "capabilities": {"portMappings": true},
      "snat": true
    }
  ]
}
```
- File of '/etc/cni/multus/net.d'

Contains `multus.kubeconfig` file, nothing else.

- NetworkAttachment info: None created.
- Target pod yaml info: n/a

**Comment by s1061123** [comment]
@Cynerva,

The latest multus has '--cni-version' option to add "cniVersion" in generated CNI conf.
So please add "--cni-version=0.3.1" in your multus-daemonset.yml and test it?
```
        args:
        - "--multus-conf-file=auto"
        - "--cni-version=0.3.1"

```

**Comment by Cynerva** [comment]
Thanks. Adding the `--cni-version=0.3.1` option appears to do nothing with the nfvpe/multus:v3.2 image. But if I change the image to nfvpe/multus:latest, then it works.

Two follow-up questions:
1. When will there be a stable release of nfvpe/multus that includes the `--cni-version` option?
2. Will `--cni-version=0.3.1` be added to the [multus-daemonset.yml](https://github.com/intel/multus-cni/blob/1f8b44c575ee60f86ec99decd008a2328586952d/images/multus-daemonset.yml) file in this repo?

**Comment by s1061123** [comment]
@Cynerva 
1. When will there be a stable release of nfvpe/multus that includes the --cni-version option?
 -> it will be appeared in next stable release.
1. Will --cni-version=0.3.1 be added to the multus-daemonset.yml file in this repo?
 -> for now, not planning to add '--cni-version' in default (i.e. repo's multus-daemonset.yml).

Could you please close the issue if you don't mind it?

**Comment by Cynerva** [comment]
Thanks. Sure, I'll close it.

> it will be appeared in next stable release.

Any info on when that might occur?
