### ISSUE TITLE
Does multus have any DNS solution?

### ISSUE THREAD

**Issue by mJace** [intel/multus-cni#340]
As to title.  
Does multus cni have any dns solution? 
For example, I have 2 pods and each of them ware attached with sriov vf by sriov cni using multus.
Both IP address of sriov nic in the pods are assigned according the same net-attach-def using ipam hostLocal plugin.
For now, If podA want to connect to podB via sriov vf.  I have to check podB's sriov nic address first.
Is there a more smart/efficient way to do this?

Thank you.

**Comment by s1061123** [comment]
Multus is just a meta plugin and all network feature should be done in delegating CNI plugin, so multus does not have any IPAM related feature (including DNS) for now.
