### ISSUE TITLE
Can't define device resource on cluster network when using delegates

### ISSUE THREAD

**Issue by moshe010** [intel/multus-cni#342]
When Using multus network attachment definition on cluster network we can specify the device resource by k8s.v1.cni.cncf.io/resourceName in the annothation.  When you use delegates syntax it is not possible. 

We have a use case that for a cluster network we need SR-IOV resource (for ovs offload) see [1]. 

It is expected that we can requested device resource for network with  network attachment definition and delegates. Currently is working only with network attachment 

[1] - https://github.com/ovn-org/ovn-kubernetes/pull/665

**Comment by SchSeba** [comment]
This PR will help you with that? 
https://github.com/intel/multus-cni/pull/268

Or you prefer something in the multus cni config file?

**Comment by moshe010** [comment]
@SchSeba, So today you can define the default cluster network in Pod annotations using v1.multus-cni.io/default-network and this works well when you use network attachment def, but if you use delegates (cni config) you can't do that.  Currently we have 2 ways to define the cni config and they are a bit different, This is why I opened issue https://github.com/intel/multus-cni/issues/343.

**Comment by s1061123** [comment]
Hi, as you mentioned before #343, user can use network-attachment-definition for cluster network in "clusterNetwork" in multus CNI config.

So in this issue, you mentioned that same feature with 'delegates', correct?
Is there any reason why you need it in 'delegates' configuration, not "clusterNetwork" config?

**Comment by dougbtv** [comment]
This is currently being discussed in the NPWG -- more information on meeting details and proposal can be found here @ https://www.google.com/url?q=https://docs.google.com/document/d/1oE93V3SgOGWJ4O1zeD1UmpeToa0ZiiO6LqRAmZBPFWM/edit&sa=D&ust=1586189710642000&usg=AOvVaw1u1JLNu85L2hP1t8C7BTdU
