### ISSUE TITLE
delegates vs network attachments 

### ISSUE THREAD

**Issue by moshe010** [intel/multus-cni#343]
Currently there are 2 ways to configure cluster network or add additional network. One why is using delegates and the second one is the network attachments. 
Do we want to keep these 2 ways in the future?

**Comment by s1061123** [comment]
Let me list up the current Pros/Cons from my thoughts (cons = opposite's pros, so omitted)

Delegates(Pros):

- Pure CNI SPEC notation
- Support non-k8s container runtime (still now!)

Network Attachments (Pros):

- Network attachments is cluster wide object, so easy to change to all nodes in cluster
- In some upgrade / migration, network attachments are very useful

**Comment by dougbtv** [comment]
Moshe thanks for the concerns on this one, we think there's not a lot of overhead for having both methods for now, so we'd like to keep them both as it's not a maintanance problem. But, happy to bring this up in the regularly maintainers meeting if you have further concerns for sure. Feel free to add to the agenda and join any time, agenda doc here: https://docs.google.com/document/d/17-vkuoObBFBb6feXNA7tjTaKr-rs8ea0VTnqvlEdCv8/edit#
