### ISSUE TITLE
How to assign different static IPs across pod replicas using multus.

### ISSUE THREAD

**Issue by DheerajKhajuria** [intel/multus-cni#346]
using multus with type "macvlan" and  IP assignment with help of IPM type "static" 

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-try3
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "team0",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }'

using a StatefulSet with two replicas

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
       k8s.v1.cni.cncf.io/networks: '[{ "name": "macvlan-conf-try3", "ips": "10.64.109.201/23" },{ "name": "macvlan-conf-try3", "ips": "10.64.109.202/23" }]'
    spec:
      containers:
      - name: nginx
        image: busybox
        ports:
        - containerPort: 22
          name: web
        command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']

		
with this deployment, both pods get the same IP address on additional interfaces.
Any idea of how can I assign different static IP address across the pod replica. Is there any CNI plugin available to do so.

**Comment by DheerajKhajuria** [comment]
Any help will be appreciated.

**Comment by s1061123** [comment]
@DheerajKhajuria for now, I don't have ideas for that. How about to use alternative CNI, such as [whereabouts](https://github.com/dougbtv/whereabouts)?

**Comment by DheerajKhajuria** [comment]
thanks for replying @s1061123.  Not sure whereabouts CNI provides static IP addresses across replica PODs  in statefulset deployment.
