### ISSUE TITLE
How to modify default route in multus?

### ISSUE THREAD

**Issue by piyushewkani** [intel/multus-cni#349]
Hi,

I have OpenShift 3.11 running on Red hat OpenStack 13. I have configured Multus v3.2 with Calico for pod networking. 

I am able to create a secondary nic on the pod using type ipvlan, it connects to a network which is externally routable. I would like to have this pod externally accessible and for which I need to modify the default route on the pod but I can't figure out a way to change this in the network attachment definition. 

I added routes in the CRD and also 'k8s.v1.cni.cncf.io/networks-default:' in the pod metadata annotation during creation, but these both options have no effect. 

Would appreciate if someone could help me with this! Thanks.

CRD:-
 `cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-test
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": "eth1",
      "ipam": {
        "type": "host-local",
        "ranges": [
          [
            {
              "subnet": "10.46.90.224/27",
              "rangeStart": "10.46.90.245",
              "rangeEnd": "10.46.90.254",
              "gateway": "10.46.90.225"
            }
          ]
        ],
        "routes": [
          { "dst": "0.0.0.0/0", "gw": "10.46.90.225" }
        ]
      }
    }'
EOF`

POD creation template:-
`cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: samplepod-ipvlan
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-test
    k8s.v1.cni.cncf.io/networks-default: ipvlan-test
spec:
  containers:
  - name: samplepod
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
EOF`

pod terminal :- 

![image](https://user-images.githubusercontent.com/53101479/61823079-a4e26e00-ae20-11e9-92df-82240ce5357a.png)

**Comment by s1061123** [comment]
Hi @piyushewkani 

For now, multus does not have any functionality to manipulate container routing table yet and we are proposing new features for K8s Networking Plumbing Working Group. So in the future, multus will take care of it, I hope.

BTW, there is CNI plugin to manipulate container's routing table, so you could use it to manipulate routing table. Just FYI. 
https://github.com/redhat-nfvpe/cni-route-override

**Comment by piyushewkani** [comment]
Hi @s1061123 

Thank you very much for your prompt response. Appreciate your help! 

One point I noticed for cni-route-override plugin is that it is verified with podman and crio. I am using docker as a container runtime engine in my set up. I tried to create a CRD based on this, but it had no effect on routing table of the pod. Is it because docker is not supported yet?

**Comment by piyushewkani** [comment]
@s1061123 

this is the specific error I am seeing;

`Multus: Err adding pod to network "ipvlan-test": Multus: error in invoke Conflist add - "ipvlan-test": error in getting result from AddNetworkList: failed to load netconf: json: cannot unmarshal string into Go struct field RouteOverrideConfig.flushroutes of type bool, failed to clean up sandbox container "9b9d01fb6fedb06d87ef884d3011a048e915aabe31aba03f4c758db0d5755f6b" network for pod "samplepod-ipvlan-default-route": NetworkPlugin cni failed to teardown pod "samplepod-ipvlan-default-route_piyush" network: Multus: error in invoke Delegate del - "": no plugin name provided]`

**Comment by tunicashashi** [comment]
hi @s1061123 

Is now default route supported from Multus to manipulate the container routing table ?

**Comment by s1061123** [comment]
Currently multus support to change default route by pod annotation.

See "4.1.2.1.9 “default-route” Default route selection for a particular attachment" in the following doc for the detail.

https://github.com/k8snetworkplumbingwg/multi-net-spec/blob/master/v1.1/%5Bv1.1%5D%20Kubernetes%20Network%20Custom%20Resource%20Definition%20De-facto%20Standard.pdf
