### ISSUE TITLE
netconf cache file shouldn't be deleted if delegate cni call failed in cmdDel 

### ISSUE THREAD

**Issue by jmf0526** [intel/multus-cni#355]
**What happend**:
I'm using multus 3.1 as k8s cni, calico as the underlying delegate cni.  Sometimes after the node reboot, some pod ip wouldn't be released in calico, causing ip leakage. 
After doing some investagtion, I found the root cause is that multus 3.1 delete the netconf cache (the files in /var/lib/cni/multus/) even if the first invocation of calico cmdDel failed (because of some calico problem), then the next time multus got called, it would wrongly return successs to kubelet without invoke calico cmdDel, beause it thinks that no cache file means the container network has already torn down.

code snippet of multus 3.1
`		netconfBytes, err := consumeScratchNetConf(args.ContainerID, in.CNIDir)`
`		if err != nil {`
`			if os.IsNotExist(err) {`
`				// Per spec should ignore error if resources are missing / already removed`
`				return nil`

**What you expected to happen**:
In cmdDel func, the netconf cache file should only be deleted if the invocation of the delegate cni succeed. 

**How to reproduce it (as minimally and precisely as possible)**:
1. use calco as the only delgate in multus net conf.

2. rename /opt/cni/bin/calico to /opt/cni/bin/calico_wrong to simulate the calico invocation failure.

3. delete a pod, the pod can be deleted, but its calico resource leaks.

**Anything else we need to know?**:
In the latest master branch code , it seems that multus would trying to  reassemble the delegate by combining the current config and pod annotation when the netconf cache file isn't present, the cmdDel would continue to execute.
https://github.com/intel/multus-cni/blob/master/multus/multus.go#L452
But cache file still go deleted if every time multus cmdDel got called.
https://github.com/intel/multus-cni/blob/master/multus/multus.go#L478

IMHO, this also has potential problems, if the pod is already deleted and the invocation of delegate cni failed, then the next time  multus got called, it can't got the delegate from pod annotation, causing delegate cni resource leakage.

**Environment**:

- Multus version 
3.1
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
- Primary CNI for Kubernetes cluster:
- OS (e.g. from /etc/os-release):
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by s1061123** [comment]
Hi,

This is not an issue because of following reasons:

1) Without multus cache, latest multus can create required information
In case of cluster network plugin (i.e master plugin), required information is in `/etc/cni/net.d/multus.conf` and latest multus can create required information at cmdDel().

2) Without multus, calico will leak resource.
Install k8s with calico (without multus), the leak is happen. (verified in my environment).
This is not multus issue, kubernetes issue as following:
https://github.com/kubernetes/kubernetes/issues/65943

**Comment by jmf0526** [comment]
> Hi,
> 
> This is not an issue because of following reasons:
> 
> 1. Without multus cache, latest multus can create required information
>    In case of cluster network plugin (i.e master plugin), required information is in `/etc/cni/net.d/multus.conf` and latest multus can create required information at cmdDel().

I might be wrong, but here is my concern:
 `/etc/cni/net.d/multus.conf` is just one half of the required information. Another half is in the pod `network-attchment` annotation, if the pod is deleted before kubelet tearing down sandbox network (in this case kubelet container GC is responsible for calling multus to tear down the network), it's impossible for multus to get the delegates in pod annotation (because the pod is already gone).
