### ISSUE TITLE
Multus cause Calico cannot work correctly when run K8S with containerd

### ISSUE THREAD

**Issue by LinShuicheng** [intel/multus-cni#356]
**What happend**:
Try to deploy Multus + Calico following below link. It could work first, but doesn't work when switch k8s container runtime from docker to containerd. calico-kube-controllers/coredns will stuck at IP allocation.
https://github.com/K8sNetworkPlumbingWG/reference-deployment/tree/master/multus-calico

controller-0:~$ kubectl get po -n kube-system -o wide
NAME                                       READY   STATUS              RESTARTS   AGE    IP              NODE           NOMINATED NODE   READINESS GATES
calico-kube-controllers-757ff97ff5-sqlnc   0/1     ContainerCreating   0          3m9s   <none>          controller-0   <none>           <none>
calico-node-xq8x8                          1/1     Running             0          76m    192.168.206.3   controller-0   <none>           <none>
coredns-5ffc5dfc87-mq9ww                   0/1     ContainerCreating   0          40m    <none>          controller-0   <none>           <none>

controller-0:~$ kubectl -n kube-system describe po calico-kube-controllers-757ff97ff5-sqlnc
Events:
  Type     Reason                  Age                   From                   Message
  ----     ------                  ----                  ----                   -------
  Normal   Scheduled               3m49s                 default-scheduler      Successfully assigned kube-system/calico-kube-controllers-757ff97ff5-sqlnc to controller-0
  Warning  FailedCreatePodSandBox  3m43s                 kubelet, controller-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "2cca2fdc26cd987726683f954c48688c845cdd6de1b635841b14ca015395d258": cannot convert: no valid IP addresses
  Warning  FailedCreatePodSandBox  3m37s                 kubelet, controller-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "44cab6fca8e39881bdb81cbf577a7f9d4d9f0b83089a6ac7f14183f96a4458f3": cannot convert: no valid IP addresses
  Warning  FailedCreatePodSandBox  3m31s                 kubelet, controller-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "7e9fcada023afc787806ba592ccbc25e1bdec87c3394c78c4b2949e707aecfb1": cannot convert: no valid IP addresses
  Warning  FailedCreatePodSandBox  3m25s                 kubelet, controller-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "9de8c151319b968b98842c93d661a46d985ba0c5f285ba17171455f81c063ba6": cannot convert: no valid IP addresses
  Warning  FailedCreatePodSandBox  3m19s                 kubelet, controller-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "02b245fbf91f0637cded3886cdcfe9436befd13cc2cbd4ff59ada2c0a5426b38": cannot convert: no valid IP addresses
  Warning  FailedCreatePodSandBox  3m12s                 kubelet, controller-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "fdbc7f320215fc2b76887013d9cf10245626b2d5735eaa44a54ffc86224170f7": cannot convert: no valid IP addresses
  Warning  FailedCreatePodSandBox  3m6s                  kubelet, controller-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "d713ae1b11f682db4c566f0a0f15c5cf4e9fb215d3db248f1c42b4a8bbdd5732": cannot convert: no valid IP addresses
  Warning  FailedCreatePodSandBox  3m                    kubelet, controller-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "af7008b64e369c5ea30556108f194f52d3cd93486ef0370e5cba342049039fbc": cannot convert: no valid IP addresses
  Warning  FailedCreatePodSandBox  2m54s                 kubelet, controller-0  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "cf62dcfb279b731f84b91e148fb490fd29bf266e07db530c71846c63a0ffe89c": cannot convert: no valid IP addresses
  Warning  FailedCreatePodSandBox  75s (x16 over 2m48s)  kubelet, controller-0  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "2734cd22058261a7f57d5500e47a1071e62cee9ec6b5397a01121613337c22bb": cannot convert: no valid IP addresses

Also there is error in daemon.log:
2019-08-06T08:44:24.518 controller-0 containerd[109360]: info 2019-08-06 08:44:24.517 [INFO][297117] k8s.go 420: Wrote updated endpoint to datastore ContainerID="f225b3a306cc51f757c9f7280f34ee647f8a175acb79ebf918341fd3d27b2fa3" Namespace="kube-system" Pod="coredns-5ffc5dfc87-mq9ww" WorkloadEndpoint="controller--0-k8s-coredns--5ffc5dfc87--mq9ww-eth0"
2019-08-06T08:44:24.529 controller-0 containerd[109360]: info 2019-08-06T08:44:24Z [verbose] Add: kube-system:coredns-5ffc5dfc87-mq9ww:chain:eth0 {"cniVersion":"0.3.0","interfaces":[{"name":"cali60a2b8aaa42"}],"ips":[{"version":"4","address":"172.16.193.18/32"}],"dns":{}}
2019-08-06T08:44:24.537 controller-0 containerd[109360]: info time="2019-08-06T08:44:24.537275833Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:coredns-5ffc5dfc87-mq9ww,Uid:49b86b67-b821-11e9-8ec1-5254008c3e56,Namespace:kube-system,Attempt:0,} failed, error" error="failed to setup network for sandbox "f225b3a306cc51f757c9f7280f34ee647f8a175acb79ebf918341fd3d27b2fa3": cannot convert: no valid IP addresses"
2019-08-06T08:44:24.537 controller-0 kubelet[109863]: info E0806 08:44:24.537428  109863 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to setup network for sandbox "f225b3a306cc51f757c9f7280f34ee647f8a175acb79ebf918341fd3d27b2fa3": cannot convert: no valid IP addresses
2019-08-06T08:44:24.537 controller-0 kubelet[109863]: info E0806 08:44:24.537465  109863 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "coredns-5ffc5dfc87-mq9ww_kube-system(49b86b67-b821-11e9-8ec1-5254008c3e56)" failed: rpc error: code = Unknown desc = failed to setup network for sandbox "f225b3a306cc51f757c9f7280f34ee647f8a175acb79ebf918341fd3d27b2fa3": cannot convert: no valid IP addresses
2019-08-06T08:44:24.537 controller-0 kubelet[109863]: info E0806 08:44:24.537477  109863 kuberuntime_manager.go:662] createPodSandbox for pod "coredns-5ffc5dfc87-mq9ww_kube-system(49b86b67-b821-11e9-8ec1-5254008c3e56)" failed: rpc error: code = Unknown desc = failed to setup network for sandbox "f225b3a306cc51f757c9f7280f34ee647f8a175acb79ebf918341fd3d27b2fa3": cannot convert: no valid IP addresses
2019-08-06T08:44:24.537 controller-0 kubelet[109863]: info E0806 08:44:24.537519  109863 pod_workers.go:190] Error syncing pod 49b86b67-b821-11e9-8ec1-5254008c3e56 ("coredns-5ffc5dfc87-mq9ww_kube-system(49b86b67-b821-11e9-8ec1-5254008c3e56)"), skipping: failed to "CreatePodSandbox" for "coredns-5ffc5dfc87-mq9ww_kube-system(49b86b67-b821-11e9-8ec1-5254008c3e56)" with CreatePodSandboxError: "CreatePodSandbox for pod \"coredns-5ffc5dfc87-mq9ww_kube-system(49b86b67-b821-11e9-8ec1-5254008c3e56)\" failed: rpc error: code = Unknown desc = failed to setup network for sandbox \"f225b3a306cc51f757c9f7280f34ee647f8a175acb79ebf918341fd3d27b2fa3\": cannot convert: no valid IP addresses"

here is the configuration file:
controller-0:/etc/cni/net.d# ls
05-multus.conf  10-calico.conflist  calico-kubeconfig  multus.d
controller-0:/etc/cni/net.d# cat 05-multus.conf
{
  "name": "multus-cni-network",
  "type": "multus",
  "logLevel": "debug",
  "logFile": "/var/log/multus.log",
  "delegates": [
    {
      "cniVersion": "0.3.0",
      "name": "chain",
      "plugins": [
        {
          "cniVersion": "0.3.0",
          "name": "k8s-pod-network",
          "type": "calico",
          "masterplugin": true,
          "log_level": "info",
          "datastore_type": "kubernetes",
          "nodename": "controller-0",
          "mtu": 1500,
          "ipam": {
              "type": "calico-ipam",
              "assign_ipv4": "true",
              "assign_ipv6": "false"
          },
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
          }
        },
        {
          "name": "sysctl-tuning",
          "type": "tuning",
          "sysctl": {
            "net.ipv4.tcp_keepalive_intvl": "1",
            "net.ipv4.tcp_keepalive_probes": "5",
            "net.ipv4.tcp_keepalive_time": "5"
          }
        }
      ]
    }
  ],
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
}
controller-0:/etc/cni/net.d# cat 10-calico.conflist
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.0",
  "plugins": [
    {
      "type": "calico",
      "log_level": "info",
      "datastore_type": "kubernetes",
      "nodename": "controller-0",
      "mtu": 1440,
      "ipam": {
        "type": "calico-ipam",
        "assign_ipv4": "true",
        "assign_ipv6": "false"
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    }
  ]
}

**What you expected to happen**:
If Multus is disabled, Calico could run successfully. Also if remove 05-multus.conf in /etc/cni/net.d, issue also doesn't occur.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy kubernetes with containerd
https://github.com/containerd/cri/blob/master/contrib/ansible/README.md#kubernetes-cluster-with-containerd
Apply Calico and Multus:
https://github.com/K8sNetworkPlumbingWG/reference-deployment/tree/master/multus-calico

**Anything else we need to know?**:

**Environment**:
OS: CentOS 7.6

- Multus version 
v3.2
  image path and image ID (from 'docker images')
nfvpe/multus              v3.2                          45da14a16accc       179MB
calico/cni                v3.6.2                        14f1e7286a2dc       27.5MB
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"archive", BuildDate:"2019-08-05T19:04:14Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Primary CNI for Kubernetes cluster:
Calico

- OS (e.g. from /etc/os-release):
CentOS 7.6
- File of '/etc/cni/net.d/'
controller-0:/etc/cni/net.d# ls /etc/cni/net.d/
05-multus.conf  10-calico.conflist  calico-kubeconfig  multus.d

- File of '/etc/cni/multus/net.d'
None
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
controller-0:/etc/cni/net.d# kubectl get net-attach-def -o yaml
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)

controller-0:/etc/cni/net.d# kubectl -n kube-system get pod calico-kube-controllers-757ff97ff5-sqlnc -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 172.16.194.157/32
  creationTimestamp: "2019-08-06T08:45:06Z"
  generateName: calico-kube-controllers-757ff97ff5-
  labels:
    k8s-app: calico-kube-controllers
    pod-template-hash: 757ff97ff5
  name: calico-kube-controllers-757ff97ff5-sqlnc
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: calico-kube-controllers-757ff97ff5
    uid: 36147696-b81c-11e9-8ec1-5254008c3e56
  resourceVersion: "18244"
  selfLink: /api/v1/namespaces/kube-system/pods/calico-kube-controllers-757ff97ff5-sqlnc
  uid: 7d46e0c0-b826-11e9-8ec1-5254008c3e56
spec:
  containers:
  - env:
    - name: ENABLED_CONTROLLERS
      value: node
    - name: DATASTORE_TYPE
      value: kubernetes
    image: edgehost01.sh.intel.com:5000/calico/kube-controllers:v3.6.2
    imagePullPolicy: IfNotPresent
    name: calico-kube-controllers
    readinessProbe:
      exec:
        command:
        - /usr/bin/check-status
        - -r
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: calico-kube-controllers-token-qg7f6
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: controller-0
  nodeSelector:
    beta.kubernetes.io/os: linux
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: calico-kube-controllers
  serviceAccountName: calico-kube-controllers
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 30
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 30
  volumes:
  - name: calico-kube-controllers-token-qg7f6
    secret:
      defaultMode: 420
      secretName: calico-kube-controllers-token-qg7f6
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-08-06T08:45:06Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-08-06T08:45:06Z"
    message: 'containers with unready status: [calico-kube-controllers]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-08-06T08:45:06Z"
    message: 'containers with unready status: [calico-kube-controllers]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-08-06T08:45:06Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: edgehost01.sh.intel.com:5000/calico/kube-controllers:v3.6.2
    imageID: ""
    lastState: {}
    name: calico-kube-controllers
    ready: false
    restartCount: 0
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 192.168.206.3
  phase: Pending
  qosClass: BestEffort
  startTime: "2019-08-06T08:45:06Z"

- Other log outputs (if you use multus logging)

**Comment by LinShuicheng** [comment]
One more finding today, if I change the cniVersion parameter in 05-multus.conf from "0.3.0" to "0.2.0", then issue also gone.
The major change for 0.3.0 is "plugin chaining" support.
tag              | spec permalink    | major changes
spec-v0.3.0 | spec at v0.3.0       | rich result type, plugin chaining
spec-v0.2.0 | spec at v0.2.0       | VERSION command

Anyone could help answer whether it is containerd issue or Multus issue?
Thanks.

  "delegates": [
    {
      "cniVersion": "0.2.0",   //changed from 0.3.0
      "name": "chain",

**Comment by s1061123** [comment]
If you don't change multus binary and works fine, issue should be in containerd or in calico.
In case of config in "delegates", multus just get the config from runtime (i.e. containerd in the case) and pass it to CNI plugin (i.e. calico in the case).

**Comment by shawnho1018** [comment]
Hello, I encountered the same issue on my kubernetes cluster (v.1.15.3), installed with containerd. I am also using multus and calico yaml from: https://github.com/K8sNetworkPlumbingWG/reference-deployment/tree/master/multus-calico .

**Comment by LinShuicheng** [comment]
@shawnho1018 , please check https://github.com/containerd/containerd/issues/3566

**Comment by shawnho1018** [comment]
Lin…Thanks! Will give it a try~

--
Tzunghsien (Shawn) Ho

Solution Architect @ VMware
+886-920-201-322
hos@vmware.com<mailto:hos@vmware.com>
[signature_1315195585]
