### ISSUE TITLE
Getting error in deploying multus-daemonset

### ISSUE THREAD

**Issue by Sisir-Chowdhury** [intel/multus-cni#358]
I'm trying to setup a K8s Cluster (3 Node - 1 Master and 2 Workers)  with MULTUS CNI Broker, something like this - A K8s POD will have 3 interfaces (net0, net1, eth0) where net0 might be part of Flannel Network, net1 might be part of Calico . and eth0 connected to K8s Control Plane - K8s Master Node etc. Is it possible ? 
I just installed K8s but not formed the cluster - trying below command at the designated master node and getting the following error.

```
$ git clone https://github.com/intel/multus-cni.git && cd multus-cni
$ /multus-cni$ cat ./images/{multus-daemonset.yml,flannel-daemonset.yml} | kubectl apply -f -
cat: ./images/flannel-daemonset.yml: No such file or directory
unable to recognize "STDIN": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "STDIN": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "STDIN": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "STDIN": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "STDIN": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "STDIN": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
unable to recognize "STDIN": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
```

**Comment by dougbtv** [comment]
Hey @Sisir-Chowdhury -- I think you might have some out of date instructions...

We now just do a:

```
cat ./images/multus-daemonset.yml | kubectl apply -f -
```

(no more flannel-daemonset.yml in the Multus github repo)

This assumes that you already have a default network CNI plugin installed (like Flannel) which is fairly easy to create yourself.

The method I usually use is that I apply [this Flannel YAML for a daemonset](https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml) and then do the Multus steps.

**Comment by Sisir-Chowdhury** [comment]
Thanks @dougbtv .

I got it working like this: cat ./reference-deployment/multus-flannel/{multus-daemonset.yml,flannel-daemonset.yml} | kubectl apply -f -

**Comment by Sisir-Chowdhury** [comment]
After this I am trying to create network attachments for multiple networks.. Something like this: 
****************************************************************************
* STEP-1: Create network attachment definition
*         for additional Network Interfaces (net1, net2, etc.) at the Pod
*         Default will be: lo, eth0
****************************************************************************

cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-1
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": "ens160",
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                         "subnet": "18.18.0.0/16",
                         "rangeStart": "18.18.1.20",
                         "rangeEnd": "18.18.3.50",
                         "gateway": "18.18.0.254"
                    } ]
                ]
            }
        }'
EOF

This works  but my Question is: what is ` "master": "ens160",` in the above YML Spec ? I believe that's the physical NIC of the Worker Node but if I  have multiple worker nodes , how will that work ?
