### ISSUE TITLE
interfaceRequest annotation key is ignored

### ISSUE THREAD

**Issue by defo89** [intel/multus-cni#360]
**What happened**:
Multus 3.2 and 3.3-tp seem to ignore `interfaceRequest` annotation key.
It was working with 3.1.

**What you expected to happen**:
Interface device name is set to one specified in `interfaceRequest`.

E.g. `vlan101`.

But the name is actually `net2`:

```
root@<container>:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if510: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default
    link/ether <some-mac> brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet x.x.x.x/23 brd x.x.x.x scope global eth0
       valid_lft forever preferred_lft forever
4: net2@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default
    link/ether <some-mac> brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet x.x.x.x/26 brd x.x.x.x scope global net2
       valid_lft forever preferred_lft forever
```

**How to reproduce it**:

```
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name": "nad-name-1", "interfaceRequest":"vlan101" }]'
```

**How to fix it**:

```
      annotations:
        k8s.v1.cni.cncf.io/networks=nad-name-1@vlan101
```

**Environment**:

- Multus version: v3.2
- Kubernetes version (use `kubectl version`): 1.8.15
- Primary CNI for Kubernetes cluster: bridge
- OS (e.g. from /etc/os-release): Container Linux 2135.5.0

**Comment by s1061123** [comment]
To track on Kubernetes NPWG standards, we `interfaceRequest` is renamed to `interface`, hence v3.2/3.3 does not have it.

Could you please `interface` instead of `interfaceRequest`?

**Comment by defo89** [comment]
Thanks @s1061123!  `interface` works as well
