### ISSUE TITLE
Multus: Err adding pod to network

### ISSUE THREAD

**Issue by helioaymoto** [intel/multus-cni#386]
Hi,
I am new on multus-cni and I have followed the instruction on quick start guide (https://github.com/intel/multus-cni/blob/master/doc/quickstart.md)...
I was able sucesfully add the network-attachement-definition, but it is failing when i tried to create a POD with the following log message:

>  Warning  FailedCreatePodSandBox  24m                    kubelet, kube-2    Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "7caa536a060bf581160dfade36a0a48ad13dff796ea6e281682e73fe3d1b7dc2" network for pod "samplepod": NetworkPlugin cni failed to set up pod "samplepod_default" network: Multus: Err adding pod to network "macvlan-conf": Multus: error in invoke Delegate add - "macvlan": failed to find plugin "macvlan" in path [/opt/cni/bin], failed to clean up sandbox container "7caa536a060bf581160dfade36a0a48ad13dff796ea6e281682e73fe3d1b7dc2" network for pod "samplepod": NetworkPlugin cni failed to teardown pod "samplepod_default" network: Multus: error in invoke Delegate del - "macvlan": failed to find plugin "macvlan" in path [/opt/cni/bin]]

---------------
1. The daemon set are running fine in my 2 workers:

> [helio@centos ~]$ kubectl get pods --all-namespaces | grep -i multus
kube-system         kube-multus-ds-amd64-5x2nl                                1/1     Running             1          16h
kube-system         kube-multus-ds-amd64-fm6gn                                1/1     Running             1          16h

2. The binary was deployed by the daemon set in the workers nodes:

> [helio@kube-1 ~]$ cd /opt/cni/bin
[helio@kube-1 bin]$ ls -ltr
total 102920
-rwxr-xr-x 1 root root 28190144 Sep 27 08:57 calico
-rwxr-xr-x 1 root root 27444416 Sep 27 08:57 calico-ipam
-rwxr-xr-x 1 root root  2856252 Sep 27 08:57 flannel
-rwxr-xr-x 1 root root  3036768 Sep 27 08:57 host-local
-rwxr-xr-x 1 root root  3084347 Sep 27 08:57 loopback
-rwxr-xr-x 1 root root  3550877 Sep 27 08:57 portmap
-rwxr-xr-x 1 root root  2850029 Sep 27 08:57 tuning
-rwxr-xr-x 1 root root 34359288 Sep 27 08:57 multus

3. The resource:

> [helio@centos ~]$ kubectl get network-attachment-definitions
NAME           AGE
macvlan-conf   16h

> [helio@centos ~]$ kubectl describe network-attachment-definition macvlan-conf
Name:         macvlan-conf
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  k8s.cni.cncf.io/v1
Kind:         NetworkAttachmentDefinition
Metadata:
  Creation Timestamp:  2019-09-26T19:40:51Z
  Generation:          1
  Resource Version:    870345
  Self Link:           /apis/k8s.cni.cncf.io/v1/namespaces/default/network-attachment-definitions/macvlan-conf
  UID:                 8bed2e2b-e095-11e9-b3f0-000c29fd6c86
Spec:
  Config:  { "cniVersion": "0.3.0", "type": "macvlan", **"master": "ens33"**, "mode": "bridge", "ipam": { "type": "host-local", "subnet": "192.168.1.0/24", "rangeStart": "192.168.1.30", "rangeEnd": "192.168.1.79", "routes": [ { "dst": "0.0.0.0/0" } ], "gateway": "192.168.1.1" } }
Events:    <none>

4. The "master" is pointing to my physicall NIC:
> 2: **ens33**: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:72:c1:aa brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.181/24 brd 192.168.1.255 scope global noprefixroute ens33
       valid_lft forever preferred_lft forever

5. Additional information:
> [helio@centos ~]$ kubectl describe crd network-attachment-definition
Name:         network-attachment-definitions.k8s.cni.cncf.io
Namespace:
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"name":"network-attachment-def...
API Version:  apiextensions.k8s.io/v1beta1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2019-09-26T19:27:41Z
  Generation:          1
  Resource Version:    869078
  Self Link:           /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/network-attachment-definitions.k8s.cni.cncf.io
  UID:                 b52c6561-e093-11e9-b3f0-000c29fd6c86
Spec:
  Conversion:
    Strategy:  None
  Group:       k8s.cni.cncf.io
  Names:
    Kind:       NetworkAttachmentDefinition
    List Kind:  NetworkAttachmentDefinitionList
    Plural:     network-attachment-definitions
    Short Names:
      net-attach-def
    Singular:  network-attachment-definition
  Scope:       Namespaced
  Validation:
    openAPIV3Schema:
      Properties:
        Spec:
          Properties:
            Config:
              Type:  string
  Version:           v1
  Versions:
    Name:     v1
    Served:   true
    Storage:  true
Status:
  Accepted Names:
    Kind:       NetworkAttachmentDefinition
    List Kind:  NetworkAttachmentDefinitionList
    Plural:     network-attachment-definitions
    Short Names:
      net-attach-def
    Singular:  network-attachment-definition
  Conditions:
    Last Transition Time:  2019-09-26T19:27:41Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  <nil>
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1
Events:  <none>

Any idea of what is the issue from the log?

Thanks.

**Comment by helioaymoto** [comment]
It was missing "macvlan" binary in /opt/cni/bin.
Not sure it was missing... but the Kubernet cluster has been installed by Rancher, so I think it might be something related to Rancher.

I have installed a kubernet cluster manually from where I got the "macvlan" binary...  I copied the binary to my Rancher Kubernet enviroment... and I could sucesfully create a POD with 2 networks/NICs.

**Comment by sunvim** [comment]
> macvlan

can u send me macvlan binary? i can't find it too
