### ISSUE TITLE
Question about config in NetworkAttachmentDefinition Spec

### ISSUE THREAD

**Issue by devdattakulkarni** [intel/multus-cni#397]
Currently the CNI config is defined as part of the spec of NetworkAttachmentDefinition Custom Resource definition. The structure of this config section seems to be like bash HERE Document. I was wondering what was the reason not to use Kubernetes's built-in Config object as input mechanism for passing in the CNI configuration? Then the name of such a Config object can be included as Spec parameter in NetworkAttachmentDefinition Spec.

**Comment by dougbtv** [comment]
@devdattakulkarni we'd love to have your input in the NPWG weekly meetings on this topic -- information about joining the meeting is available in the community github repo @ https://github.com/K8sNetworkPlumbingWG/community

**Comment by devdattakulkarni** [comment]
@dougbtv Thanks for the note. 
I will plan to join next meeting. When is it happening next? Is the next one on January 2nd at 
9:30AM US Eastern Time?

Another option, instead of ConfigMap, could be to include the Configuration data directly as different Spec properties. That would allow us to use CRD Schema validation feature to define validation rules for individual Spec properties. Right now the validation rule is defining that the config object should be a string. This is too coarse-grained. But explicitly defining required properties, we will be able to define fine-grained validation rules. Thoughts?
