### ISSUE TITLE
multus sriov cni not working after system reboot

### ISSUE THREAD

**Issue by RahulG115** [intel/multus-cni#40]
using multus sriov cni as network annotation (use for creating multiple interface ) in pod yaml file but after system reboot it is not working and pod is in still completed state but the weave multus cni plugin is working in the same way....

root@ubuntu:/home/mavenir/rahul/files# kubectl get pods -o wide
NAME READY STATUS RESTARTS AGE IP NODE
multus10 1/1 Running 8 8d 10.32.0.5 ubuntu
multus8-jq6m7 0/1 Completed 0 8d ubuntu

**Comment by rkamudhan** [comment]
@RahulG115 the issue is fixed, we will release the fixes in the couple of days

**Comment by rkamudhan** [comment]
I believe the issue is fixed. Please check it

**Comment by RahulG115** [comment]
okk i will check that
