### ISSUE TITLE
Configuration provided for Multus does not seem to be used.

### ISSUE THREAD

**Issue by svallala** [intel/multus-cni#400]
**What happened**:
I wanted to change a few things about the multus and they don't seem to take effect. Is my understanding correct about these parameters?

- Change the confDir from /etc/cni/multus/net.d to /etc/cni/net.d
- Enabling logging to logfile /var/log/multus.log
- ReadinessIndicator File - Even if the specified file is not present, I still see CNI requests coming to the Calico CNI plugin

Here is the config file I am using.

  cni-conf.json: |
    {
      "name": "multus-cni-network",
      "type": "multus",
      "capabilities": {
        "portMappings": true
      },
      "defaultNetworks": ["calico"],
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
      "confDir": "/etc/cni/net.d",
      "binDir": "/opt/cni/bin",
      "logFile": "/var/log/multus.log",
      "logLevel": "debug",
      "multusNamespace": "kube-system",
      "readinessindicatorfile": /etc/cni/plugin_ready
  }

**What you expected to happen**:

The configuration provided for Multus should be used.

**How to reproduce it (as minimally and precisely as possible)**:

Should be able to reproduce by customizing the fields mentioned here.

**Anything else we need to know?**:

**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
nfvpe/multus:v3.3

- Kubernetes version (use `kubectl version`):
[root@centos-60-218 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

- Primary CNI for Kubernetes cluster:
Calico
- OS (e.g. from /etc/os-release):
Centos 7.6
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by s1061123** [comment]
Could you please let us know which container runtime is used for k8s? (e.g. docker, cri-o or others)

**Comment by svallala** [comment]
Container runtime is docker 18.09.8 version

**Comment by s1061123** [comment]
One more q. Is you use this configmap to change the config?
https://github.com/intel/multus-cni/blob/master/images/multus-daemonset.yml#L67

**Comment by svallala** [comment]
Yes, I am using that file, with minor changes.

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: network-attachment-definitions.k8s.cni.cncf.io
spec:
  group: k8s.cni.cncf.io
  scope: Namespaced
  names:
    plural: network-attachment-definitions
    singular: network-attachment-definition
    kind: NetworkAttachmentDefinition
    shortNames:
    - net-attach-def
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                config:
                  type: string
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multus
rules:
  - apiGroups: ["k8s.cni.cncf.io"]
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
    verbs:
      - get
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multus
subjects:
- kind: ServiceAccount
  name: multus
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multus
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-config
  namespace: kube-system
  labels:
    tier: node
    app: multus
data:
  # NOTE: If you'd prefer to manually apply a configuration file, you may create one here.
  # In the case you'd like to customize the Multus installation, you should change the arguments to the Multus pod
  # change the "args" line below from
  # - "--multus-conf-file=auto"
  # to:
  # "--multus-conf-file=/tmp/multus-conf/70-multus.conf"
  # Additionally -- you should ensure that the name "70-multus.conf" is the alphabetically first name in the
  # /etc/cni/net.d/ directory on each node, otherwise, it will not be used by the Kubelet.
  cni-conf.json: |
    {
      "name": "multus-cni-network",
      "type": "multus",
      "capabilities": {
        "portMappings": true
      },
      "defaultNetworks": ["calico"],
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
      "confDir": "/etc/cni/net.d",
      "binDir": "/opt/cni/bin",
      "logFile": "/var/log/multus.log",
      "logLevel": "debug",
      "multusNamespace": "kube-system",
      "readinessindicatorfile": "/etc/cni/plugin_ready"
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds-amd64
  namespace: kube-system
  labels:
    tier: node
    app: multus
    name: multus
spec:
  selector:
    matchLabels:
      name: multus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: multus
        name: multus
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: multus
      containers:
      - name: kube-multus
        image: nfvpe/multus:v3.3
        command: ["/entrypoint.sh"]
        args:
        - "--multus-conf-file=auto"
        - "--cni-version=0.3.1"
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
        - name: multus-cfg
          mountPath: /tmp/multus-conf
      volumes:
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: multus-cfg
          configMap:
            name: multus-cni-config
            items:
            - key: cni-conf.json
              path: 70-multus.conf
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds-ppc64le
  namespace: kube-system
  labels:
    tier: node
    app: multus
    name: multus
spec:
  selector:
    matchLabels:
      name: multus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: multus
        name: multus
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/arch: ppc64le
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: multus
      containers:
      - name: kube-multus
        # ppc64le support requires multus:latest for now. support 3.3 or later.
        image: nfvpe/multus:latest-ppc64le
        command: ["/entrypoint.sh"]
        args:
        - "--multus-conf-file=auto"
        - "--cni-version=0.3.1"
        resources:
          requests:
            cpu: "100m"
            memory: "90Mi"
          limits:
            cpu: "100m"
            memory: "90Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
        - name: multus-cfg
          mountPath: /tmp/multus-conf
      volumes:
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: multus-cfg
          configMap:
            name: multus-cni-config
            items:
            - key: cni-conf.json
              path: 70-multus.conf

**Comment by s1061123** [comment]
Got it. Currently `multus-daemonset.yml` generates active CNI config file from `/etc/cni/net.d` in case of `--multus-conf-file=auto`, this option is enabled by default and your config file also has the one.

ConfigMap is used previously but now it is not used default.

Hence your modified configMap is not used. If you'd like to use it, you need to change `-multus-conf-file` (and might be configmap/volumeMounts to verify).

**Comment by s1061123** [comment]
Will close this issue soon. Please let me know if you have a question.

**Comment by svallala** [comment]
@s1061123 Thanks it worked after making the change you suggested.

**Comment by svallala** [comment]
@s1061123 Things are working fine, except that the readiness indicator file is not honored. Even before the file is created, I see requests to the IPAM module. What is the behavior of the readiness indicator?

**Comment by s1061123** [comment]
@svallala let's discuss about it in #402 because you've already created the one for that.
Let me close it.
