### ISSUE TITLE
Network attchment not working for Job objects

### ISSUE THREAD

**Issue by tse77** [intel/multus-cni#404]
I'm trying to get multus-cni to attach a macvlan interface in a pod belonging to a Job object but I can not get it to work.

I can get the samplepod example work:
Working:

    apiVersion: v1
    kind: Pod
    metadata:
      name: samplepod
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
    spec:
      containers:
      - name: samplepod
        command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
        image: dougbtv/centos-network

Not working:

    apiVersion: batch/v1
    kind: Job
    metadata:
      name: samplepod
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
    spec:
      template:
        spec:
          containers:
          - name: samplepod
            command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
            image: dougbtv/centos-network
          restartPolicy: Never

**What happend**:
Pod created from through job object does not have a second interface.

**What you expected to happen**:
POD should have a second interface.

**How to reproduce it (as minimally and precisely as possible)**:
Always reproducible

**Anything else we need to know?**:
I tried to add job resources to multus ClusterRole like so:

    kind: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: multus
    rules:
      - apiGroups: ["k8s.cni.cncf.io"]
        resources:
          - '*'
        verbs:
          - '*'
      - apiGroups:
          - ""
        resources:
          - pods
          - pods/status
        verbs:
          - get
          - update
      - apiGroups:
          - "batch"
        resources:
          - jobs
          - jobs/status
          - cronjobs
          - cronjobs/status
        verbs:
          - get
          - update
But i'm not sure if it needed or not?

**Environment**:
- K8s 
1.16.2

- Multus version 
v3.3

Anyone have any ideas what I could try to get it to work?

**Comment by tse77** [comment]
I got it to work now, I had to put the annotation under the template section like so:

    apiVersion: batch/v1
    kind: Job
    metadata:
      name: samplepod
    spec:
      template:
        metadata:
          annotations:
            k8s.v1.cni.cncf.io/networks: macvlan-conf
        spec:
          containers:
          - name: samplepod
            command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
            image: dougbtv/centos-network
            securityContext:
              privileged: true
          restartPolicy: Never

So now it works :)

**Comment by s1061123** [comment]
@tse77 good to hear that. Can I close this issue?

**Comment by tse77** [comment]
@s1061123  Yes you can close this issue.

**Comment by s1061123** [comment]
Thanks!
