### ISSUE TITLE
Install with helm 3

### ISSUE THREAD

**Issue by micw** [intel/multus-cni#410]
Hello,
helm 3 was just released - it is now just a client (no server component required anymore) and allows template based deployment. That means that we could put everything required for multus (including different setup variants) into one helm chart.
What do you think about it? If you are open to that idea (and make helm3 setup a 1st class citizen), I'd spend some time to create an initial chart for it.
Best regards,
Michael.

**Comment by lolin9** [comment]
Yes please. That would be great to have.

**Comment by s1061123** [comment]
@micw @lolin9 

@mukesh-dua is working on helm-chats for multus and other tools. Could you please take a look into it?
https://github.com/k8snetworkplumbingwg/helm-charts

**Comment by s1061123** [comment]
Will close it in a few days if no additional question.

**Comment by micw** [comment]
Please keep it open. I have an eye on the issue and will have a look at the chart and comment. Unfortunately I have not much time currently.

**Comment by s1061123** [comment]
@micw, Close it because it is not 'active issue' in the multus itself and please submit issue in [helm chats](https://github.com/k8snetworkplumbingwg/helm-charts) if you need feedback.

**Comment by maxpain** [comment]
Still no official helm chart?

**Comment by FranciscoSedeno** [comment]
Hi, I am trying to make a helm chart for a pod which uses multus CNI to add a new NI, but can't find a way to specify it. Does someone know how should I do it?
