### ISSUE TITLE
[dev] goreleaser deployment failing on tag

### ISSUE THREAD

**Issue by dougbtv** [intel/multus-cni#418]
Reference here: https://travis-ci.org/intel/multus-cni/jobs/611917037#L5077

This causes subsequent deployments to fail

**Comment by s1061123** [comment]
As of following message, goreleaser failed to upload due to 'already exist', I guess.

```
   ⨯ release failed after 178.29s error=GitHub/GitLab/Gitea Releases: failed to publish artifacts: failed to upload multus-cni_3.4_linux_386.tar.gz after 10 retries: POST https://uploads.github.com/repos/intel/multus-cni/releases/21477410/assets?name=multus-cni_3.4_linux_386.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
```

**Comment by s1061123** [comment]
I found that travis tries to add artifacts twice (one is TARGET=ppc and another is TARGET=amd64). #421 proposes to fix the issue (suppress ppc's gorelease invocation).
