### ISSUE TITLE
VF assignment/reassignment to a Pod

### ISSUE THREAD

**Issue by devdattakulkarni** [intel/multus-cni#425]
I was wondering how does Multus behave today if it is not able to assign a VF to a Pod? Does it try to select another VF from a Pool and assign to a Pod?

**Comment by ahalim-intel** [comment]
@devdattakulkarni 
I am assuming you are referring to SR-IOV VF? In that case, Multus has no role in VF assignment to any Pod. In Kubernetes, HW resources are managed by a Kubelet device plugin manager with an associated device plugin. For SR-IOV network interfaces, it is [SR-IOV network device plugin](https://github.com/intel/sriov-network-device-plugin/). 
Multus only able to look up allocated Pod devices if there is a `k8s.v1.cni.cncf.io/resourceName` annotation given in net-attach-def CR.

**Comment by devdattakulkarni** [comment]
Thanks @ahalim-intel for the note.

Yes, this question was related to SR-IOV VFs.
Thanks for the pointer that it is handled in the SR-IOV network device plugin. I will check with that team.
