### ISSUE TITLE
Ability to specify MAC address for an interface within the container

### ISSUE THREAD

**Issue by svallala** [intel/multus-cni#435]
Multus today has a way to specify the interface name using following annotations in the pod:

  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name" : "macvlan-conf-1",
              "interface": "macvlan1" }
    ]'

Can you add the ability to also specify the MAC address for the container interface:

  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name" : "macvlan-conf-1",
              "interface": "macvlan1",
              "macaddress": "ce:ff:6a:78:88:a1" }
    ]'

Some of the applications that are being containerized need the ability to pick a MAC address for the interface.

**Comment by s1061123** [comment]
Now you can specify MAC address in some CNI plugins (macvlan, bridge or so) in following way with latest multus and [CNI plugins](https://github.com/containernetworking/plugins/releases/tag/v0.8.5):

```
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: centos-runtimeconfig-def
spec: 
  config: '{
            "cniVersion": "0.3.1",
            "plugins": [
                {
                    "type": "macvlan",
                    "master": "eth1",
                    "mode": "bridge",
                    "ipam": {
                          (snip)
                    }
                }, {
                    "capabilities": { "mac": true },
                    "type": "tuning"
                } ]
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-runtimeconfig
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "centos-runtimeconfig-def",
              "mac": "c2:b0:57:49:47:f1" }
    ]'
spec:
  containers:
  - name: centos-runtimeconfig
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
    securityContext:
      privileged: true
```

**Comment by svallala** [comment]
@s1061123 I was looking for the ability to request mac address for SRIOV CNI plugin, so I am guessing I should open a ticket against that plugin, is that right?
