### ISSUE TITLE
Multus not working with Deployment file

### ISSUE THREAD

**Issue by thanhlong9x** [intel/multus-cni#444]
Hi, I'm read and exampled with your source. I use Deployment file to create pod. But my pod run with nothing additional interface. 
This is my pod and it's interfaces
![bug3](https://user-images.githubusercontent.com/29721257/75011735-f33d1580-54b2-11ea-92af-2033837db9a8.PNG)

deployment file
![Capture](https://user-images.githubusercontent.com/29721257/75011738-f506d900-54b2-11ea-874f-8415ecf82e08.PNG)

dmesg of node
![Capture2](https://user-images.githubusercontent.com/29721257/75011742-f59f6f80-54b2-11ea-8315-2e12ed9fa114.PNG)

**Comment by s1061123** [comment]
You need to add annotation in 'template.metadata' section of Deployment, not metadata of Deployment because multus parse annotation in Pod, not in Deployment.

**Comment by thanhlong9x** [comment]
Hi @s1061123 , Thank you for watching my issue. I tested with your suggestion. I see annotation on pod but don't see interface. As below:

![image](https://user-images.githubusercontent.com/29721257/76045493-d236f300-5f8f-11ea-8482-e92bfd33a94c.png)

**Comment by thanhlong9x** [comment]
Thank you, @s1061123 . My problem is solved.
