### ISSUE TITLE
Error checking when using kubeconfig is wrong

### ISSUE THREAD

**Issue by One-ders** [intel/multus-cni#45]
The function getK8sNetwork returns an error. After commit 7066439e38ce3e442699b40c4bbe3485a2409fd7
it was changed so that the error checking is done on the type of the returned error, instead of the string value. In cmdAdd a check is done for the type '*NoK8sNetworkError', but the function returns NoK8sNetworkError (no star), so the statement will never be true. What will happend is that the else will be taken, and if there is a default net in the delegates list, the pod will be started without any anotated nets, just with the default network, this is wrong if you wnated the pod to have annotated networks, and made an error in the config.

Also the cmdDel does not even check for the type of error, but for the string value, that is not returned anymore, since the update of getK8sNetwork. 

Attaching a git diff for an example fix.

[multus-error.patch.tar.gz](https://github.com/Intel-Corp/multus-cni/files/1736427/multus-error.patch.tar.gz)

Fixes 1

Signed-off-by: anders.franzen@yahoo.se

**Comment by rkamudhan** [comment]
Hi Anders. I will check the issue and try to fix it with your patch.

**Comment by One-ders** [comment]
Great!!!

**Comment by dougbtv** [comment]
Also put the `.patch` into a gist here @ https://gist.github.com/dougbtv/c58c08c9498070c2cdb9fd10dbc801e4

**Comment by dougbtv** [comment]
Fixed in #60
