### ISSUE TITLE
Is the log functionality working with v3.4?

### ISSUE THREAD

**Issue by mukesh-dua** [intel/multus-cni#450]
I am using Multus nfvpe/v3.4 image and using the following configMap:
```
  cni-conf.json: |
    {
      "name": "multus-cni-network",
      "type": "multus",
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
      "confDir": "/etc/cni/net.d",
      "cniDir": "/var/lib/cni/multus",
      "binDir": "/opt/cni/bin",
      "logFile:": "/var/log/multus.log",
      "logLevel": "debug",
      "readinessindicatorfile": "",
      "namespaceIsolation": "false",
      "clusterNetwork": "10-calico",
      "defaultNetwork": "",
      "systemNamespaces": "kube-system",
      "multusNamespace": "kube-system"
    }

```
Somehow, I don't see a log file created at path /var/log/multus.log. Am I missing any specific config here?

**Comment by s1061123** [comment]
- CNI configuration is required in container host side (i.e. /etc/cni/net.d/00-multus.conf in kube-master), not multus pod side. Could you please verify that your configMap changes are reflected in /etc/cni/net.d/00-multus.conf of each node?

additional comments:
- Changes are required not only in master node CNI config also in worker node. Could you please check your CNI config? 
- Log file is going to be created for each node (not aggregated to master), so could you please check your worker node?

Let me close it but please re-open you still have issue on that.

**Comment by mukesh-dua** [comment]
Yes, I observe a file at path /etc/cni/net.d/00-multus.conf 
`{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "k8s-pod-network", "cniVersion": "0.3.1", "plugins": [ { "type": "calico", "log_level": "debug", "datastore_type": "kubernetes", "nodename": "server-1", "mtu": 1440, "ipam": { "type": "calico-ipam" }, "policy": { "type": "k8s" }, "kubernetes": { "kubeconfig": "/etc/cni/net.d/calico-kubeconfig" } }, { "type": "portmap", "snat": true, "capabilities": {"portMappings": true} } ] } ] }`

Contents of configmap "multus-cni-config" created post deployment:
```
# kubectl describe cm multus-cni-config -n kube-system
Name:         multus-cni-config
Namespace:    kube-system
Labels:       app=multus
              tier=node
Annotations:  <none>

Data
====
cni-conf.json:
----
{
  "name": "multus-cni-network",
  "type": "multus",
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
  "confDir": "/etc/cni/net.d",
  "cniDir": "/var/lib/cni/multus",
  "binDir": "/opt/cni/bin",
  "logFile:": "/var/log/multus.log",
  "logLevel": "debug",
  "readinessindicatorfile": "",
  "namespaceIsolation": "false",
  "clusterNetwork": "10-calico",
  "defaultNetwork": "",
  "systemNamespaces": "kube-system",
  "multusNamespace": "kube-system"
}

Events:  <none>
```

**Comment by mukesh-dua** [comment]
>     * CNI configuration is required in container host side (i.e. /etc/cni/net.d/00-multus.conf in kube-master), not multus pod side. Could you please verify that your configMap changes are reflected in /etc/cni/net.d/00-multus.conf of each node?
> 
> 
> additional comments:
> 
>     * Changes are required not only in master node CNI config also in worker node. Could you please check your CNI config?
> 
>     * Log file is going to be created for each node (not aggregated to master), so could you please check your worker node?
> 
> 
> Let me close it but please re-open you still have issue on that.

Yes, I observe a file at path /etc/cni/net.d/00-multus.conf
`{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "k8s-pod-network", "cniVersion": "0.3.1", "plugins": [ { "type": "calico", "log_level": "debug", "datastore_type": "kubernetes", "nodename": "server-1", "mtu": 1440, "ipam": { "type": "calico-ipam" }, "policy": { "type": "k8s" }, "kubernetes": { "kubeconfig": "/etc/cni/net.d/calico-kubeconfig" } }, { "type": "portmap", "snat": true, "capabilities": {"portMappings": true} } ] } ] }
`
Contents of configmap "multus-cni-config" created post deployment:
```
# kubectl describe cm multus-cni-config -n kube-system
Name:         multus-cni-config
Namespace:    kube-system
Labels:       app=multus
              tier=node
Annotations:  <none>

Data
====
cni-conf.json:
----
{
  "name": "multus-cni-network",
  "type": "multus",
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
  "confDir": "/etc/cni/net.d",
  "cniDir": "/var/lib/cni/multus",
  "binDir": "/opt/cni/bin",
  "logFile:": "/var/log/multus.log",
  "logLevel": "debug",
  "readinessindicatorfile": "",
  "namespaceIsolation": "false",
  "clusterNetwork": "10-calico",
  "defaultNetwork": "",
  "systemNamespaces": "kube-system",
  "multusNamespace": "kube-system"
}

Events:  <none>
```

**Comment by s1061123** [comment]
As you mentioned above, your /etc/cni/net.d/00-multus.conf does not have 'logFile' and 'logLevel' config. 
Currently CNI config for kubernetes is only provided as a file, configMap is not supported yet, hence you do not have to change configMap, but have to change /etc/cni/net.d/00-multus.conf to add 'logLevel' and 'logFile'.

**Comment by mukesh-dua** [comment]
> As you mentioned above, your /etc/cni/net.d/00-multus.conf does not have 'logFile' and 'logLevel' config.
> Currently CNI config for kubernetes is only provided as a file, configMap is not supported yet, hence you do not have to change configMap, but have to change /etc/cni/net.d/00-multus.conf to add 'logLevel' and 'logFile'.

Thanks! it worked.
