### ISSUE TITLE
Network policies support

### ISSUE THREAD

**Issue by duylong** [intel/multus-cni#465]
Hello,

Does Multus support network policies? I don't have the impression when I create a second interface with a macvlan type.

Best regards.

**Comment by s1061123** [comment]
From multus-cni point of view, it should be implemented outside of multus-cni. Multus-cni just
 provides CNI multiplexing to interface CNI plugins and it does not provide network transporting/network filtering.

Currently I'm thinking to implement NetworkPolicy for macvlan using iptables, alongside multus-cni.
It should be under [kubernetes network plumbing working group](https://github.com/k8snetworkplumbingwg/). Stay tuned!
