### ISSUE TITLE
Communication between interface

### ISSUE THREAD

**Issue by jenifermajella02** [intel/multus-cni#478]
Hi everyone,

I am trying to bring communication between second interface (eth1) of the pod using multus. But ping is not happening. I am new to kubernetes and multus. Need ur support in this..

My test.yaml file is:

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: eth1
spec:
  config: '{
    "type": "bridge",
    "interface": "eth1",
    "master": "eth0",
    "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.200",
        "rangeEnd": "192.168.1.220",
        "routes": [
          { "dst": "0.0.0.0/0" },
		  { "dst": "192.168.1.0/24", "gw": "192.168.1.1" }
        ],
        "gateway": "192.168.1.1"
      }
  }'
---
apiVersion: v1
kind: Pod
metadata:
   name: csr
   annotations:
     k8s.v1.cni.cncf.io/networks: '[
            { "name" : "eth1",
              "interface": "eth1" }
    ]'
spec:
   containers:
   - name: csr
     image: csr_kgeneric:v0.16
     command: ["python", "/root/Main.py" ,"trap : TERM INT; sleep infinity & wait"]
#     imagePullPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
   name: ut
   annotations:
     k8s.v1.cni.cncf.io/networks: '[
            { "name" : "eth1",
              "interface": "eth1" }
    ]'
spec:
   containers:
   - name: ut
     image: ut:v0.1
     command: ["/root/loop.sh", "-d" ,"trap : TERM INT; sleep infinity & wait"]
#     imagePullPolicy: Always

Kindly let me know what mistake I m making. Why second interface is not pingable from other pod

**Comment by jenifermajella02** [comment]
@s1061123 : Any inputs/suggestions?

**Comment by s1061123** [comment]
Your network attachment definition, `eth1` is too big and it seems to be wrong config.
Could you please take a look into the following page (bridge cni README) and check the configuration parameters?
https://github.com/containernetworking/plugins/tree/master/plugins/main/bridge

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
name: eth1
spec:
config: '{
"type": "bridge",
"interface": "eth1",
"master": "eth0",
"ipam": {
"type": "host-local",
"subnet": "192.168.1.0/24",
"rangeStart": "192.168.1.200",
"rangeEnd": "192.168.1.220",
"routes": [
{ "dst": "0.0.0.0/0" },
{ "dst": "192.168.1.0/24", "gw": "192.168.1.1" }
],
"gateway": "192.168.1.1"
}
}'
```

From multus point of view, default route cannot be changed by ipam/routes. So as a first step, I recommend to make more simple config (e.g. macvlan/static ip/no route change) and try to add gradually.
