### ISSUE TITLE
multus-daemonset-pre-1.16.yml is broken for Kubernetes 1.13

### ISSUE THREAD

**Issue by neelimamukiri** [intel/multus-cni#479]
**What happend**:
In multus-daemonset-pre-1.16.yml, 
network-attachment-definitions.k8s.cni.cncf.io is being registered as apiextensions.k8s.io/v1 which doesn't exist in Kubernetes 1.13. It seems to have been broken with https://github.com/intel/multus-cni/commit/8fff5aac6046f4342dc65bda6190ee1172e1d7e7

**What you expected to happen**:
network-attachment-definitions.k8s.cni.cncf.io should be registered as apiextensions.k8s.io/v1beta1 as in 
https://raw.githubusercontent.com/intel/multus-cni/14fb6be1094b009b6a0ce6f9e9c15ee30c665636/images/multus-daemonset-pre-1.16.yml

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f  https://raw.githubusercontent.com/intel/multus-cni/master/images/multus-daemonset-pre-1.16.yml on a Kubernetes 1.13 cluster.

**Environment**:

- Multus version 
Broken in https://github.com/intel/multus-cni/commit/8fff5aac6046f4342dc65bda6190ee1172e1d7e7
Works with 
https://raw.githubusercontent.com/intel/multus-cni/14fb6be1094b009b6a0ce6f9e9c15ee30c665636/images/multus-daemonset-pre-1.16.yml
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
1.13.12
- Primary CNI for Kubernetes cluster:
Calico

**Comment by dougbtv** [comment]
@neelimamukiri -- thanks for the report! We believe that we may have incorrectly set the wrong API version in a recent fix.

We have a pending patch available here @ https://github.com/intel/multus-cni/pull/480

It's still in need of testing if you could also test those changes, I'd appreciate it. Thank you!

**Comment by s1061123** [comment]
#480 is now merged, so could you update your repo and try it?
