### ISSUE TITLE
Multus bringing up a Pod with incorrect number of interfaces

### ISSUE THREAD

**Issue by svallala** [intel/multus-cni#492]
Had a Pod with following annotations:
    k8s.v1.cni.cncf.io/networks: '[ { "interface": "eth1", "namespace": "t001-u000003",
      "name": "test1-pktgen-21-net1" } ]'
    v1.multus-cni.io/default-network: '[ { "interface": "eth0", "namespace": "kube-system",
      "name": "calico" } ]'

Pod came up with only one interface using Calico CNI plugin. There are no annotations to the Pod containing the "network-status".

Looked at the logs and the source code noticed the following error. Multus does not return a failure, instead, I think it assigns interface from the default network. This does not seem right, it brings up a Pod with incorrect configuration. The best thing would be to fail the CNI.

Apr 26 07:50:42 qct-03 kubelet: 2020-04-26T07:50:42-07:00 [debug] TryLoadPodDelegates: Err in loading K8s cluster default network from pod annotation: rpc error:      code = Unavailable desc = etcdserver: leader changed, use cached delegates

 Ignoring this error can be hard to track when 100s of Pods are deployed.

**Comment by svallala** [comment]
Multus Version: v3.4.1
K8s Version: 1.16.3

**Comment by svallala** [comment]
Please find the NetworkAttachment definitions. Given the known flakiness issues with etcd, it's better to retry multiple times and fail if we can't get the pod annotations.

[root@cscale-82-73 ~]# kubectl get net-attach-def -n kube-system calico -o yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"k8s.cni.cncf.io/v1","kind":"NetworkAttachmentDefinition","metadata":{"annotations":{},"name":"calico","namespace":"kube-system"}}
  creationTimestamp: "2020-04-29T05:04:02Z"
  generation: 1
  name: calico
  namespace: kube-system
  resourceVersion: "344"
  selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/kube-system/network-attachment-definitions/calico
  uid: a079f0b3-d0ec-4eb3-8390-4c188b640ee9
[root@cscale-82-73 ~]# kubectl get net-attach-def -n t001-u000003 test2-pktgen-01-net1 -o yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/enp59s0f0_iavf
  creationTimestamp: "2020-04-30T22:59:02Z"
  generation: 1
  name: test2-pktgen-01-net1
  namespace: t001-u000003
  resourceVersion: "374931"
  selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/t001-u000003/network-attachment-definitions/test2-pktgen-01-net1
  uid: bb723fcc-b5e7-4656-b9fa-3413bb8222e8
spec:
  config: '{ "cniVersion": "0.3.1", "name": "sriov-network", "plugins": [ { "type":
    "sriov", "vlan": 20, "ipam": { "type": "robin-ipam" } }, { "type": "tuning", "mtu":
    9000, "sysctl": { "net.ipv6.conf.all.accept_ra": "0", "net.ipv6.conf.default.accept_ra":
    "0", "net.ipv6.conf.eth1.accept_ra": "0" } } ] }'

**Comment by krishnajs** [comment]
@svallala we had a discussion with the maintainer and this is by design that when there is an error becasue of invalid network attachment definition becasue of multus this will not gate the creation of the pod.

**Comment by svallala** [comment]
@krishnajs this was not an error with Network Attachment defintion. Call to get the Pod annotations failed. It is still not clear why not fail, instead of bringing up a Pod with default network.

Let's say my default network is Calico. There is an option to override this with "default-network" annotation, I deploy a Pod with default-network as Flannel. Because Multus was not able to get Pod Annotations, it ends up bringing the Pod with Calico.

When you are deploying 100s of Pods, it will be a daunting task to figure out which of the Pods is not correctly deployed.

When there is an error, why not fail it? K8s will retry again and it might succeed the next try.

**Comment by svallala** [comment]
This code snippet is the problem. As I mentioned it's not happening consistently. Is there any reason to proceed if the issue is encountered? If the operation is failed at this point, there is a possibility of getting the right information when kubelet attempts again.

==================================================================
        // Get the pod info. If cannot get it, we use cached delegates
        pod, err := clientInfo.GetPod(string(k8sArgs.K8S_POD_NAMESPACE), string(k8sArgs.K8S_POD_NAME))
        if err != nil {
                logging.Debugf("TryLoadPodDelegates: Err in loading K8s cluster default network from pod annotation: %v, use cached delegates", err)
                return 0, nil, nil, nil
        }
==================================================================
