### ISSUE TITLE
Need help to configure multus in GKE 

### ISSUE THREAD

**Issue by ravikumar1907** [intel/multus-cni#508]
Does multus plugin will work in GKE ?
I followed the steps provided at https://intel.github.io/multus-cni/doc/quickstart.html and able configure , but pods are not comming with extra interfaces?

$ cat ./images/{multus-daemonset.yml,flannel-daemonset.yml} | kubectl apply -f -

multus pods came up and running with success message in log and /etc/cni/net.d/00-multus.conf got created.

Now Create network attachment definition for macvlan-conf:
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.2.0/24",
        "rangeStart": "192.168.2.200",
        "rangeEnd": "192.168.2.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.2.1"
      }
    }'

Now Run pod with network annotation
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine

But pod did not attached with extra interface macvlan-conf.

I'm stuck here and not found the way to debug.
Could someone please help me in this regard
Does anyone had tried multus on GKE ? Please share your inuputs.

Thanks
Ravi

**Comment by s1061123** [comment]
@cucosion may know about it because he create yaml file for gke.

Could you please take a look into it?
https://github.com/intel/multus-cni/blob/master/images/multus-daemonset-gke-1.16.yml

**Comment by ravikumar1907** [comment]
I tried multus-daemonset-gke-1.16.yml too. Same behavior.

**Comment by cucosion** [comment]
Hi @s1061123, @ravikumar1907,

To be able to deploy multus as second interface in GKE you will have to create the cluster with the flag --enable-network-policy, this flag will enable the cni. The full example should be something like:  
gcloud container clusters create <cluster name> --zone europe-west1-b  --num-nodes=2 --machine-type=c2-standard-8 --image-type ubuntu --enable-network-policy  --cluster-version "1.16.8-gke.15"
I added some detailed explanation in here https://github.com/intel/multus-cni/pull/455

After the cluster will be started with CNI enabled the default network plugin will be calico. After you can use the this yaml file to deploy multus https://github.com/intel/multus-cni/blob/master/images/multus-daemonset-gke-1.16.yml and after you can try it out to create a new network attachment definition and to attach a interface to your pod.

Keep in mind that this is not officially suported by GKE.

BR,
Ion

**Comment by ravikumar1907** [comment]
> Hi @s1061123, @ravikumar1907,
> 
> To be able to deploy multus as second interface in GKE you will have to create the cluster with the flag --enable-network-policy, this flag will enable the cni. The full example should be something like:
> gcloud container clusters create --zone europe-west1-b  --num-nodes=2 --machine-type=c2-standard-8 --image-type ubuntu --enable-network-policy --cluster-version "1.16.8-gke.15"
> I added some detailed explanation in here #455
> 
> After the cluster will be started with CNI enabled the default network plugin will be calico. After you can use the this yaml file to deploy multus https://github.com/intel/multus-cni/blob/master/images/multus-daemonset-gke-1.16.yml and after you can try it out to create a new network attachment definition and to attach a interface to your pod.
> 
> Keep in mind that this is not officially suported by GKE.
> 
> BR,
> Ion
@cucosion 
It's working now. Thank you for the help.
Calico is requirement for multus integration with GKE? Is GKE default flannel plugin will not work? 
Is it because of network policies in GKE.
 Also only cluster version 1.16.8-gke.15 to used ? I hope versions > 1.16.8 will work. 
Thanks
Ravi

**Comment by cucosion** [comment]
> > Hi @s1061123, @ravikumar1907,
> > To be able to deploy multus as second interface in GKE you will have to create the cluster with the flag --enable-network-policy, this flag will enable the cni. The full example should be something like:
> > gcloud container clusters create --zone europe-west1-b  --num-nodes=2 --machine-type=c2-standard-8 --image-type ubuntu --enable-network-policy --cluster-version "1.16.8-gke.15"
> > I added some detailed explanation in here #455
> > After the cluster will be started with CNI enabled the default network plugin will be calico. After you can use the this yaml file to deploy multus https://github.com/intel/multus-cni/blob/master/images/multus-daemonset-gke-1.16.yml and after you can try it out to create a new network attachment definition and to attach a interface to your pod.
> > Keep in mind that this is not officially suported by GKE.
> > BR,
> > Ion
> > @cucosion
> > It's working now. Thank you for the help.
> > Calico is requirement for multus integration with GKE? Is GKE default flannel plugin will not work?
> > Is it because of network policies in GKE.
> > Also only cluster version 1.16.8-gke.15 to used ? I hope versions > 1.16.8 will work.
> > Thanks
> > Ravi

@ravikumar1907 
Calico will be enabled if you are adding that flag for network policies. I tried with flannel but i had to adapt flannel daemon set to point to the correct folders, in GKE in the nodes, kubelet is not using the default folders, you will have to adapt the flannel daemon set to point to correct ones. eg look in /home/kuberenetes/bin ..
You can use with a newer version of kubernetes, i tested it with 1.16, with newer versions like 1.17 or 1.18 there can be changes in kubernetes objects used by multus and you will have to adapt them, just try it out

**Comment by ravikumar1907** [comment]
@cucosion  Did you ever try integrating https://github.com/intel/sriov-network-device-plugin + multus  with GKE. any help or some pointers towards that.

**Comment by cucosion** [comment]
> @cucosion Did you ever try integrating https://github.com/intel/sriov-network-device-plugin + multus with GKE. any help or some pointers towards that.

@ravikumar1907 No, i didnt try, most probable it would be quite hard to alter the GKE setup. If you will explain what you try to achive I can provide an advice. The SRIOV plugin if i'm not wrong is used to connect the pod NIC directlly to a high speed node NIC, you will have to alter the GKE cluster and you changes can be lost bu an automatic upgrade, it seems that a installation from scratch on GCP virtual machine can be easier.
Even like this i know that the network throughput in GCP is limited by the machine type so what do you try to achive with SRIOV that you cannot do with a default plugin? https://cloud.google.com/compute/docs/machine-types#network_bandwidth

**Comment by cucosion** [comment]
@ravikumar1907 Please close this issue since you where able to add multus to GKE setup :)
And you can open a new feature request on multus/sriov in gcp/gke setups

**Comment by ravikumar1907** [comment]
@cucosion  thank you for help to configure multus with GKE. Your inputs resolved my issue.
