### ISSUE TITLE
is it possible to add extra nic when poding is running ?

### ISSUE THREAD

**Issue by ftiannew** [intel/multus-cni#512]
Does multus support it currently ?or it can be improved to support it ?
thanks

**Comment by dougbtv** [comment]
Hi @ftiannew -- Multus doesn't currently support dynamic attachments.

Something you may be interested in is a fork of Multus called "kactus" which does do dynamic attachments: https://github.com/kaloom/kubernetes-kactus-cni-plugin

If you have use cases for dynamic attachments, you may wish to join the meetings for the network plumbing working group and discuss your use case and bring this functionality forward: https://github.com/k8snetworkplumbingwg/community

Thanks for your interest!
