### ISSUE TITLE
fix:511 is not compete,  how about the cmdDel part?

### ISSUE THREAD

**Issue by winsopc** [intel/multus-cni#519]
**What happend**:
pod could be nil in cmdDel..
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
https://github.com/intel/multus-cni/commit/fff8e490b964daf686de5cca9d421562e475af19

same reason with fix in cmdAdd part,  in cmdDel,  if getpod not working due to kclient acces,
pod is nil. then multus.go will panic, right?
**Anything else we need to know?**:
I think just add the code which #511 introduced to cmdDel()
**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
- Primary CNI for Kubernetes cluster:
- OS (e.g. from /etc/os-release):
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by winsopc** [comment]
@s1061123 what is the plan to integrate your fix for this problem?
This is a problem that can be easily hit on large scale cluster size.

**Comment by s1061123** [comment]
Still work on the issue. After rebase I will ask for review again.

**Comment by winsopc** [comment]
@s1061123 thanks for the update!
I pulled your changes and tested on my local large scale k8s client,  the problem fixed.
Thanks!
