### ISSUE TITLE
Not able to create additional interface using multus. 

### ISSUE THREAD

**Issue by aishwaryajoshi96** [intel/multus-cni#528]
I am not able to create an additional interface using multus. Initially I used flannel cni, afterwhich I migrated to calico and the set up worked fine. So I am currently using calico. Now I am trying to add additional interface using multus and I am following this guide: https://intel.github.io/multus-cni/doc/quickstart.html
I am not getting any errors. But I am not seeing any additional interfaces in my pods. 

Yaml file:
---
apiVersion: v1
kind: Pod
metadata:
  name: server
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command:  ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: k8worker2server
---

I have a 00-multus.conf file:
{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "k8s-pod-network", "cniVersion": "0.3.1", "plugins": [ { "type": "calico", "log_level": "info", "datastore_type": "kubernetes", "nodename": "k8master-standard-pc-i440fx-piix-1996", "mtu": 1450, "ipam": { "type": "calico-ipam" }, "policy": { "type": "k8s" }, "kubernetes": { "kubeconfig": "/etc/cni/net.d/calico-kubeconfig" } }, { "type": "portmap", "snat": true, "capabilities": {"portMappings": true} }, { "type": "bandwidth", "capabilities": {"bandwidth": true} } ] } ] }

I do not know where I am going wrong.

**Comment by s1061123** [comment]
Could you please share net-attach-def that you use, output of `kubectl get net-attach-def`?

**Comment by aishwaryajoshi96** [comment]
I figured out what the problem was. There was a cni version miss-match while creating network attachment definition (custom extension of Kubernetes that defines how we attach networks to our pods.). In the 00-multus.conf file, I was using 0.3.1 and in the network definition attachment, I used 0.3.0. After changing the version to 0.3.1, it worked fine. 
Thanks!
