### ISSUE TITLE
How to get the second interface IP by .spec grammer

### ISSUE THREAD

**Issue by ReyRen** [intel/multus-cni#531]
Like `status.podIP` to get the default pod IP address. But is there any way to get another interface IP in the pod?

thanks

**Comment by s1061123** [comment]
Currently we don't add second interface status in Pod's 'status', but we add network status in pod annotation, `k8s.v1.cni.cncf.io/network-status`. 

See section,"5. Network Attachment Status Annotation", in https://github.com/k8snetworkplumbingwg/multi-net-spec/tree/master/v1.1
