### ISSUE TITLE
TryLoadPodDelegates: Err in loading K8s cluster default network from pod annotation: Get "https://[10.96.0.1]:443/api/v1/namespaces/default/pods/samplepod1": Forbidden, use cached delegates

### ISSUE THREAD

**Issue by chandra-eric** [intel/multus-cni#532]
The macvlan is not triggered and secondary network/interfaces are not created in pod.
Basic K8s nodes
controller1:# kubectl get nodes -owide
NAME          STATUS   ROLES    AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                              KERNEL-VERSION      CONTAINER-RUNTIME
compute1      Ready    <none>   6h22m   v1.18.0   192.168.2.23   <none>        SUSE Linux Enterprise Server 15 SP2   5.3.18-11-default   cri-o://1.17.3
controller1   Ready    master   6h23m   v1.18.0   10.64.215.95   <none>        SUSE Linux Enterprise Server 15 SP2   5.3.18-11-default   cri-o://1.17.3

controller1:# kubectl cluster-info
Kubernetes master is running at https://192.168.2.20:6443
KubeDNS is running at https://192.168.2.20:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

Flannel installtion:

sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

Multus installation:
git clone https://github.com/intel/multus-cni.git && cd multus-cni
sudo cat ./images/multus-daemonset.yml | sudo kubectl apply -f -

Macvlan installation 

cat <<EOF | sudo kubectl create --kubeconfig=/etc/kubernetes/admin.conf -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "enp0s3",
      "mode": "bridge",
      "ipam": {
	"type": "host-local",
	"subnet": "193.168.1.0/24",
	"rangeStart": "193.168.1.200",
	"rangeEnd": "193.168.1.216",
	"routes": [
	  { "dst": "0.0.0.0/0" }
	],
	"gateway": "193.168.1.1"
      }
    }'
EOF

cat <<EOF | sudo kubectl create --kubeconfig=/etc/kubernetes/admin.conf -f - 
apiVersion: v1 
kind: Pod 
metadata: 
  name: samplepod1 
  annotations: 
    k8s.v1.cni.cncf.io/networks: macvlan-conf 
spec: 
  containers: 
  - name: samplepod1 
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"] 
    image: alpine 
EOF

We have enabled logging in multus and the following is the error in multus.log:

**What happend**:
The macvlan is not triggered and secondary network/interfaces are not created in pod.

**What you expected to happen**:
It is expected to that secondary network/interfaces is created in pod.

**How to reproduce it (as minimally and precisely as possible)**:
Flannel installtion:

sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

Multus installation:
git clone https://github.com/intel/multus-cni.git && cd multus-cni
sudo cat ./images/multus-daemonset.yml | sudo kubectl apply -f -

Macvlan installation 

cat <<EOF | sudo kubectl create --kubeconfig=/etc/kubernetes/admin.conf -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "enp0s3",
      "mode": "bridge",
      "ipam": {
	"type": "host-local",
	"subnet": "193.168.1.0/24",
	"rangeStart": "193.168.1.200",
	"rangeEnd": "193.168.1.216",
	"routes": [
	  { "dst": "0.0.0.0/0" }
	],
	"gateway": "193.168.1.1"
      }
    }'
EOF

cat <<EOF | sudo kubectl create --kubeconfig=/etc/kubernetes/admin.conf -f - 
apiVersion: v1 
kind: Pod 
metadata: 
  name: samplepod1 
  annotations: 
    k8s.v1.cni.cncf.io/networks: macvlan-conf 
spec: 
  containers: 
  - name: samplepod1 
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"] 
    image: alpine 
EOF

We have enabled logging in multus and the following is the error in multus.log:

**Anything else we need to know?**:

**Environment**:
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"

- Multus version 
  image path and image ID (from 'docker images')
   docker.io/nfvpe/multus                                v3.4.1              bf33fe4c52f0a       286MB
- Kubernetes version (use `kubectl version`):
  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T12:00:00Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-06-10T00:00:00Z", GoVersion:"go1.13.11", Compiler:"gc", Platform:"linux/amd64"}

- Primary CNI for Kubernetes cluster:
   flannel
- OS (e.g. from /etc/os-release):
  NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"
- File of '/etc/cni/net.d/'
   ceeinfra@controller1:/etc/cni/net.d> sudo cat  00-multus.conf
{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "logLevel": "debug", "logFile": "/var/log/multus.log", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "cbr0", "cniVersion": "0.3.1", "plugins": [ { "type": "flannel", "delegate": { "hairpinMode": true, "isDefaultGateway": true } }, { "type": "portmap", "capabilities": { "portMappings": true } } ] } ] }

- File of '/etc/cni/multus/net.d'
  ceeinfra@controller1:/etc/cni/net.d/multus.d> ls
multus.kubeconfig
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: network-attachment-definitions.k8s.cni.cncf.io
spec:
  group: k8s.cni.cncf.io
  scope: Namespaced
  names:
    plural: network-attachment-definitions
    singular: network-attachment-definition
    kind: NetworkAttachmentDefinition
    listKind: NetworkAttachmentDefinitionList
    shortNames:
    - net-attach-def
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              config:
                type: string

- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
Name:         samplepod2
Namespace:    default
Priority:     0
Node:         compute1/192.168.2.23
Start Time:   Fri, 03 Jul 2020 18:24:19 +0200
Labels:       <none>
Annotations:  k8s.v1.cni.cncf.io/networks: macvlan-conf
Status:       Running
IP:           193.168.1.7
IPs:
  IP:  193.168.1.7
Containers:
  samplepod2:
    Container ID:  cri-o://a4c36b93a5bbfca4c3143744c8b6a9e75c375c2d280b7719eadc9978a6df5993
    Image:         alpine
    Image ID:      docker.io/library/alpine@sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/ash
      -c
      trap : TERM INT; sleep infinity & wait
    State:          Running
      Started:      Fri, 03 Jul 2020 18:24:28 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-68ctr (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  default-token-68ctr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-68ctr
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  24m   default-scheduler  Successfully assigned default/samplepod2 to compute1
  Normal  Pulling    24m   kubelet, compute1  Pulling image "alpine"
  Normal  Pulled     24m   kubelet, compute1  Successfully pulled image "alpine"
  Normal  Created    24m   kubelet, compute1  Created container samplepod2
  Normal  Started    24m   kubelet, compute1  Started container samplepod2

- Other log outputs (if you use multus logging)
2020-07-03T18:24:25+02:00 [debug] TryLoadPodDelegates: &{{true} <nil> samplepod2 default 4d049de33ced520c02c091d30fc5d8a59e63c971a01372566aef1efd9b543c33}, &{{0.3.1 multus-cni-network multus map[] {} {[]  [] []} map[] <nil>} <nil> <nil> /etc/cni/multus/net.d /var/lib/cni/multus /opt/cni/bin [] [0xc000293600] [] /etc/cni/net.d/multus.d/multus.kubeconfig  [] /var/log/multus.log debug <nil>  false [kube-system] kube-system}, <nil>
2020-07-03T18:24:25+02:00 [debug] GetK8sClient: /etc/cni/net.d/multus.d/multus.kubeconfig, <nil>
2020-07-03T18:24:25+02:00 [debug] setKubeClientInfo: &{<nil>  }, &{0xc000338690}, &{{true} <nil> samplepod2 default 4d049de33ced520c02c091d30fc5d8a59e63c971a01372566aef1efd9b543c33}
2020-07-03T18:24:25+02:00 [debug] TryLoadPodDelegates: Err in loading K8s cluster default network from pod annotation: Get https://10.96.0.1:443/api/v1/namespaces/default/pods/samplepod2: Forbidden, use cached delegates
2020-07-03T18:24:25+02:00 [debug] saveDelegates: 4d049de33ced520c02c091d30fc5d8a59e63c971a01372566aef1efd9b543c33, /var/lib/cni/multus, [0xc000293600]
2020-07-03T18:24:25+02:00 [debug] saveScratchNetConf: 4d049de33ced520c02c091d30fc5d8a59e63c971a01372566aef1efd9b543c33, /var/lib/cni/multus, [{"Conf":{"cniVersion":"0.3.1","name":"cbr0","ipam":{},"dns":{}},"ConfList":{"cniVersion":"0.3.1","name":"cbr0","plugins":[{"type":"flannel","ipam":{},"dns":{}},{"type":"portmap","capabilities":{"portMappings":true},"ipam":{},"dns":{}}]},"Bytes":"eyJjbmlWZXJzaW9uIjoiMC4zLjEiLCJuYW1lIjoiY2JyMCIsInBsdWdpbnMiOlt7ImRlbGVnYXRlIjp7ImhhaXJwaW5Nb2RlIjp0cnVlLCJpc0RlZmF1bHRHYXRld2F5Ijp0cnVlfSwidHlwZSI6ImZsYW5uZWwifSx7ImNhcGFiaWxpdGllcyI6eyJwb3J0TWFwcGluZ3MiOnRydWV9LCJ0eXBlIjoicG9ydG1hcCJ9XX0="}]

**Comment by chandra-eric** [comment]
Is there any WA for this issue ?

**Comment by s1061123** [comment]
I cannot reproduce this issue. With following configuration, net1 of macvlan interface is created, hence I suppose it is not multus issue.

`Err in loading K8s cluster default network from pod annotation: Get "https://[10.96.0.1]:443/api/v1/namespaces/default/pods/samplepod1"` means that multus cannot communicate with Kubernetes API, so could you please check Kubernetes configuration (RBAC for multus and so on)?

Output of kubectl:
```
[centos@kube-master1 ~]$ cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
        "cniVersion": "0.3.1",
        "type": "macvlan",
        "master": "eth1",
        "mode": "bridge",
        "ipam": {
                "type": "host-local",
                "subnet": "193.168.1.0/24",
                "rangeStart": "193.168.1.200",
                "rangeEnd": "193.168.1.216",
                "routes": [
                        { "dst": "0.0.0.0/0" }
                ],
                "gateway": "193.168.1.1"
        }
  }'
---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod1
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
    - name: samplepod1
      command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
      image: alpine
EOF

networkattachmentdefinition.k8s.cni.cncf.io/macvlan-conf created
pod/samplepod1 created
```

`ip a` output for pod:
```
[centos@kube-master1 ~]$ kubectl exec -it samplepod1 -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3: eth0@if12: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP
    link/ether 42:c7:c8:43:b0:f2 brd ff:ff:ff:ff:ff:ff
    inet 10.244.1.7/24 brd 10.244.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::40c7:c8ff:fe43:b0f2/64 scope link
       valid_lft forever preferred_lft forever
4: net1@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN
    link/ether 36:70:1b:a7:8f:02 brd ff:ff:ff:ff:ff:ff
    inet 193.168.1.201/24 brd 193.168.1.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::3470:1bff:fea7:8f02/64 scope link
       valid_lft forever preferred_lft forever
```

Environment Info:
```
[centos@kube-master1 ~]$ sudo cat /etc/cni/net.d/00-multus.conf
{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "logLevel": "debug", "logFile": "/tmp/multus.log", "binDir": "/opt/multus/bin", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "cbr0", "cniVersion": "0.3.1", "plugins": [ { "type": "flannel", "delegate": { "hairpinMode": true, "isDefaultGateway": true } }, { "type": "portmap", "capabilities": { "portMappings": true } } ] } ] }
[centos@kube-master1 ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by chandra-eric** [comment]
Thanks for the looking.
We have tested the same on Ubuntu, it working fine.
