### ISSUE TITLE
Multus interface is missing if openshift cluster is powercycled

### ISSUE THREAD

**Issue by RiteshWalia** [intel/multus-cni#535]
In OKD 3.11 I have created deployment which integrated multus-cni annotation. It was observed that if we do powercycle of cluster the multus interface is missing OR simply gets deleted whenever POD comes up after powercycle. Is this expected behaviour ? POD definitions still had annotations defined however multus interface was missing. And after explicit delete of pod would get interface created. 

Steps to Reproduce -
1. oc exec -it test-pod -- ifconfig [multus/2nd interface is present]
2. Powercycle complete cluster
3. oc exec -it test-pod -- ifconfig [multus/2nd interface is missing]

Multus Version - 3.4.1
OpenShift Version -
oc v3.11.0+4986039-380
kubernetes v1.11.0+d4cacc0

**Comment by dougbtv** [comment]
Hi @RiteshWalia -- unfortunately, Kubernetes v1.11 is below our supported version for Multus, so I don't believe we're likely to dig in to find the core issues here. However, it's plausible Multus will work with it, but, it would be usage at your own risk.

I do have some good news for you, though. With OKD 4.x, Multus CNI is installed by default and configured by OKD for you.

Something that I might recommend is that you enable logging: https://github.com/intel/multus-cni/blob/master/doc/configuration.md#logging

This might give you some insight as to what's happening. If there's no logging after the reboot, it may be that somehow Multus is not enabled. I have some previous experience OKD 3.11, and I believe that the openshift-sdn configuration will probably want to own the primary on-disk CNI configuration on each node, and it won't likely have Multus configured. So it's possible that the pods come up too early, before Multus is configured, and then Multus isn't executed during the cluster reboot.

**Comment by RiteshWalia** [comment]
Thanks @dougbtv . I'll mark this close. However if there is some interesting findings I'll update in the thread.
