### ISSUE TITLE
Does Multus work on v1.14?

### ISSUE THREAD

**Issue by vveldand** [intel/multus-cni#538]
Hello,
I am using kubernetes version 1.14?. 

The recommended kube version per the URL below is v1.16 or above. Does it mean that I can't use multus with v1.14?

Currently when I run multus pod I run in to the below error. Could the below error be related to the incompatible version?

cat ./images/multus-daemonset.yml | kubectl apply -f -
clusterrole.rbac.authorization.k8s.io/multus unchanged
clusterrolebinding.rbac.authorization.k8s.io/multus unchanged
serviceaccount/multus unchanged
configmap/multus-cni-config unchanged
daemonset.apps/kube-multus-ds-amd64 unchanged
daemonset.apps/kube-multus-ds-ppc64le unchanged
**error: unable to recognize "STDIN": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"**

**Pod fails to initialize** 
Name:               kube-multus-ds-amd64-b4tbk
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               127.0.0.1/127.0.0.1
Start Time:         Thu, 23 Jul 2020 08:37:13 +0000
Labels:             app=multus
                    controller-revision-hash=5d45d6b5b4
                    name=multus
                    pod-template-generation=1
                    tier=node
Annotations:        <none>
Status:             Running
IP:                 127.0.0.1
Controlled By:      DaemonSet/kube-multus-ds-amd64
Containers:
  kube-multus:
    Container ID:  docker://4762cbd8929e3a79a96d0a39d1862e9830e91ea790a63f67b9a7561b32e3f580
    Image:         nfvpe/multus:v3.4.1
    Image ID:      docker-pullable://nfvpe/multus@sha256:167722b954355361bd69829466f27172b871dbdbf86b85a95816362885dc0aba
    Port:          <none>
    Host Port:     <none>
    Command:
      /entrypoint.sh
    Args:
      --multus-conf-file=auto
      --cni-version=0.3.1
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 23 Jul 2020 09:20:16 +0000
      Finished:     Thu, 23 Jul 2020 09:20:20 +0000
    Ready:          False
    Restart Count:  13
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:        100m
      memory:     50Mi
    Environment:  <none>
    Mounts:
      /host/etc/cni/net.d from cni (rw)
      /host/opt/cni/bin from cnibin (rw)
      /tmp/multus-conf from multus-cfg (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  cni:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:
  cnibin:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:
  multus-cfg:
    Type:        ConfigMap (a volume populated by a ConfigMap)
    Name:        multus-cni-config
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  kubernetes.io/arch=amd64
Tolerations:     :NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                   From                Message
  ----     ------     ----                  ----                -------
  Normal   Scheduled  46m                   default-scheduler   Successfully assigned kube-system/kube-multus-ds-amd64-b4tbk to 127.0.0.1
  Normal   Pulling    46m                   kubelet, 127.0.0.1  Pulling image "nfvpe/multus:v3.4.1"
  Normal   Pulled     46m                   kubelet, 127.0.0.1  Successfully pulled image "nfvpe/multus:v3.4.1"
  Normal   Created    44m (x5 over 46m)     kubelet, 127.0.0.1  Created container kube-multus
  Normal   Pulled     44m (x4 over 46m)     kubelet, 127.0.0.1  Container image "nfvpe/multus:v3.4.1" already present on machine
  Normal   Started    44m (x5 over 46m)     kubelet, 127.0.0.1  Started container kube-multus
  Warning  BackOff    106s (x203 over 46m)  kubelet, 127.0.0.1  Back-off restarting failed container

# **kubectl logs kube-multus-ds-amd64-b4tbk -n kube-system**
cat: /var/run/secrets/kubernetes.io/serviceaccount/token: No such file or directory

**Comment by dougbtv** [comment]
Currently we don't support any kubernetes that the upstream does not support.

This includes the latest 3 releases (1.18, 1.17, 1.16)

You can use 1.14 at your risk, however. Look for the "pre-1.16" daemonset.

Thanks for your interest!
