### ISSUE TITLE
ADD ARM64 jobs to Travis-CI

### ISSUE THREAD

**Issue by odidev** [intel/multus-cni#558]
Hi Team,

I am looking to add ARM64 jobs in Travis.
I have checked that the package has ARM64 support and ARM64 binaries are already available in  <https://github.com/intel/multus-cni/releases>. Also, Multus-cni is releasing ARM64 Docker images <https://hub.docker.com/r/nfvpe/multus/tags>. It would be great if we can test ARM64  builds in the Travis-CI as well. 
Changes:  <https://github.com/odidev/multus-cni/commit/54a82839b6b987e8ecbbca2cbceca2b1f9f2b9b0>
Travis logs:  <https://travis-ci.com/github/odidev/multus-cni>
If you are interested in this activity, I can raise a PR for the same.

Please share your opinion on this.

**Comment by s1061123** [comment]
Hi,

Previously multus uses travis-ci for CI until last February, but now currently multus switches CI to [github actions](https://github.com/intel/multus-cni/actions). Hence [travis.yml](https://github.com/intel/multus-cni/blob/master/.travis.yml) is no longer used and it should be removed.

In CI builds, ARM64 build is done in [go-build-arm64.yml](https://github.com/intel/multus-cni/blob/master/.github/workflows/go-build-arm64.yml) here.

I'm going to remove .travis.yml soon not to make someone wrong.
