### ISSUE TITLE
Unable to create addition interface in Deployment

### ISSUE THREAD

**Issue by rroberts59110** [intel/multus-cni#566]
I am using a Rancher k3s cluster with calico as the main network plugin and using multus to provide an additional interface to one of my pods. I can successfully create a pod with the additional interface but when I use a Deployment resource the additional interface is not appearing on the pod.

I first placed the annotation in the deployment metadata
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ...
  labels:
    app: ...
  annotations:
      k8s.v1.cni.cncf.io/networks: macvlan-conf
         .
         .
         .
 and when it didn't work I realized the annotation was on the pod so it needed to be in the pod template metadata:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ...
  labels:
    app: ...
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ...
  template:
    metadata:
      labels:
        app: ....
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf 
    spec:
      containers:
          .
          .
          .

This hasn't worked for me either.
In examining closed issues here I see moving the annotation to the template metadata section was sufficient for resolving some users issues but it isn't working for me.

I see one user submitted this same issue a couple years ago 
https://github.com/intel/multus-cni/issues/196
and indicated his problem was resolved by enabling an RBAC permission so that Multus can read the Pod information from the Deployment vs the Pod. However this user user did not describe his particular solution and I am unsure what I need to do.

Both my network-attachment-definition and my deployment reside in the default namespace for now.

Any help would be appreciated.

**Comment by dougbtv** [comment]
Out of curiosity, does it work when you use it against a pod? (as opposed to a deployment)

**Comment by rroberts59110** [comment]
Yes, it works fine against a pod. But when applied to a deployment the interface does not appear.

**Comment by rroberts59110** [comment]
Okay. My fault for failing to reapply changes to my Deployment file. Adding the k8s.v1.cni.cncf.io/networks: macvlan-conf annotation to the metadata section of the Pod template in side the Deployment file was sufficient. This issue is closed.
