### ISSUE TITLE
Creating vlan interfaces on k8s

### ISSUE THREAD

**Issue by iaas365-dev** [intel/multus-cni#569]
Hello, this is my context:

- Vanilla kubernetes cluster v1.17.12 on Centos7
- On each worker I have a nic (eth2) connected to a switch port set with dot1q (vlan range 1-4094 enabled)
- I want to deploy some pods on any of the vlans enabled

I tried to use "type=vlan" but failed with errors like "conflistAdd: error in getting result from AddNetworkList: failed to create vlan: file exists" when a second pod is deployed on the same worker. The first one on each worker runs fine.
$ cat net-vlan112-static.yaml 
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-eth2-112
spec: 
  config: '{
                "cniVersion": "0.3.0",                
                "plugins": [ 
                {
                        "type": "vlan",
                        "master": "eth2",
                        "vlanId": 112,
                        "ipam": {
                                "type": "static"
                        }
                }]
        }'

I was able to make it runs doing this:

1. Deploy on each worker a bridge (multusbr0) with eth2 attached

1. Deploy on each worker a vlan interface (multusbr0.<vlan_id>) for each vlan I want to use

1. Create a network attachement for each vlan_id as (example for vlan 112):
$ cat net-dp-vlan112.yaml 
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-eth2-112-v2
  namespace: default
spec:
  config: '{ "cniVersion": "0.3.0", "plugins": [ { "type": "macvlan", "master": "multusbr0.112",
     "ipam": { "type": "static" } }] }'

After doing this I can run multiple pods on any worker without limitations.

My question: is there a better way to do it that saves us the work of creating all vlans before using them?

Thanks in advance.

**Comment by CJCShadowsan** [comment]
@iaas365-dev - could you explain your steps for your workaround?

I have a KubeVirt VM that needs to sit on 4 VLANS!

**Comment by dougbtv** [comment]
This, is unfortunately... How VLAN CNI plugin works. It's only going to allow the vlan for a single interface on a single pod, and that's all that can be done with it.

However! I think the better solution would actually be to use the vlan feature of the bridge CNI plugin. So, configure your bridges (either manually [for a lab], via configuration management, or even better, through an operator like machine-config-operator, or something like that)... Also, configure them for use of a vlan. And then... Use the bridge CNI and use the same name as the bridges on the host. With bridge CNI when you specify a bridge name, it will create it if it doesn't exist, or it'll use one if it already exists.

Bridge CNI docs @ https://github.com/containernetworking/plugins/blob/master/plugins/main/bridge/README.md

I think further issues shoud probably be filed in the CNI plugins repo, as these are specific to those. Regardless, thanks for filing the issue!

cc: @CJCShadowsan

**Comment by iaas365-dev** [comment]
> This, is unfortunately... How VLAN CNI plugin works. It's only going to allow the vlan for a single interface on a single pod, and that's all that can be done with it.
> 
> However! I think the better solution would actually be to use the vlan feature of the bridge CNI plugin. So, configure your bridges (either manually [for a lab], via configuration management, or even better, through an operator like machine-config-operator, or something like that)... Also, configure them for use of a vlan. And then... Use the bridge CNI and use the same name as the bridges on the host. With bridge CNI when you specify a bridge name, it will create it if it doesn't exist, or it'll use one if it already exists.
> 
> Bridge CNI docs @ https://github.com/containernetworking/plugins/blob/master/plugins/main/bridge/README.md
> 
> I think further issues shoud probably be filed in the CNI plugins repo, as these are specific to those. Regardless, thanks for filing the issue!
> 
> cc: @CJCShadowsan

Hello dougbtv, your were rigth.
We've applied vlan_filtering with bridge plugin and it let us work with a single bridge interface on the workers without vlan interfaces created.
Unfortunately the bridge plugin doesn't manage the "bridge vlan add" part and it seems not possible to set a vlan range on it.
Anyway we can deal with it at /etc/rc.local script.
Thanks!

**Comment by iaas365-dev** [comment]
> @iaas365-dev - could you explain your steps for your workaround?
> 
> I have a KubeVirt VM that needs to sit on 4 VLANS!

Hello Chris, I think this link could help you to clarify ideas, it did for us.
[https://developers.redhat.com/blog/2017/09/14/vlan-filter-support-on-bridge/](url)
Luck!

**Comment by CJCShadowsan** [comment]
I'm confused. What am I missing here?

```
cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br1-vl101
spec:
  config: '{
      "cniVersion": "0.4.0",
      "type": "bridge",
      "bridge": "br1",
      "vlan": 101,
      "master": "bond0",
      "ipam": {
        "type": "host-local",
        "subnet": "172.17.0.0/16",
        "rangeStart": "172.17.1.220",
        "rangeEnd": "172.17.1.220"
      }
    }'
```

So I create this, and I create a VM to bring this up... It creates, it attaches... One for each vlan.

Bridge vlan shows:
```
port    vlan ids
em1
em2
bond0    1 PVID Egress Untagged

bond0
docker0  1 PVID Egress Untagged

docker_gwbridge  1 PVID Egress Untagged

br3      1 PVID Egress Untagged

br2      1 PVID Egress Untagged

br1      1 PVID Egress Untagged

br4      1 PVID Egress Untagged

veth16cdc4c1     1 Egress Untagged
         164 PVID Egress Untagged

veth9dd6c808     1 Egress Untagged
         102 PVID Egress Untagged

veth8b0a5dac     1 Egress Untagged
         101 PVID Egress Untagged

vethf0e14b2b     1 Egress Untagged
         7 PVID Egress Untagged
```

The addresses are up, the link shows up, yet I can't traverse the VM to physical hosts.

What am I missing anyone?

**Comment by willzhang** [comment]
same here when rollout restart pod
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: host-device-nic1
  namespace: ns1-ee0e0
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "net1",
      "type": "host-device",
      "pciBusID": "0000:f4:22.0"
    }
```
```
Warning  FailedCreatePodSandBox  6s (x13 over 2m48s)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "bdc29180e537e4050eaa83a89928008e46b9658116f5d059d3bf0acfbedf8381": plugin type="multus" name="multus-cni-network" failed (add): [namespace/app-1-688bcf578f-ds8l8/e353188d-93b2-4552-821c-a68343b6c395:net3]: error adding container to network "net3": failed to create vlan: file exists
```

**Comment by reski-rukmantiyo** [comment]
any news for this? this is happened to me if i have multiple pod / vm (kubevirt) using same vlan ID on same host.
If i checked from above post, have to use combination of vlan and bridge...still confused about this. Reference: [link](https://developers.redhat.com/blog/2017/09/14/vlan-filter-support-on-bridge#without_vlan_filtering)
