### ISSUE TITLE
Golint not being run on GitHub actions?

### ISSUE THREAD

**Issue by dougbtv** [intel/multus-cni#572]
Example: https://github.com/intel/multus-cni/pull/571/checks?check_run_id=1299891943

```
/home/runner/work/_temp/73003cae-6c26-4b4e-9d1a-8f20e92ad9f3.sh: line 1: golint: command not found
```

**Comment by martinkennelly** [comment]
I had the same issue with golint binary not being found using GAs. I switched to a different system for static analysis and used a golang linter ```golangci-lint``` and enabled golint there.

https://github.com/k8snetworkplumbingwg/network-resources-injector/pull/67
Feel free to reuse if you see any value.

**Comment by s1061123** [comment]
@dougbtv @martinkennelly Thank you so much for let me know the issue!

Now I'm working on update github action script and it is already taken care of new one. When I submit PR, I'm going to mention this issue.
