### ISSUE TITLE
How to assign two `host-local` IPs to a single NIC?

### ISSUE THREAD

**Issue by podusowski** [intel/multus-cni#575]
My goal is to have pod with two IP addresses belonging to the same network, kind of like multi-homing. I have `NetworkAttachmentDefinition`:

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: mynetwork
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "mybridge",
      "type": "bridge",
      "bridge": "mybridge",
      "ipam": {
        "type": "host-local",
        "ranges": [
          [
            {
              "subnet": "some values here",
              "rangeStart": "some values here",
              "gateway": "some values here"
            }
          ]
        ]
      }
    }
```

### Two NICs
I could use it to create two interfaces:
```
annotations:
        k8s.v1.cni.cncf.io/networks: mynetwork@if1, mynetwork@if2
```
but my network will be broken due to [`rp_filter == 1`](https://access.redhat.com/solutions/53031), which I can't change.

## Assign two static IPs
I could assign two static IPs through POD annotation, but need my solution to scale, i.e. I can't duplicate addresses across POD replicas.

**Comment by dougbtv** [comment]
I think you can specify multiple IP addresses with the static CNI plugin: https://github.com/containernetworking/plugins/tree/master/plugins/ipam/static

There's also a whereabouts feature request for multiple IPs (for dual stack, but relevant I think): https://github.com/dougbtv/whereabouts/issues/62
