### ISSUE TITLE
interface is not exist

### ISSUE THREAD

**Issue by majorinche** [intel/multus-cni#576]
my goal: pod should have two ip, one is k8s internal ip, another one is physical network ip, which can connect to outside network.
i understand i need use host-local type.

so after install multus cni plugin, then i configure networkattachmentdefinition cr like following: 

[root@d0404 cluster_configuration]# cat nad-cr.yaml 
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "host-local",
      "master": "bond0.1103",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "172.18.163.0/24",
        "rangeStart": "172.18.163.215",
        "rangeEnd": "172.18.163.216",
        "gateway": "172.18.163.254"
      }
    }'

and kubectl describe pod, finding interface already add

  Normal  Scheduled       <unknown>  default-scheduler  Successfully assigned default/samplepod to d0506
  Normal  AddedInterface  1s         multus             Add eth0 [10.233.76.149/32]
  Normal  AddedInterface  1s         multus             Add net1 [172.18.163.216/24] from default/macvlan-conf
  Normal  Pulling         1s         kubelet, d0506     Pulling image "alpine"
  Normal  Pulled          1s         kubelet, d0506     Successfully pulled image "alpine"
  Normal  Created         1s         kubelet, d0506     Created container samplepod
  Normal  Started         1s         kubelet, d0506     Started container samplepod

but the interface or ip doesn't exist in pod
[root@d0404 cluster_configuration]# kubectl exec -it samplepod -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if171: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 7e:ec:d8:84:4e:d8 brd ff:ff:ff:ff:ff:ff
    inet 10.233.76.149/32 scope global eth0
       valid_lft forever preferred_lft forever

**Comment by dougbtv** [comment]
Do you mind enabling logging and then showing us the results? Thanks!

Logging parameters here @ https://github.com/intel/multus-cni/blob/master/doc/configuration.md#logging -- place these in the `/etc/cni/net.d/00-multus.conf` on each node
