### ISSUE TITLE
Pod gets stuck in ContainerCreating state if first attempt of CNI ADD fails (Multus CNI, Whereabouts IPAM)

### ISSUE THREAD

**Issue by TothFerenc** [intel/multus-cni#578]
This is a spinoff ticket of https://github.com/kubernetes/kubernetes/issues/96200
I don't know whether this is a Multus specific issue or not. 

**What happened**:
We are using Multus CNI for having multiple network interfaces inside Pod network namespace. Whereabouts IPAM is being used to serve unique IPs within an IP Pool.
In case the IP Pool is fully allocated, if we delete a Pod (under Deployment), a new Pod is started. The deleted Pod is still in Terminating state for a while holding its IP addresses. At this specific point in time the new Pod fails to start, because Multus CNI calls Whereabouts IPAM to request an IP, but it throws an error due to depleted IP Pool. That is expected.
The problem is that the new Pod gets stuck in ContainerCreating state forever. In the meantime the IP address of the old Pod is released, so the next attempt of CNI ADD would pass, but it seems K8s does not retry that.

**What you expected to happen**:
We expect that in case of such failures K8s retries the failing CNI ADD operation to be able to start the Pod. It should not be stuck in a state which requires manual intervention. 

**How to reproduce it (as minimally and precisely as possible)**:
Multus NetworkAttachmentDefinition:
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
 name: whereabouts-nad2
 namespace: whereabouts
spec:
 config: '{
  "cniVersion": "0.3.1",
  "type": "ipvlan",
  "master": "eno6",
  "mode": "l2",
  "ipam": {
   "type": "whereabouts",
   "range": "10.10.10.0/24",
   "range_start": "10.10.10.100",
   "range_end": "10.10.10.128",
   "exclude": ["10.10.10.0/25"]
  }
 }'
```
As you can see the pool size is reduced to a single IP intentionally, so whereabouts can serve 10.10.10.128 only.

Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
  run: multustest2
 name: multustest2
 namespace: whereabouts
spec:
 replicas: 1
 selector:
  matchLabels:
   run: multustest2
 template:
  metadata:
   namespace: whereabouts
   labels:
    run: multustest2
   annotations:
    k8s.v1.cni.cncf.io/networks: whereabouts-nad2
  spec:
   containers:
   - image: busybox:latest
     name: multustest2
     command: [ "/bin/sh", "-c", "while true; do date; sleep 10; done"]
     securityContext:
       runAsNonRoot: true
       runAsUser: 1000
```
Once they are applied, the Pod is running fine:
```
# kubectl get pods -n whereabouts -w
NAME                           READY   STATUS    RESTARTS   AGE
multustest2-594975985d-clp6z   1/1     Running   0          27s
```
Let's delete this Pod and see what happens:
```
# kubectl get pods -n whereabouts -w
NAME                           READY   STATUS    RESTARTS   AGE
multustest2-594975985d-clp6z   1/1     Running   0          27s
multustest2-594975985d-clp6z   1/1     Terminating   0          51s
multustest2-594975985d-fwpms   0/1     Pending       0          0s
multustest2-594975985d-fwpms   0/1     Pending       0          0s
multustest2-594975985d-fwpms   0/1     ContainerCreating   0          0s
multustest2-594975985d-clp6z   0/1     Terminating         0          86s
multustest2-594975985d-clp6z   0/1     Terminating         0          93s
multustest2-594975985d-clp6z   0/1     Terminating         0          93s
```
The new Pod (`multustest2-594975985d-fwpms`) gets stuck in ContainerCreating status.

Events part of Pod describe output:
```
Events:
  Type     Reason                  Age                    From                              Message
  ----     ------                  ----                   ----                              -------
  Normal   Scheduled               <unknown>              default-scheduler                 Successfully assigned whereabouts/multustest2-594975985d-fwpms to tb26-cscf261-workerbm-3
  Warning  FailedCreatePodSandBox  33m                    kubelet, tb26-cscf261-workerbm-3  Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "7a3efb8f68da62fb22a60271c183b6eb796ebd76225455d025273f25939a4da8" network for pod "multustest2-594975985d-fwpms": networkPlugin cni failed to set up pod "multustest2-594975985d-fwpms_whereabouts" network: Multus: [whereabouts/multustest2-594975985d-fwpms]: error adding container to network "whereabouts-nad2": delegateAdd: error invoking DelegateAdd - "ipvlan": error in getting result from AddNetwork: Error at storage engine: Could not allocate IP in range: ip: 10.10.10.100 / - 10.10.10.128 / range: net.IPNet{IP:net.IP{0xa, 0xa, 0xa, 0x0}, Mask:net.IPMask{0xff, 0xff, 0xff, 0x0}}, failed to clean up sandbox container "7a3efb8f68da62fb22a60271c183b6eb796ebd76225455d025273f25939a4da8" network for pod "multustest2-594975985d-fwpms": networkPlugin cni failed to teardown pod "multustest2-594975985d-fwpms_whereabouts" network: delegateDel: error invoking DelegateDel - "ipvlan": error in getting result from DelNetwork: Error deallocating IP: Did not find reserved IP for container 7a3efb8f68da62fb22a60271c183b6eb796ebd76225455d025273f25939a4da8]
  Normal   SandboxChanged          3m21s (x129 over 33m)  kubelet, tb26-cscf261-workerbm-3  Pod sandbox changed, it will be killed and re-created.
```

**Anything else we need to know?**:
Even if it is a special case, we don't think that Multus CNI or Whereabouts IPAM is guilty. It seems K8s is missing a retry mechanism when Pod is being created.
The new Pod can be started if we use low `terminationGracePeriodSeconds` time (<5 sec), because CNI DEL happens earlier than CNI ADD for the new Pod.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.8
- Cloud provider or hardware configuration: bare metal
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): 4.18
- Install tools: custom deployment method using ansible
- Network plugin and version (if this is a network-related bug): Multus CNI v3.4.1, whereabouts v0.1-04ed52b
- Others:

**Comment by dougbtv** [comment]
@TothFerenc thanks a bunch for the report and the :100: write-up. Thanks!

I was able to recreate it reliably. I also encounter the same thing where CNI ADD happens before a CNI DEL, and somehow the situation isn't corrected. Which is semi baffling.

I have a possible fix I put together in short, instead of erroring out in Whereabouts on CNI DEL when the IP address can't be deallocated, I instead just log a warning, and exit normally, reporting

The changes are available in my `stuck-creating` branch, in this commit: https://github.com/dougbtv/whereabouts/commit/9769d4b68292eb75f4afadd9b1e0344d48e70516

Would you be willing to give it a test? I have an image up with the experimental changes:

```
docker pull dougbtv/whereabouts:experimental
```

You can use that image tag in the Whereabouts daemonset, or pull that image and put the binaries in place on each host manually.
```

**Comment by TothFerenc** [comment]
Thanks @dougbtv !
My initial tests were good. Let's wait for few more days until my colleagues test it with different applications and config options.

**Comment by TothFerenc** [comment]
It is going to be fixed in Whereabouts IPAM, so we can close this issue here.
Thanks!
