### ISSUE TITLE
set static route inside a pod

### ISSUE THREAD

**Issue by majorinche** [intel/multus-cni#582]
while there are two interface can exist in one pod, how can we set static routes.
as in most docker image, the command like "ip" or "route" in Centos, which used to add route, is not always supported.

i notice there are two part can do this, like add a annotaion:
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{
        "name": "macvlan-conf",
        "default-route": ["172.18.163.254"]
        }]'

or add NetworkAttachmentDefinition configuration like:
     "ipam": {
        "type": "host-local",
        "subnet": "172.18.163.0/24",
        "rangeStart": "172.18.163.215",
        "rangeEnd": "172.18.163.216",
        "gateway": "172.18.163.254",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ]
      }

but how to add a specific route here?
for example, i like to add following route in a pod:
route add -net 10.233.0.0/16 gw 169.254.1.1

thanks

**Comment by dougbtv** [comment]
I think you can use the route override CNI to do just that to set a static route: https://github.com/redhat-nfvpe/cni-route-override

**Comment by majorinche** [comment]
thank you, it works for me

**Comment by maxpain** [comment]
The problem is that Calico uses 169.254.1.1 as a default gateway. Can we override this behavior? I think in the case of multiple interfaces Calico should add 192.168.8.0/22 route instead of 169.254.1.1 and all traffic to the cluster network will be routed via the calico interface.
