### ISSUE TITLE
Assign static IP to replicas in statefulset

### ISSUE THREAD

**Issue by planky78** [intel/multus-cni#589]
Hello

I have a statefulset with 3 replicas and would like to assign a different static address to each of the pods that are created.

I am successful in a single pod configuration to assign an IP, is there a way to specifiy a different static to each replica pod? Currently the below config will add the same IP and MAC to all the replicas  

spec:
  serviceName: my-app
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
      annotations:
        #k8s.v1.cni.cncf.io/networks: macvlan-conf
        k8s.v1.cni.cncf.io/networks: '[{ "name": "conf-static", "ips": [ "122.126.229.119/24" ], "mac": "00:01:02:03:04:05", "gateway": "132.196.219.254" }]'

Or should/can I do from a configmap 

multus-cni version:v3.6

Any guidanace would be appreciated, or is it a silly idea.

Thanks

**Comment by dougbtv** [comment]
Static CNI is for assigning the address to one pod, unfortunately.

You might consider Whereabouts IPAM CNI to assign addresses within a range to each item in the replicaset: https://github.com/dougbtv/whereabouts
