### ISSUE TITLE
bandwidth useless

### ISSUE THREAD

**Issue by better0332** [intel/multus-cni#590]
my 00-multus.conf file
```
{
  "name": "multus-cni-network",
  "type": "multus",
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
  "delegates": [
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "WARNING",
          "datastore_type": "kubernetes",
          "nodename": "192.168.56.100",
          "mtu": 1450,
          "ipam": {
            "type": "host-local",
            "subnet": "usePodCidr"
          },
          "policy": {
            "type": "k8s"
          },
          "kubernetes": {
            "kubeconfig": "/etc/kubernetes/ssl/kubecfg-kube-node.yaml"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {
            "portMappings": true
          }
        },
        {
          "type": "bandwidth",
          "capabilities": {
            "bandwidth": true
          }
        }
      ]
    }
  ]
}
```
I use `kubernetes.io/ingress-bandwidth: 1M` in pod annotations, It's useless.
can multus support bandwidth now?

my env:
cni: canal
k8s: v1.15.12
multus: nfvpe/multus:v3.6

**Comment by dougbtv** [comment]
Unfortunately, the `kubernetes.io/ingress-bandwidth: 1M` annotation isn't recognized by Multus, you can use a chained CNI plugin in a NetworkAttachmentDefinition with the bandwidth meta plugin alternatively.

Check out section `4.1.2.1.8 "bandwidth"` in the [net-attach-def specification for some other options](https://docs.google.com/document/d/1Ny03h6IDVy_e_vmElOqR7UdTPAG_RNydhVE1Kx54kFQ/edit#).

**Comment by cyclinder** [comment]
Can we do `kubernetes.io/ingress-bandwidth: 1M` to be recognized by multus ? @dougbtv
