### ISSUE TITLE
Clean Up auto generated config

### ISSUE THREAD

**Issue by Mmduh-483** [intel/multus-cni#592]
When multus daemonset is deployed with --multus-conf-file=auto, it generates an auto cnofig file in CNI_DIR, usually it is 00-multus. After removing the multus daemonset and roles, this file will stay which cause to call multus cni that doesn't have the permissions to access k8s api, that cause the multus to fail everytime.

**What would you like to be added**:
Clean up the auto generated config file

**Why is this needed**:
Leaving config file for mulus without permission causing the cluster to not be able to schedule pods

**Comment by adrianchiris** [comment]
It should be noted that in multus v3.4.1 this operation is not observed

so with multus v3.4.1 when you deploy it in a k8s cluster and then delete (daemonset, rbac) pods with primary network keep on working

with multus v3.6 doing the same leaves k8s cluster in an inoperable state as multus CNI calls now fail.

i didnt have time to dig into this issue but it seems that between v3.4.1 and v3.6 we lost the ability of multus to handle failure to access kubernetes API when not nessecary (e.g no secondary network for pod and not `clusterNetwork` crd specified in multus config)

**Comment by adpempx** [comment]
Hi,

do you please have a proper solution?
This is a critical issue Multus-CNI team.

Please let us know as soon as possibile.

Thanks

**Comment by adrianchiris** [comment]
In [NVIDIA network operator](https://github.com/Mellanox/network-operator) we currently WA this issue by deploying multus daemonset with a pre-stop hook which deletes the generated multus cni config file (we use `--multus-config-file=auto`).

see: https://github.com/Mellanox/network-operator/blob/2dcf59f17d737b11632da2f41ed640aaf8323ee5/manifests/stage-multus-cni/0050-multus-ds.yml#L44

**Comment by adpempx** [comment]
@adrianchiris 

you are my hero!

I confirm it is the solution!

Thanks

**Comment by dougbtv** [comment]
Great approach Adrian, I think handling this with an operator is great, that's an excellent way to make an opinionated way to handle the lifecycle and to denote node readiness based on a specific scenario.
