### ISSUE TITLE
macvlan with ipam dhcp and static routes with route-override not working

### ISSUE THREAD

**Issue by nsaeris** [intel/multus-cni#602]
I have following network-attachment-definition. macvlan interface comes up but route addition is not successful. I see following error in kubelet logs:
Jan 23 17:38:23 srv microk8s.daemon-containerd[3464761]: failed to add route: {Dst:{IP:172.16.0.0 Mask:fff00000} GW:x.y.z.1}: network is unreachablefailed to add route: {Dst:{IP:192.168.0.0 Mask:ffff0000} GW:x.y.z.1}: network is unreachablefailed to add route: {Dst:{IP:0.0.0.0 Mask:00000000} GW:x.y.z.254}: network is unreachable

Jan 23 17:38:23 srv microk8s.daemon-containerd[3464633]: I0123 09:38:23.843349 3464633 event.go:221] Event(v1.ObjectReference{Kind:"Pod", Namespace:"test", Name:"samplepod", UID:"af44a564-c300-477c-87c7-af2d846c7cc4", APIVersion:"v1", ResourceVersion:"798928", FieldPath:""}): type: 'Normal' reason: 'AddedInterface' Add net1 [x.y.z.135/18] from test-macvlan-conf

`apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
name: test-macvlan-conf
namespace: test
spec:
config: '{
"cniVersion": "0.3.1",
"name": "test-macvlan-conf",
"plugins": [
{
"type": "macvlan",
"master": "ens192.121",
"mode": "bridge",
"ipam": {
"type": "dhcp"
}
},
{
"type": "route-override",
"flushroutes": true,
"addroutes": [
{
"dst": "172.16.0.0/12",
"gw": "x.y.z.1"
},
{
"dst": "192.168.0.0/16",
"gw": "x.y.z.1"
},
{
"dst": "0.0.0.0/0",
"gw": "a.b.c.d"
}
]
}
]
}'
`

**Comment by s1061123** [comment]
Q. 
Are the dhcp assigned ip address, "x.y.z.1", and "a.b.c.d" in same subnet, or different? As far as I know, gateway ip address should be in same subnet of interface address.

I recommend you to configure your configuration in container, by your hand.  
Following container image has ip route tools so you can run this image with privilege and try your configuration is valid or not.
https://hub.docker.com/r/centos/tools/

**Comment by s1061123** [comment]
BTW, this issue seems not to be multus issue, just cni-route-override issue (or troubleshooting?).
Let's continue to discuss in https://github.com/redhat-nfvpe/cni-route-override/issues/15#issuecomment-766144461
