### ISSUE TITLE
QUERY: How to associate multiple IPAM sections in same NAD, in order to use different routing tables (via SBR plugin) for each IPAM block.

### ISSUE THREAD

**Issue by superfix906** [intel/multus-cni#605]
Hi, today, using NADs, under "plugins" section, we can add one IPAM section and chain it with SBR plugin to configure a separate routing table for it (table 100).  Also we can add multiple IP addresses to same IPAM section ("static" plugin), by specifying the list of IPs in the IPAM section, under NAD.

Requirement : Is there a way to have multiple IPAM sections  + SBR for each section in same NAD ?
We want to add multiple IPAM sections (each with its own default gw), in same NAD, and configure "SBR" plugin for each such IPAM. Thus, having multiple routing tables (just like "table 100" in pod), each with its own IPAM entries.

Thanks in Advance !!

**Comment by dougbtv** [comment]
Unfortunately, I don't believe there's a way to have multiple IPAM sections for a single plugin. Additionally, IPAM and SBR are kind of independent.

Potentially, the SBR plugin is possibly still in need of feature enhancement.

One thing you might want to try is the route-override plugin: https://github.com/redhat-nfvpe/cni-route-override (this allows CNI ARGS, and these are supported in multus as a network annotation) -- however, we are unsure if SBR and route-override may conflict with one another, so it would be experimental.

You may want to start a discussion with the CNI maintainers regarding the SBR plugin, to bring up this case, potentially it's worth opening up an issue in the reference CNI plugins @ https://github.com/containernetworking/plugins/

**Comment by superfix906** [comment]
Hi @dougbtv, thanks for all details.  Appreciate the response !

Have opened an issue at @ https://github.com/containernetworking/plugins/

As for the https://github.com/redhat-nfvpe/cni-route-override plugin, I see it can help with route manipulations, but I think it does it in the default routing table only (as no options to customize table), whereas here the ask is to have different routing tables, for different IPAMs. So I guess, it wont help. Do you think it can still be used somehow for the expected use case ?

**Comment by dougbtv** [comment]
I think having it operate on different routing tables would be a feature, I think it's best to have this handled from the SBR side. Thanks @superfix906 !

It's kind of a new frontier to handle multiple routing tables in CNI at the moment! (But rather interesting, regardless!)
