### ISSUE TITLE
Multus on GKE

### ISSUE THREAD

**Issue by hyavari** [intel/multus-cni#620]
I am trying to run Multus on GKE through guidelines but I see that pods can't run:
 kube-system   kube-multus-ds-amd64-h2x8h                                 0/1     RunContainerError   0          8s
kube-system   kube-multus-ds-amd64-h89qm                                 0/1     CrashLoopBackOff    1          9s
kube-system   kube-multus-ds-amd64-m9mnz                                 0/1     RunContainerError   1          8s

Is there any specific hint for running Multus on GKE? 
I want to make a second interface for some pods that uses the node host network.

**Comment by hyavari** [comment]
Reason is : 
Message:      error while creating mount source path '/opt/cni/bin': mkdir /opt/cni: read-only file system

So what is the solution?

**Comment by hyavari** [comment]
I added a /home before all the paths on the host like this:
hostPath:
            path: /home/opt/cni/bin

and it's resolved the issue of "read-only" path. 
Is it the correct solution?

**Comment by hyavari** [comment]
Solution:
You have to change nodes' OS from Optimized OS to others like Ubuntu.

**Comment by dougbtv** [comment]
Thanks for following up, it may be that you need to check what directory is
used for the CNI binaries on that system.

**Comment by hyavari** [comment]
Thanks @dougbt . /etc/ is read-only on Optimized OS.
