### ISSUE TITLE
Migrate from glide to go modules

### ISSUE THREAD

**Issue by s1061123** [intel/multus-cni#84]
In glide README ([https://github.com/Masterminds/glide#golang-dep](https://github.com/Masterminds/glide#golang-dep), Glide asks users to switch to [golang/dep](https://github.com/golang/dep).

So we should move to use golang/dep, not soon, but near future.

**Comment by rkamudhan** [comment]
+1

**Comment by s1061123** [comment]
Golang community start to use [go modules](https://github.com/golang/go/wiki/Modules), so rename it.
